const BRASIL_TAGS = {
  cachoeira: { e: '💦', l: 'Cachoeira' },
  gruta:     { e: '🕯️', l: 'Gruta & caverna' },
  aguas:     { e: '💧', l: 'Águas minerais' },
  vilarejo:  { e: '🏡', l: 'Vilarejo pra desacelerar' },
};

const MG_REGIOES = [
  {
    id: 'mg-bate-volta',
    nome: 'Até 2h30 de BH — cabe num sábado',
    emoji: '🚗',
    resumo: 'O raio que dá pra sair depois do café e dormir em casa, ou esticar numa pousada sem sentir que passou o fim de semana dirigindo. É onde mora o barroco mineiro e a serra mais perto.',
    paises: [
      {
        slug: 'mg-inhotim', nome: 'Inhotim & Brumadinho', bandeira: '🎨',
        tags: ['historia', 'natureza', 'gastronomia'],
        resumo: 'Um museu a céu aberto: galerias de arte contemporânea espalhadas por um jardim botânico de mata, a 1h de BH. É o passeio mais fácil de encaixar da lista inteira — e o único em que o dia todo passa andando devagar.',
        quando: 'Qua–dom e feriados · em janeiro e julho abre também na terça · quarta tem entrada gratuita, com retirada prévia online',
        transporte: { modo: '🚗', rotulo: 'Carro até a portaria', texto: 'Uma hora de BH pela MG-040. Lá dentro é tudo a pé por caminho de jardim, com carrinho elétrico pago à parte pra encurtar as pernas longas. Leve protetor e sapato confortável.' },
        rotuloPortas: 'Saindo de BH',
        portas: [{ c: '≈1h', n: 'Brumadinho · MG-040', t: 'porta' }],
        cidades: [
          { n: 'As galerias', tags: ['historia'], d: 'Pavilhões construídos para uma obra ou um artista só — Adriana Varejão, Cildo Meireles, Lygia Pape, entre outros — mais as obras soltas pelo parque. É arte contemporânea de verdade, não passeio de jardim com escultura.' },
          { n: 'O jardim botânico', tags: ['natureza'], d: 'O parque é jardim botânico registrado: lagos, palmeiras, orquidário e mata. Mesmo quem não liga pra arte contemporânea passa o dia bem.' },
          { n: 'Um dia ou dois', tags: [], d: 'O ingresso vem em versão de 1, 2 ou 3 dias. Em um dia dá pra ter uma boa noção; em dois você percorre os eixos sem correr entre uma instalação e outra.' },
          { n: 'Brumadinho', tags: ['gastronomia'], d: 'A cidade tem pousada e restaurante pra quem quer dormir e voltar no dia seguinte com o ingresso de dois dias — bem melhor que fazer tudo num sábado.' },
        ],
      },
      {
        slug: 'mg-circuito-ouro', nome: 'Circuito do Ouro', bandeira: '⛪',
        tags: ['historia', 'cidade', 'gastronomia', 'cachoeira'],
        resumo: 'O quadrilátero barroco: casario setecentista, igreja de Aleijadinho e mina de ouro, tudo num raio curto entre si. Dá pra combinar duas ou três dessas no mesmo fim de semana — o erro é tentar as cinco.',
        quando: 'Abr–set (seca, céu limpo) · evite feriadão em Ouro Preto, que lota',
        estradaReal: 'Carimba em Ouro Preto e Mariana (Diamantes) · Congonhas e Santo Antônio do Leite (Velho)',
        transporte: { modo: '🚗', rotulo: 'Carro, e sapato bom', texto: 'As distâncias entre as cidades são curtas, mas as ladeiras de Ouro Preto e Mariana são de pedra e íngremes de verdade. Estacione uma vez e ande a pé.' },
        rotuloPortas: 'Saindo de BH',
        portas: [
          { c: '≈1h15', n: 'Congonhas · BR-040', t: 'porta' },
          { c: '≈1h45', n: 'Ouro Preto · BR-356', t: 'porta' },
          { c: '≈2h', n: 'Mariana / Lavras Novas', t: 'regional' },
        ],
        cidades: [
          { n: 'Ouro Preto', tags: ['historia', 'cidade', 'gastronomia'], d: 'Patrimônio Mundial da Unesco desde 1980. Praça Tiradentes, Museu da Inconfidência, Casa dos Contos e a São Francisco de Assis — projeto de Aleijadinho com pintura de Ataíde. É a mais movimentada da lista, e ainda assim imperdível.' },
          { n: 'Lavras Novas', tags: ['vilarejo', 'cachoeira', 'montanha'], d: 'Distrito de Ouro Preto virado vilarejo de pousada boa, lareira e restaurante. Cachoeira dos Namorados e do Castelinho de dia, jantar com vista à noite. A melhor escapada romântica do raio de 2h.' },
          { n: 'Mariana', tags: ['historia', 'cidade'], d: 'Primeira capital de Minas. A Praça Minas Gerais tem duas igrejas e o pelourinho no mesmo conjunto; a Catedral da Sé tem o órgão alemão setecentista que ainda dá concerto. Melhor emendada com Ouro Preto do que sozinha.' },
          { n: 'Mina da Passagem', tags: ['historia'], d: 'Entre Ouro Preto e Mariana. Descida de trolley por 315 m de galeria até uns 120 m de profundidade, onde tem um lago de água transparente. Passeio de ~45 min, aberto todos os dias.' },
          { n: 'Congonhas', tags: ['historia'], d: 'Os 12 Profetas em pedra-sabão de Aleijadinho no adro do Santuário do Bom Jesus de Matosinhos — Patrimônio Mundial da Unesco. Com o Museu de Congonhas, fecha um bate-volta de um dia.' },
          { n: 'Santo Antônio do Leite', tags: ['vilarejo', 'cachoeira'], d: 'Outro distrito de Ouro Preto, esse quase sem turista. Pousada, ateliê, comida de fogão a lenha e silêncio. Não é lugar de fazer roteiro: é de não fazer nada.' },
        ],
        aviso: 'O Trem da Vale entre Ouro Preto e Mariana está parado desde 2020. A ferrovia entrou em nova etapa de recuperação em 2026 e a prefeitura de Mariana fala em retorno só em 2027 — não monte o passeio contando com ele.',
      },
      {
        slug: 'mg-caraca', nome: 'Serra do Caraça', bandeira: '🐺',
        tags: ['montanha', 'natureza', 'historia', 'cachoeira'],
        resumo: 'Um colégio-santuário de 1774 dentro de uma reserva de montanha, entre Catas Altas e Santa Bárbara. À noite, lobo-guará sobe a escadaria da igreja pra comer. É o passeio mais fora do comum a 2h de BH.',
        quando: 'O ano todo · abr–set pras trilhas secas',
        estradaReal: 'Carimba em Catas Altas, Santa Bárbara e Ipoema (Diamantes) — o Santuário do Caraça é ponto próprio da rota',
        transporte: { modo: '🚗', rotulo: 'Carro até a portaria', texto: 'Da portaria até o santuário ainda tem alguns quilômetros de estrada dentro da reserva. As trilhas (cachoeiras, picos) saem do próprio santuário a pé.' },
        rotuloPortas: 'Saindo de BH',
        portas: [
          { c: '≈2h', n: 'Catas Altas · BR-381', t: 'porta' },
          { c: '≈2h', n: 'Santa Bárbara', t: 'porta' },
          { c: '≈1h30', n: 'Ipoema (Itabira)', t: 'regional' },
        ],
        cidades: [
          { n: 'Santuário do Caraça', tags: ['historia', 'natureza', 'montanha'], d: 'Hospedagem em pensão completa no antigo colégio, trilhas pra cachoeira e pros picos e a "hora do lobo" à noite — tradição desde 1982, aberta principalmente a quem está hospedado. Reserve com antecedência.' },
          { n: 'Catas Altas', tags: ['vilarejo', 'historia'], d: 'Vila colonial pequena aos pés da serra, com a Matriz de Nossa Senhora da Conceição e um centro que se vê numa manhã. Boa base pra quem não conseguir vaga dentro do santuário.' },
          { n: 'Santa Bárbara', tags: ['vilarejo', 'historia'], d: 'A outra porta do Caraça. Centro histórico miúdo, casa de cultura e cachoeiras no entorno. Combina com Catas Altas no mesmo fim de semana.' },
          { n: 'Ipoema', tags: ['vilarejo', 'cachoeira'], d: 'Distrito de Itabira, terra de tropeiro — o Museu do Tropeiro é o cartão da vila. Cachoeiras, estradas rurais e quase nenhum turista. Pro interior sem fila.' },
        ],
      },
      {
        slug: 'mg-cipo', nome: 'Serra do Cipó', bandeira: '🏞️',
        tags: ['natureza', 'cachoeira', 'montanha', 'gruta'],
        resumo: 'Cerrado de altitude a 1h40 de BH: dezenas de cachoeiras, cânions e campo rupestre. É a melhor relação natureza/tempo de carro que existe saindo da capital.',
        quando: 'Abr–set pra estrada e trilha secas · out–mar as cachoeiras enchem, mas tem risco de cabeça d\'água',
        estradaReal: 'Carimba em Santana do Riacho (Diamantes) · Cordisburgo fica fora da rota',
        transporte: { modo: '🚗', rotulo: 'MG-010 e muita terra', texto: 'A MG-010 é asfaltada até a região; boa parte dos atrativos fica em estrada de terra depois. Carro baixo passa na seca com cuidado — na chuva, complica.' },
        rotuloPortas: 'Saindo de BH',
        portas: [
          { c: '≈1h40', n: 'Serra do Cipó (Santana do Riacho) · MG-010', t: 'porta' },
          { c: '≈1h40', n: 'Cordisburgo · BR-040 + MG-231', t: 'porta' },
        ],
        cidades: [
          { n: 'Parque Nacional da Serra do Cipó', tags: ['natureza', 'cachoeira'], d: 'Pela Portaria Areias saem a Cachoeira da Farofa (uns 7 km de caminhada) e o Cânion das Bandeirinhas, bem mais longe — o circuito completo passa de 20 km e leva o dia inteiro. Vá cedo.' },
          { n: 'Cachoeira Serra Morena', tags: ['cachoeira'], d: 'Saindo da MG-010 são uns 5,5 km de estrada de terra até a portaria. São duas quedas na mesma propriedade e a taxa dá acesso às duas, com banheiro e estacionamento inclusos. Tem horário-limite pra ficar — chegue de manhã.' },
          { n: 'Cachoeira Capivara', tags: ['cachoeira', 'natureza'], d: 'Uma das maiores quedas da região, dentro da APA Morro da Pedreira. Estrada de terra longa e trilha no fim. O acesso não é regularizado — a cobrança é informal e já houve disputa entre morador e proprietário. Confirme na hospedagem se está liberado.' },
          { n: 'Mirante Serra do Cipó', tags: ['montanha', 'natureza'], d: 'Parada na subida da MG-010, do lado esquerdo: vista aberta das montanhas e dos vales sem descer do asfalto nem pagar nada. O melhor pôr do sol de graça da região.' },
          { n: 'Santana do Riacho', tags: ['vilarejo', 'natureza'], d: 'O município que abriga o parque. A vida turística se concentra no distrito de Cardeal Mota e ao longo da MG-010: pousada, restaurante, bike e cavalgada.' },
          { n: 'Cordisburgo', tags: ['gruta', 'historia'], d: 'A Gruta do Maquiné, aberta à visitação desde 1908, é a mais antiga do país nesse papel — salões iluminados, visita guiada. A cidade é a terra de Guimarães Rosa e tem o museu na casa onde ele nasceu.' },
        ],
        aviso: 'Quase toda cachoeira famosa do Cipó (Serra Morena, Capivara, Véu da Noiva, Cachoeira Grande) fica em propriedade particular: portaria, taxa por pessoa em dinheiro e horário-limite de entrada. Preço e funcionamento mudam de temporada e algumas fecham sem aviso — ligue antes de encarar a estrada de terra.',
      },
      {
        slug: 'mg-lapinha', nome: 'Lapinha da Serra', bandeira: '🏕️',
        tags: ['montanha', 'natureza', 'cachoeira', 'vilarejo'],
        resumo: 'Vilarejo de Santana do Riacho a 13 km da sede, encaixado no pé da Serra do Breu, com uma lagoa represada que reflete a serra inteira. Mesmo município da Serra do Cipó, acesso por outro lado — e clima completamente diferente: aqui não tem agito nenhum.',
        quando: 'Abr–set · na chuva a estrada de terra piora bastante',
        estradaReal: 'Carimba em Santana do Riacho (Diamantes) — Lapinha da Serra é ponto próprio da rota',
        transporte: { modo: '🚗', rotulo: 'Terra no fim', texto: 'O acesso é por estrada de terra em condições medianas, mas em geral passável por carro comum no tempo seco. São 13 km depois da sede de Santana do Riacho.' },
        rotuloPortas: 'Saindo de BH',
        portas: [{ c: '≈2h20', n: 'Lapinha da Serra · MG-010 + terra', t: 'porta' }],
        cidades: [
          { n: 'Lagoa da Lapinha', tags: ['natureza'], d: 'A represa com a serra atrás é o cartão-postal do lugar. Uma subida curta a partir do vilarejo já entrega a vista de cima, com a lagoa e o vale inteiro.' },
          { n: 'Serra do Breu', tags: ['montanha', 'natureza'], d: 'A parede que fecha o vilarejo. Trilhas de meio período, mirantes e o pôr do sol que faz a fama do lugar entre casais.' },
          { n: 'Travessia Lapinha × Tabuleiro', tags: ['montanha'], d: 'A trilha clássica do Espinhaço: cerca de 42 km da capelinha de Lapinha até a portaria do parque do Tabuleiro, em dois ou três dias com pernoite. Vai de guia. Liga este bloco direto no de Conceição do Mato Dentro.' },
          { n: 'O vilarejo', tags: ['vilarejo'], d: 'Poucas pousadas e restaurantes, sem estrutura de cidade. É exatamente o motivo de ir — e o motivo de reservar com antecedência em feriado.' },
        ],
      },
    ],
  },
  {
    id: 'mg-fim-de-semana',
    nome: '3h a 5h — fim de semana inteiro',
    emoji: '🗓️',
    resumo: 'Aqui não compensa bate-volta: são duas ou três noites. Em troca, entram as cachoeiras mais impressionantes do estado, a cidade mais charmosa pra casal e Diamantina, que não cabe num sábado.',
    paises: [
      {
        slug: 'mg-tiradentes', nome: 'Tiradentes & São João del-Rei', bandeira: '🚂',
        tags: ['historia', 'gastronomia', 'cidade', 'montanha'],
        resumo: 'A cidade mais charmosa da lista, e a que menos exige da sua perna. Casario colonial inteiro, restaurante bom de verdade, serra atrás e uma maria-fumaça de 1881 ligando as duas cidades.',
        quando: 'O ano todo · em agosto tem o festival de gastronomia e a cidade lota',
        estradaReal: 'Carimba em Tiradentes, São João del-Rei e Prados/Bichinho (Velho)',
        transporte: { modo: '🚂', rotulo: 'Carro + trem', texto: 'A maria-fumaça faz os ~12 km entre São João del-Rei e Tiradentes em cerca de 45 min, de quinta a domingo, com duas ou três saídas por dia. Confirme o quadro de horários com a VLI antes — muda em feriado.' },
        rotuloPortas: 'Saindo de BH',
        portas: [
          { c: '≈3h10', n: 'Tiradentes · BR-040 + BR-265', t: 'porta' },
          { c: '≈3h', n: 'São João del-Rei', t: 'porta' },
        ],
        cidades: [
          { n: 'Tiradentes', tags: ['historia', 'gastronomia', 'vilarejo'], d: 'Matriz de Santo Antônio com retábulo dourado e órgão português, Igreja do Rosário, Museu Sant\'Ana na antiga cadeia. Centro pequeno, plano e cheio de café, ateliê e restaurante. Fim de semana romântico sem trilha.' },
          { n: 'Serra de São José', tags: ['natureza', 'montanha'], d: 'A parede de serra que fecha o horizonte de Tiradentes. Trilhas, mirantes e cachoeiras logo ali — dá pra encaixar meio período sem pegar estrada.' },
          { n: 'Bichinho', tags: ['vilarejo', 'gastronomia'], d: 'Distrito de Prados a uns 10 km de Tiradentes, virado vilarejo de artesão: marcenaria, ateliê, loja de decoração e restaurante. Não sustenta a viagem sozinho, mas é a meia diária que melhora o fim de semana.' },
          { n: 'São João del-Rei', tags: ['historia', 'cidade'], d: 'Maior e mais viva que a vizinha: igrejas setecentistas, a estação ferroviária de 1881 com o museu do trem e uma cena de bar que Tiradentes não tem.' },
        ],
      },
      {
        slug: 'mg-tabuleiro', nome: 'Conceição do Mato Dentro', bandeira: '💦',
        tags: ['cachoeira', 'natureza', 'montanha'],
        resumo: 'Espinhaço mais selvagem, cerca de 1h ao norte do Cipó. É onde está a Cachoeira do Tabuleiro — 273 m, a mais alta de Minas e uma das mais altas do Brasil.',
        quando: 'Abr–set · na chuva as estradas de terra e as trilhas complicam',
        estradaReal: 'Carimba em Conceição do Mato Dentro e Itambé do Mato Dentro (Diamantes)',
        transporte: { modo: '🚗', rotulo: 'Carro, terra no fim', texto: 'O distrito do Tabuleiro fica a uns 18 km da sede, boa parte em estrada de terra. Do estacionamento em diante é trilha a pé.' },
        rotuloPortas: 'Saindo de BH',
        portas: [
          { c: '≈3h', n: 'Conceição do Mato Dentro · MG-010', t: 'porta' },
          { c: '≈2h05', n: 'Itambé do Mato Dentro', t: 'regional' },
        ],
        cidades: [
          { n: 'Cachoeira do Tabuleiro', tags: ['cachoeira', 'natureza'], d: 'Queda de 273 m num anfiteatro de pedra. A trilha até o poço tem cerca de 3 km ida e volta, nível moderado. O parque cobra ingresso, limita o número de visitantes por dia e tem horário-limite pra entrar.' },
          { n: 'Cachoeira Rabo de Cavalo', tags: ['cachoeira'], d: 'A outra queda muito procurada da região, num vale fechado. Combina com o Tabuleiro em dois dias, não no mesmo.' },
          { n: 'Parque Estadual Serra do Intendente', tags: ['natureza', 'montanha'], d: 'Trilhas, poços e mirantes na mesma serra, com bem menos gente que o Tabuleiro.' },
          { n: 'Itambé do Mato Dentro', tags: ['cachoeira', 'vilarejo'], d: 'Município vizinho, mais perto de BH que a própria Conceição, e bem menos massacrado. Cachoeira da Vitória (quase 70 m, a 4,5 km da cidade), Cachoeira do Funil com três quedas em sequência e a do Lúcio, de acesso fácil a pé.' },
        ],
        aviso: 'O Tabuleiro passou quase cinco anos com acesso restrito por questões de segurança geológica e só foi reaberto integralmente em julho de 2026. Cheque com a prefeitura ou o parque no dia anterior — o acesso já foi suspenso outras vezes.',
      },
      {
        slug: 'mg-diamantina', nome: 'Diamantina', bandeira: '💎',
        tags: ['historia', 'cidade', 'gastronomia', 'cachoeira', 'gruta'],
        resumo: 'Patrimônio Mundial da Unesco no alto do Espinhaço, terra de JK e de Chica da Silva. É a maior e mais viva das cidades históricas mineiras longe de BH — e a base natural pra emendar com Serro e Milho Verde.',
        quando: 'Abr–out, quando acontecem as Vesperatas · fora dessa janela a cidade fica bem mais quieta',
        estradaReal: 'Carimba em Diamantina (Diamantes), o ponto de partida — a Vila do Biribiri também é ponto da rota',
        transporte: { modo: '🚗', rotulo: 'Asfalto o caminho todo', texto: 'Quatro horas de BH pela BR-040 e depois BR-259, tudo asfaltado. De Diamantina dá pra descer pro Serro e Milho Verde, aí sim com trechos de terra.' },
        rotuloPortas: 'Saindo de BH',
        portas: [{ c: '≈4h', n: 'Diamantina · BR-040 + BR-259', t: 'porta' }],
        cidades: [
          { n: 'Centro histórico', tags: ['historia', 'cidade'], d: 'Rua da Quitanda, Praça JK, Casa de Chica da Silva, Museu do Diamante, Catedral e a Casa da Glória com o passadiço azul entre dois sobrados. Tudo a pé, em ladeira.' },
          { n: 'Vesperata', tags: ['historia'], d: 'Bandas tocam das sacadas e janelas dos casarões da Rua da Quitanda, com o público na rua. Acontece entre abril e outubro, em datas marcadas, e precisa de ingresso comprado antes.' },
          { n: 'Vila de Biribiri', tags: ['vilarejo', 'cachoeira'], d: 'A uns 13 km do centro, dentro do Parque Estadual do Biribiri: vila operária da fábrica de tecidos de 1876, desativada nos anos 70 e preservada. Cachoeiras e inscrições rupestres no parque em volta.' },
          { n: 'Gruta do Salitre', tags: ['gruta'], d: 'A 9 km do centro, formação de quartzito com fendas e paredões de até 80 m. Passeio curto, bom pra encaixar numa manhã.' },
        ],
      },
      {
        slug: 'mg-canastra', nome: 'Serra da Canastra', bandeira: '🚙',
        tags: ['natureza', 'cachoeira', 'montanha', 'gastronomia', 'roadtrip'],
        resumo: 'Parque nacional criado em 1972 pra proteger a nascente do São Francisco: chapadão aberto, cachoeira de mais de 180 m, lobo-guará e o queijo mais famoso do país. Fica na mesma direção de Capitólio.',
        quando: 'Abr–set · na chuva boa parte das estradas de terra vira problema sério',
        transporte: { modo: '🚙', rotulo: '4x4 faz diferença', texto: 'A MG-050 é asfaltada, mas os acessos dentro e em volta do parque são de terra e muitos estão em má conservação — vários pedem 4x4. Da sede de São Roque de Minas até a Portaria 1 são uns 7 km de estrada de terra e quartzito subindo a serra.' },
        rotuloPortas: 'Saindo de BH',
        portas: [
          { c: '≈4h45', n: 'São Roque de Minas · BR-381 + MG-050', t: 'porta' },
          { c: '≈4h35', n: 'Vargem Bonita (parte baixa da Casca d\'Anta)', t: 'regional' },
        ],
        cidades: [
          { n: 'Cachoeira Casca d\'Anta', tags: ['cachoeira', 'natureza'], d: 'Mais de 180 m de queda, uma das mais altas do Brasil. Tem parte alta e parte baixa, com acesso e trilha próprios cada uma — não dá pra ir de uma pra outra a pé com facilidade. Escolha antes.' },
          { n: 'Nascente do São Francisco', tags: ['natureza'], d: 'A nascente histórica do rio, na parte alta do parque. Motivo pelo qual o parque existe, e um dos poucos lugares onde a paisagem é chapadão aberto de horizonte a horizonte.' },
          { n: 'São Roque de Minas', tags: ['vilarejo', 'gastronomia'], d: 'A principal porta do parque e onde fica a maior parte dos atrativos e da hospedagem. Cidade pequena, com pousada e restaurante.' },
          { n: 'Queijo canastra', tags: ['gastronomia'], d: 'A região é a origem do queijo canastra, com queijarias abertas à visita ao longo das estradas. Vale programar uma parada em vez de comprar na beira da pista.' },
        ],
      },
      {
        slug: 'mg-ibitipoca', nome: 'Ibitipoca', bandeira: '🍃',
        tags: ['natureza', 'cachoeira', 'montanha', 'gruta', 'vilarejo'],
        resumo: 'Parque estadual pequeno e cultuado, de campo rupestre, gruta e rio de água escura, com o vilarejo de Conceição do Ibitipoca do lado de fora cheio de pousada boa. É o parque mais controlado de Minas — e o que mais recompensa quem planeja.',
        quando: 'Abr–set pras trilhas secas · em feriado e alta temporada o agendamento esgota com antecedência',
        transporte: { modo: '🚗', rotulo: 'Carro até o vilarejo', texto: 'Cerca de 4h45 de BH pela BR-040, passando por Juiz de Fora e Lima Duarte. O parque se faz a pé: os circuitos saem da portaria e são de meio período a dia inteiro.' },
        rotuloPortas: 'Saindo de BH',
        portas: [{ c: '≈4h45', n: 'Conceição do Ibitipoca (Lima Duarte) · BR-040', t: 'porta' }],
        cidades: [
          { n: 'Circuito Janela do Céu', tags: ['montanha', 'natureza'], d: 'O passeio mais famoso do parque: mirante debruçado sobre o vale, com poço no caminho. Tem cota diária própria, menor que a do parque, e a entrada só é liberada no comecinho da manhã.' },
          { n: 'Circuito das Águas', tags: ['cachoeira'], d: 'Cachoeiras e piscinas naturais de água escura de tanino, que é a assinatura visual de Ibitipoca. O circuito mais fácil de encaixar em meio período.' },
          { n: 'Circuito do Pião', tags: ['natureza', 'gruta'], d: 'O lado das grutas e formações de quartzito, com trechos de mata e campo rupestre.' },
          { n: 'Conceição do Ibitipoca', tags: ['vilarejo', 'gastronomia'], d: 'O vilarejo fora da portaria concentra pousada, restaurante e a vida noturna possível. Dá pra ficar bem sem entrar no parque todo dia — o que ajuda, já que a entrada é limitada.' },
        ],
        aviso: 'Agendamento eletrônico é obrigatório e o parque tem teto diário de visitantes, com cota separada e menor pro Circuito Janela do Céu. Não abre todos os dias da semana e a entrada tem horário-limite. Regras, cotas e valores já mudaram várias vezes — confirme no site do parque antes de reservar pousada.',
      },
      {
        slug: 'mg-serro', nome: 'Serro & Milho Verde', bandeira: '🧀',
        tags: ['vilarejo', 'gastronomia', 'historia', 'cachoeira'],
        resumo: 'Minas raiz no alto do Espinhaço: queijo com origem reconhecida, casario colonial e dois vilarejos de estrada de terra que são a definição de pousada charmosa com cachoeira perto.',
        quando: 'Abr–set · a estrada de terra fica ruim depois de chuva forte',
        estradaReal: 'Carimba no Serro (Diamantes) — Milho Verde e São Gonçalo do Rio das Pedras são pontos próprios da rota',
        transporte: { modo: '🚗', rotulo: 'Carro alto ajuda', texto: 'Entre Serro, Milho Verde e São Gonçalo do Rio das Pedras a ligação é de terra, com trechos ruins. Dá pra chegar por asfalto contornando, mas o miolo é terra.' },
        rotuloPortas: 'Saindo de BH',
        portas: [
          { c: '≈4h', n: 'Serro · MG-010 ou BR-259', t: 'porta' },
          { c: '≈4h45', n: 'Milho Verde', t: 'regional' },
        ],
        cidades: [
          { n: 'Milho Verde', tags: ['vilarejo', 'cachoeira', 'gastronomia'], d: 'Distrito do Serro: casinhas coloridas, rua de terra, a igreja de Nossa Senhora dos Prazeres e cachoeira em volta (Lajeado, Moinho). Pousada charmosa, comida mineira e pôr do sol de mirante — talvez o lugar mais romântico da lista.' },
          { n: 'Serro', tags: ['historia', 'gastronomia'], d: 'Sede do município, centro histórico tombado, igrejas e casarões. O queijo do Serro é dos poucos do país com origem reconhecida — vale comprar direto na queijaria.' },
          { n: 'São Gonçalo do Rio das Pedras', tags: ['vilarejo', 'cachoeira'], d: 'O terceiro vilarejo do triângulo, entre os dois anteriores. Menor e mais quieto ainda, com cachoeira a pé da vila.' },
        ],
      },
      {
        slug: 'mg-capitolio', nome: 'Capitólio & Lago de Furnas', bandeira: '🛶',
        tags: ['natureza', 'cachoeira', 'montanha'],
        resumo: 'Os cânions de quartzito do Lago de Furnas, com cachoeira caindo direto na água. É a paisagem mais "uau" a menos de 4h de BH — e a que mais exige planejamento.',
        quando: 'Abr–set pra água mais transparente · evite feriadão, que o lago vira fila de lancha',
        transporte: { modo: '🛶', rotulo: 'Carro + lancha', texto: 'Os cânions só se veem de barco: lancha, escuna ou caiaque saindo das marinas. Em terra, mirantes e cachoeiras têm acesso por estrada de terra e boa parte cobra entrada.' },
        rotuloPortas: 'Saindo de BH',
        portas: [{ c: '≈3h55', n: 'Capitólio · BR-381 + MG-050', t: 'porta' }],
        cidades: [
          { n: 'Cânions de Furnas', tags: ['natureza'], d: 'O passeio clássico de lancha entre paredões de pedra. Depois do desabamento de 2022, a entrada no trecho principal é limitada a uma embarcação por vez, com monitoramento geológico diário e proibição de parar e nadar em partes do percurso.' },
          { n: 'Cachoeira Lagoa Azul', tags: ['cachoeira'], d: 'Queda com poço de água esverdeada, uma das mais procuradas da região. Acesso por propriedade particular, com taxa.' },
          { n: 'Mirante dos Canyons', tags: ['montanha', 'natureza'], d: 'A vista dos cânions por cima, sem barco — o cartão-postal da região no fim de tarde.' },
          { n: 'Cachoeira da Filó', tags: ['cachoeira'], d: 'Complexo de quedas e poços em série, bom pra passar o dia. Também é acesso pago, por propriedade privada.' },
        ],
        aviso: 'Em janeiro de 2022 um paredão desabou sobre lanchas num dos cânions e dez pessoas morreram. A visitação reabriu com regras rígidas, mas o passeio depende do monitoramento do dia e pode ser cancelado sem aviso. Não deixe pro último dia da viagem.',
      },
      {
        slug: 'mg-sul-serras', nome: 'Serras do sul: São Thomé & Carrancas', bandeira: '🪨',
        tags: ['cachoeira', 'natureza', 'montanha', 'vilarejo'],
        resumo: 'Duas cidades do sul de Minas na mesma faixa de 4h30, cada uma com uma vocação: Carrancas é um parque de cachoeiras; São Thomé é pedra, mirante e uma personalidade mística que não existe em outro lugar.',
        quando: 'Abr–set (seca) pra estrada de terra · a água fica mais transparente e o risco de cabeça d\'água cai',
        estradaReal: 'Carimba em Carrancas e São Thomé das Letras (Velho)',
        transporte: { modo: '🚗', rotulo: 'Carro e taxa de entrada', texto: 'Quase toda cachoeira dessas duas está dentro de fazenda: portaria, taxa por pessoa e estrada de terra até lá. Leve dinheiro e considere guia local nos complexos maiores.' },
        rotuloPortas: 'Saindo de BH',
        portas: [
          { c: '≈4h30', n: 'Carrancas · BR-381 + BR-265', t: 'porta' },
          { c: '≈4h35', n: 'São Thomé das Letras · BR-381 + MG-167', t: 'porta' },
        ],
        cidades: [
          { n: 'Carrancas', tags: ['cachoeira', 'natureza'], d: 'Dezenas de quedas divididas em complexos: Zilda, Poço do Coração, Cachoeira da Fumaça, Véu da Noiva, Esmeralda. Dá pra encher três dias sem repetir. Pousada boa e pouca vida noturna — que é justamente a graça.' },
          { n: 'São Thomé das Letras', tags: ['montanha', 'vilarejo', 'gruta'], d: 'Cidade construída em quartzito no alto da serra, cercada de mirante e de fama mística. Pirâmide, Matriz, Vale das Borboletas, Cachoeira Véu da Noiva e grutas no entorno — várias em propriedade privada, com taxa.' },
        ],
      },
    ],
  },
  {
    id: 'mg-viagem-maior',
    nome: '5h+ — já é viagem, não escapada',
    emoji: '🏔️',
    resumo: 'Passou de 350 km, a conta muda: aqui vale emendar feriado ou dormir três noites. É a faixa da Mantiqueira e do Circuito das Águas, com o clima mais frio de Minas.',
    paises: [
      {
        slug: 'mg-aguas', nome: 'Circuito das Águas', bandeira: '💧',
        tags: ['aguas', 'cidade', 'gastronomia', 'historia'],
        resumo: 'Cidades de estação de águas do século XIX: parque com fontes minerais, balneário, coreto e hotel antigo. O programa é beber água na fonte, comer bem e não fazer nada — não é destino de trilha.',
        quando: 'O ano todo · o inverno é a temporada tradicional, com frio seco',
        estradaReal: 'Carimba em Caxambu e São Lourenço (Velho)',
        transporte: { modo: '🚗', rotulo: 'Carro (é longe)', texto: 'De BH são quase 400 km pela BR-381 e depois BR-267 — na prática, mais de 5h com parada. As duas cidades ficam a uns 25 km uma da outra, então dá pra usar uma como base.' },
        rotuloPortas: 'Saindo de BH',
        portas: [
          { c: '≈5h25', n: 'Caxambu · BR-381 + BR-267', t: 'porta' },
          { c: '≈5h40', n: 'São Lourenço', t: 'porta' },
        ],
        cidades: [
          { n: 'Caxambu', tags: ['aguas', 'historia'], d: 'Parque das Águas com uma das maiores concentrações de fontes minerais do circuito, arquitetura de balneário antigo e o Morro do Cristo por cima da cidade. Mais tranquila que São Lourenço.' },
          { n: 'São Lourenço', tags: ['aguas', 'gastronomia'], d: 'O Parque das Águas é maior e mais organizado, com fontes, lago e balneário. Centro com café, loja de doce e restaurante — o passeio de cidade mais confortável dessa faixa.' },
        ],
        aviso: 'Os teleféricos das duas cidades têm relatos recentes de má conservação, e o de Caxambu aparece como desativado em avaliações de 2026. O mesmo vale pro trem turístico da região: confirme com a prefeitura ou a operadora antes de contar com esses passeios.',
      },
      {
        slug: 'mg-pocos', nome: 'Poços de Caldas', bandeira: '♨️',
        tags: ['termas', 'aguas', 'cidade', 'gastronomia'],
        resumo: 'A cidade construída dentro de uma caldeira vulcânica extinta, com água sulfurosa quente saindo do chão. É a única da lista onde dá pra fazer termas de verdade — e a mais distante de BH.',
        quando: 'O ano todo · o inverno é a alta temporada tradicional das águas',
        transporte: { modo: '🚗', rotulo: 'Carro, e é longe', texto: 'Mais de 460 km de BH, quase 7h de estrada. Só compensa emendando feriado, ou como parada de um roteiro maior no sul de Minas. Dentro da cidade dá pra andar a pé no centro.' },
        rotuloPortas: 'Saindo de BH',
        portas: [{ c: '≈6h50', n: 'Poços de Caldas · via BR-381', t: 'porta' }],
        cidades: [
          { n: 'Thermas Antônio Carlos', tags: ['termas'], d: 'Balneário de 1931 em estilo neorromano, o primeiro estabelecimento termal moderno do país. Banho de imersão em água sulfurosa a cerca de 37 °C, sauna e massagem.' },
          { n: 'Cristo Redentor e teleférico', tags: ['montanha'], d: 'O Cristo fica no alto da Serra de São Domingos, a 1.686 m, com vista da caldeira inteira. O teleférico, de 1974, sobe 1.500 m do centro até lá.' },
          { n: 'Véu das Noivas', tags: ['cachoeira'], d: 'Cachoeira logo na saída da cidade, um dos cartões-postais antigos de Poços. Passeio curto, de mirante.' },
        ],
        aviso: 'O teleférico passou por manutenção em 2026, com previsão de reabrir antes do feriado de Corpus Christi. Confirme se está operando antes de contar com ele — subir de carro até o Cristo é possível, mas é outro passeio.',
      },
      {
        slug: 'mg-mantiqueira', nome: 'Mantiqueira mineira', bandeira: '🌲',
        tags: ['montanha', 'natureza', 'gastronomia', 'cachoeira'],
        resumo: 'A parte alta e fria de Minas, na divisa com São Paulo. Vila de montanha com fondue, turismo rural de estrada de terra e o vale mais bonito do sul do estado. Aqui o inverno é atração, não problema.',
        quando: 'Jun–ago pro frio (e geada eventual em Monte Verde) · abr–mai e set pras trilhas com tempo firme',
        estradaReal: 'Carimba em Aiuruoca (Velho) · Monte Verde e Gonçalves ficam fora da rota',
        transporte: { modo: '🚗', rotulo: 'Carro, e 4x4 ajuda', texto: 'Em Gonçalves e no Vale do Matutu (Aiuruoca), boa parte das pousadas e trilhas fica em estrada de terra de serra — carro baixo sofre, principalmente na chuva. Monte Verde tem asfalto até a vila.' },
        rotuloPortas: 'Saindo de BH',
        portas: [
          { c: '≈6h', n: 'Aiuruoca · BR-381 + BR-267', t: 'porta' },
          { c: '≈6h25', n: 'Gonçalves', t: 'porta' },
          { c: '≈6h50', n: 'Monte Verde (Camanducaia)', t: 'porta' },
        ],
        cidades: [
          { n: 'Monte Verde', tags: ['montanha', 'gastronomia'], d: 'Distrito de Camanducaia no alto da Mantiqueira, com cara de vila alpina: chalé, lareira, fondue, chocolate e loja. Trilhas curtas pra Pedra Redonda e Chapéu do Bispo. Lota em julho e feriado — reserve cedo.' },
          { n: 'Gonçalves', tags: ['montanha', 'natureza', 'cachoeira'], d: 'O oposto de Monte Verde: turismo rural, pousada isolada e trilha de verdade — Pico do Selado, Pedra Chanfrada, Pedra do Forno. Almoço de fogão a lenha em fazenda e estrada de terra até quase tudo.' },
          { n: 'Aiuruoca', tags: ['montanha', 'natureza', 'cachoeira'], d: 'A porta do Vale do Matutu, no pé do Pico do Papagaio. Cachoeira, poço e uma das trilhas mais bonitas de Minas — a do pico é de dia inteiro e pede guia.' },
        ],
      },
    ],
  },
];

const MG_PASSAPORTE = {
  titulo: '📕 Passaporte da Estrada Real',
  texto: [
    'Boa parte desta lista está em cima da Estrada Real, a rota de 1.630 km que ligava as minas ao litoral. O Instituto Estrada Real emite um passaporte de carimbos: você carimba nas cidades por onde passa e, batendo o mínimo de cada caminho, recebe um certificado. Não custa nada e não exige desviar do que você já ia fazer.',
    'Cada bloco abaixo mostra a qual caminho pertence, quando pertence. Só o Caminho dos Diamantes já cobre Ouro Preto, Mariana, Caraça, Cipó, Lapinha, Conceição do Mato Dentro, Serro, Milho Verde e Diamantina — ou seja, quase todo fim de semana que você já queria fazer.',
  ],
  itens: [
    { k: 'Grátis, em duas versões.', v: 'A virtual sai pelo app Estrada Real (Android e iOS). A física você retira num ponto oficial — Diamantina, Ouro Preto, Cocais, Glaura, Tiradentes, Paraty ou Petrópolis — mediante cadastro e doação de 1 kg de alimento não perecível.' },
    { k: 'Carimbos mínimos por caminho:', v: 'Diamantes 10 · Velho 14 · Novo 8 · Sabarabuçu 4. Vale um carimbo por município — confirme no app, que mostra os pontos por geolocalização. Fechando os quatro caminhos, sai o certificado especial.' },
    { k: 'Como fecha:', v: 'No app o certificado é liberado automaticamente ao completar os carimbos. Na versão física, você escaneia as páginas e manda por e-mail pro instituto validar.' },
    { k: 'O mais fácil de fechar:', v: 'O Sabarabuçu, que pede só 4 carimbos — e passa por Sabará, ali do lado de BH.' },
  ],
  listas: [
    {
      titulo: 'Caminho dos Diamantes — 10 carimbos',
      texto: 'Estes dez municípios da sua lista estão na rota oficial. São exatamente os dez que o caminho exige: fazendo os fins de semana que já estão aqui, você fecha o Diamantes sem um desvio sequer.',
      cidades: ['Diamantina', 'Serro', 'Conceição do Mato Dentro', 'Itambé do Mato Dentro', 'Santana do Riacho', 'Itabira (Ipoema)', 'Santa Bárbara', 'Catas Altas', 'Mariana', 'Ouro Preto'],
    },
    {
      titulo: 'Caminho Velho — 14 carimbos',
      texto: 'Dez dos seus destinos estão nele (Ouro Preto conta de novo, por outro caminho). Faltam quatro.',
      cidades: ['Ouro Preto', 'Santo Antônio do Leite', 'Congonhas', 'Prados (Bichinho)', 'Tiradentes', 'São João del-Rei', 'Carrancas', 'São Thomé das Letras', 'Caxambu', 'São Lourenço', 'Aiuruoca'],
      faltam: {
        texto: 'Pra fechar os 14, estes ficam no meio do caminho que você já vai fazer — a maioria entre Congonhas e Tiradentes:',
        cidades: ['Entre Rios de Minas', 'Lagoa Dourada', 'Resende Costa', 'Ritápolis', 'Coronel Xavier Chaves', 'Dores de Campos', 'Barroso', 'Baependi', 'Cruzília', 'Cambuquira', 'Lambari'],
      },
    },
  ],
  fonte: { href: 'https://institutoestradareal.com.br/passaporte/', rotulo: 'Regras e cadastro no site do Instituto Estrada Real →' },
};

const MG_FORA = {
  titulo: '🇧🇷 Perto de BH e ainda fora da lista',
  paises: [
    { bandeira: '🍬', nome: 'Sabará' },
  ],
  texto: 'Meia hora de BH, barroco setecentista e doce de jabuticaba — cabe numa manhã de domingo. Ficou de sugestão em vez de virar bloco porque é curta demais pra sustentar um fim de semana; é só pedir que ela sobe pra lista.',
};

window.DESTINOS = window.DESTINOS || { continentes: [], fotos: {}, tags: {} };
window.DESTINOS.continentes.push({
  id: 'brasil',
  nome: 'Minas Gerais',
  emoji: '🇧🇷',
  resumo: 'As escapadas de carro saindo de BH, agrupadas por quanto tempo de estrada cada uma custa. Aqui milha não entra na conta — o que decide é quantas horas você aguenta dirigir.',
  regioes: MG_REGIOES,
  destaque: MG_PASSAPORTE,
  fora: MG_FORA,
});
Object.assign(window.DESTINOS.tags, BRASIL_TAGS);
