const EUROPA_FOTOS = {
"Aarhus": "assets/europa/aarhus.jpg",
"Abisko": "assets/europa/abisko.jpg",
"Albanian Riviera": "assets/europa/albanian-riviera.jpg",
"Algarve": "assets/europa/algarve.jpg",
"Alsace": "assets/europa/alsace.jpg",
"Amalfi Coast": "assets/europa/amalfi-coast.jpg",
"Amsterdam": "assets/europa/amsterdam.jpg",
"Andorra": "assets/europa/andorra.jpg",
"Andorra la Vella": "assets/europa/andorra-la-vella.jpg",
"Antalya": "assets/europa/antalya.jpg",
"Antwerp": "assets/europa/antwerp.jpg",
"Armenia": "assets/europa/armenia.jpg",
"Athens": "assets/europa/athens.jpg",
"Austria": "assets/europa/austria.jpg",
"Azerbaijan": "assets/europa/azerbaijan.jpg",
"Bad Gastein": "assets/europa/bad-gastein.jpg",
"Baden-Baden": "assets/europa/baden-baden.jpg",
"Baile Herculane": "assets/europa/baile-herculane.jpg",
"Baku": "assets/europa/baku.jpg",
"Balzers": "assets/europa/balzers.jpg",
"Bansko": "assets/europa/bansko.jpg",
"Barcelona": "assets/europa/barcelona.jpg",
"Bath": "assets/europa/bath.jpg",
"Batumi": "assets/europa/batumi.jpg",
"Belgium": "assets/europa/belgium.jpg",
"Belgrade": "assets/europa/belgrade.jpg",
"Berat": "assets/europa/berat.jpg",
"Bergen": "assets/europa/bergen.jpg",
"Berlin": "assets/europa/berlin.jpg",
"Bilbao": "assets/europa/bilbao.jpg",
"Bitola": "assets/europa/bitola.jpg",
"Black Forest": "assets/europa/black-forest.jpg",
"Blagaj": "assets/europa/blagaj.jpg",
"Bled": "assets/europa/bled.jpg",
"Bohinj": "assets/europa/bohinj.jpg",
"Bologna": "assets/europa/bologna.jpg",
"Bordeaux": "assets/europa/bordeaux.jpg",
"Borjomi": "assets/europa/borjomi.jpg",
"Brasov": "assets/europa/brasov.jpg",
"Bratislava": "assets/europa/bratislava.jpg",
"Bruges": "assets/europa/bruges.jpg",
"Brussels": "assets/europa/brussels.jpg",
"Bucharest": "assets/europa/bucharest.jpg",
"Budapest": "assets/europa/budapest.jpg",
"Budva": "assets/europa/budva.jpg",
"Bursa": "assets/europa/bursa.jpg",
"Cappadocia": "assets/europa/cappadocia.jpg",
"Catez ob Savi": "assets/europa/catez-ob-savi.jpg",
"Causeway Coast": "assets/europa/causeway-coast.jpg",
"Cesky Krumlov": "assets/europa/cesky-krumlov.jpg",
"Chamonix": "assets/europa/chamonix.jpg",
"Chisinau": "assets/europa/chisinau.jpg",
"Cinque Terre": "assets/europa/cinque-terre.jpg",
"Cliffs of Moher": "assets/europa/cliffs-of-moher.jpg",
"Cologne": "assets/europa/cologne.jpg",
"Comino": "assets/europa/comino.jpg",
"Copenhagen": "assets/europa/copenhagen.jpg",
"Cordoba": "assets/europa/cordoba.jpg",
"Corfu": "assets/europa/corfu.jpg",
"Cornwall": "assets/europa/cornwall.jpg",
"Corsica": "assets/europa/corsica.jpg",
"Crete": "assets/europa/crete.jpg",
"Cricova": "assets/europa/cricova.jpg",
"Curonian Spit": "assets/europa/curonian-spit.jpg",
"Czech Republic": "assets/europa/czech-republic.jpg",
"Danube Delta": "assets/europa/danube-delta.jpg",
"Decani": "assets/europa/decani.jpg",
"Denmark": "assets/europa/denmark.jpg",
"Dilijan": "assets/europa/dilijan.jpg",
"Dingle Peninsula": "assets/europa/dingle-peninsula.jpg",
"Djavolja Varos": "assets/europa/djavolja-varos.jpg",
"Dolomites": "assets/europa/dolomites.jpg",
"Douro Valley": "assets/europa/douro-valley.jpg",
"Dresden": "assets/europa/dresden.jpg",
"Dublin": "assets/europa/dublin.jpg",
"Dubrovnik": "assets/europa/dubrovnik.jpg",
"Durmitor National Park": "assets/europa/durmitor-national-park.jpg",
"Edinburgh": "assets/europa/edinburgh.jpg",
"Eger": "assets/europa/eger.jpg",
"Egerszalok": "assets/europa/egerszalok.jpg",
"Ephesus": "assets/europa/ephesus.jpg",
"Escaldes-Engordany": "assets/europa/escaldes-engordany.jpg",
"Evora": "assets/europa/evora.jpg",
"Fethiye": "assets/europa/fethiye.jpg",
"Flam": "assets/europa/flam.jpg",
"Florence": "assets/europa/florence.jpg",
"Fussen": "assets/europa/fussen.jpg",
"Gabala": "assets/europa/gabala.jpg",
"Galway": "assets/europa/galway.jpg",
"Gdansk": "assets/europa/gdansk.jpg",
"Geghard": "assets/europa/geghard.jpg",
"Geiranger": "assets/europa/geiranger.jpg",
"Geneva": "assets/europa/geneva.jpg",
"Georgia (country)": "assets/europa/georgia-country.jpg",
"Ghent": "assets/europa/ghent.jpg",
"Giethoorn": "assets/europa/giethoorn.jpg",
"Gjirokaster": "assets/europa/gjirokaster.jpg",
"Gobustan": "assets/europa/gobustan.jpg",
"Gothenburg": "assets/europa/gothenburg.jpg",
"Gotland": "assets/europa/gotland.jpg",
"Gozo": "assets/europa/gozo.jpg",
"Granada": "assets/europa/granada.jpg",
"Grandvalira": "assets/europa/grandvalira.jpg",
"Hallstatt": "assets/europa/hallstatt.jpg",
"Hamburg": "assets/europa/hamburg.jpg",
"Helsinki": "assets/europa/helsinki.jpg",
"Heviz": "assets/europa/heviz.jpg",
"High Tatras": "assets/europa/high-tatras.jpg",
"Hill of Crosses": "assets/europa/hill-of-crosses.jpg",
"Hungary": "assets/europa/hungary.jpg",
"Hvar": "assets/europa/hvar.jpg",
"Ibiza": "assets/europa/ibiza.jpg",
"Inari": "assets/europa/inari.jpg",
"Innsbruck": "assets/europa/innsbruck.jpg",
"Interlaken": "assets/europa/interlaken.jpg",
"Ireland": "assets/europa/ireland.jpg",
"Ischia": "assets/europa/ischia.jpg",
"Isle of Skye": "assets/europa/isle-of-skye.jpg",
"Istanbul": "assets/europa/istanbul.jpg",
"Istria": "assets/europa/istria.jpg",
"Jurmala": "assets/europa/jurmala.jpg",
"Karlovy Vary": "assets/europa/karlovy-vary.jpg",
"Kaunas": "assets/europa/kaunas.jpg",
"Khor Virap": "assets/europa/khor-virap.jpg",
"Kiruna": "assets/europa/kiruna.jpg",
"Koman": "assets/europa/koman.jpg",
"Kosice": "assets/europa/kosice.jpg",
"Kotor": "assets/europa/kotor.jpg",
"Krakow": "assets/europa/krakow.jpg",
"Kravice": "assets/europa/kravice.jpg",
"Ksamil": "assets/europa/ksamil.jpg",
"Kuldiga": "assets/europa/kuldiga.jpg",
"Kutna Hora": "assets/europa/kutna-hora.jpg",
"Lahemaa National Park": "assets/europa/lahemaa-national-park.jpg",
"Lake Balaton": "assets/europa/lake-balaton.jpg",
"Lake Como": "assets/europa/lake-como.jpg",
"Lake District": "assets/europa/lake-district.jpg",
"Lake Sevan": "assets/europa/lake-sevan.jpg",
"Lake Skadar": "assets/europa/lake-skadar.jpg",
"Lauterbrunnen": "assets/europa/lauterbrunnen.jpg",
"Leukerbad": "assets/europa/leukerbad.jpg",
"Levi": "assets/europa/levi.jpg",
"Lisbon": "assets/europa/lisbon.jpg",
"Lisse": "assets/europa/lisse.jpg",
"Ljubljana": "assets/europa/ljubljana.jpg",
"Lofoten": "assets/europa/lofoten.jpg",
"Loire Valley": "assets/europa/loire-valley.jpg",
"London": "assets/europa/london.jpg",
"Lovcen National Park": "assets/europa/lovcen-national-park.jpg",
"Lucerne": "assets/europa/lucerne.jpg",
"Lugano": "assets/europa/lugano.jpg",
"Luxembourg City": "assets/europa/luxembourg-city.jpg",
"Lyon": "assets/europa/lyon.jpg",
"Madeira": "assets/europa/madeira.jpg",
"Madrid": "assets/europa/madrid.jpg",
"Malbun": "assets/europa/malbun.jpg",
"Mallorca": "assets/europa/mallorca.jpg",
"Malmo": "assets/europa/malmo.jpg",
"Malta": "assets/europa/malta.jpg",
"Maramures": "assets/europa/maramures.jpg",
"Matka Canyon": "assets/europa/matka-canyon.jpg",
"Mavrovo": "assets/europa/mavrovo.jpg",
"Mdina": "assets/europa/mdina.jpg",
"Menorca": "assets/europa/menorca.jpg",
"Meteora": "assets/europa/meteora.jpg",
"Milestii Mici": "assets/europa/milestii-mici.jpg",
"Moldova": "assets/europa/moldova.jpg",
"Mon": "assets/europa/mon.jpg",
"Monaco": "assets/europa/monaco.jpg",
"Mondorf-les-Bains": "assets/europa/mondorf-les-bains.jpg",
"Moselle (Luxembourg)": "assets/europa/moselle-luxembourg.jpg",
"Mostar": "assets/europa/mostar.jpg",
"Mount Nemrut": "assets/europa/mount-nemrut.jpg",
"Mullerthal": "assets/europa/mullerthal.jpg",
"Munich": "assets/europa/munich.jpg",
"Myvatn": "assets/europa/myvatn.jpg",
"Nafplio": "assets/europa/nafplio.jpg",
"Naples": "assets/europa/naples.jpg",
"Naxos": "assets/europa/naxos.jpg",
"Nazare": "assets/europa/nazare.jpg",
"Nesebar": "assets/europa/nesebar.jpg",
"Netherlands": "assets/europa/netherlands.jpg",
"Nice": "assets/europa/nice.jpg",
"Normandy": "assets/europa/normandy.jpg",
"North Zealand": "assets/europa/north-zealand.jpg",
"Novi Sad": "assets/europa/novi-sad.jpg",
"Odense": "assets/europa/odense.jpg",
"Ohrid": "assets/europa/ohrid.jpg",
"Ordino": "assets/europa/ordino.jpg",
"Orheiul Vechi": "assets/europa/orheiul-vechi.jpg",
"Oslo": "assets/europa/oslo.jpg",
"Otztal": "assets/europa/otztal.jpg",
"Ourense": "assets/europa/ourense.jpg",
"Pamukkale": "assets/europa/pamukkale.jpg",
"Paris": "assets/europa/paris.jpg",
"Parnu": "assets/europa/parnu.jpg",
"Peja": "assets/europa/peja.jpg",
"Perast": "assets/europa/perast.jpg",
"Permet": "assets/europa/permet.jpg",
"Piestany": "assets/europa/piestany.jpg",
"Piran": "assets/europa/piran.jpg",
"Plitvice Lakes National Park": "assets/europa/plitvice-lakes-national-park.jpg",
"Plovdiv": "assets/europa/plovdiv.jpg",
"Poland": "assets/europa/poland.jpg",
"Poprad": "assets/europa/poprad.jpg",
"Porto": "assets/europa/porto.jpg",
"Postojna": "assets/europa/postojna.jpg",
"Prague": "assets/europa/prague.jpg",
"Pristina": "assets/europa/pristina.jpg",
"Prizren": "assets/europa/prizren.jpg",
"Provence": "assets/europa/provence.jpg",
"Reykjavik": "assets/europa/reykjavik.jpg",
"Rhine Valley": "assets/europa/rhine-valley.jpg",
"Rhodes": "assets/europa/rhodes.jpg",
"Riga": "assets/europa/riga.jpg",
"Rila Monastery": "assets/europa/rila-monastery.jpg",
"Ring of Kerry": "assets/europa/ring-of-kerry.jpg",
"Rome": "assets/europa/rome.jpg",
"Rotterdam": "assets/europa/rotterdam.jpg",
"Rovaniemi": "assets/europa/rovaniemi.jpg",
"Saaremaa": "assets/europa/saaremaa.jpg",
"Safranbolu": "assets/europa/safranbolu.jpg",
"Salzburg": "assets/europa/salzburg.jpg",
"San Marino": "assets/europa/san-marino.jpg",
"San Sebastian": "assets/europa/san-sebastian.jpg",
"Santiago de Compostela": "assets/europa/santiago-de-compostela.jpg",
"Santorini": "assets/europa/santorini.jpg",
"Sao Miguel": "assets/europa/sao-miguel.jpg",
"Sarajevo": "assets/europa/sarajevo.jpg",
"Sardinia": "assets/europa/sardinia.jpg",
"Saturnia": "assets/europa/saturnia.jpg",
"Savonlinna": "assets/europa/savonlinna.jpg",
"Seville": "assets/europa/seville.jpg",
"Sheki": "assets/europa/sheki.jpg",
"Sibiu": "assets/europa/sibiu.jpg",
"Sicily": "assets/europa/sicily.jpg",
"Sighisoara": "assets/europa/sighisoara.jpg",
"Sighnaghi": "assets/europa/sighnaghi.jpg",
"Sigulda": "assets/europa/sigulda.jpg",
"Sintra": "assets/europa/sintra.jpg",
"Skagen": "assets/europa/skagen.jpg",
"Skopje": "assets/europa/skopje.jpg",
"Sliema": "assets/europa/sliema.jpg",
"Slovenia": "assets/europa/slovenia.jpg",
"Snaefellsnes": "assets/europa/snaefellsnes.jpg",
"Snowdonia": "assets/europa/snowdonia.jpg",
"Soca Valley": "assets/europa/soca-valley.jpg",
"Sofia": "assets/europa/sofia.jpg",
"South Iceland": "assets/europa/south-iceland.jpg",
"South Moravia": "assets/europa/south-moravia.jpg",
"Spa": "assets/europa/spa.jpg",
"Spain": "assets/europa/spain.jpg",
"Spissky hrad": "assets/europa/spissky-hrad.jpg",
"Split": "assets/europa/split.jpg",
"St. Moritz": "assets/europa/st-moritz.jpg",
"Stavanger": "assets/europa/stavanger.jpg",
"Stepantsminda": "assets/europa/stepantsminda.jpg",
"Stockholm": "assets/europa/stockholm.jpg",
"Sutjeska National Park": "assets/europa/sutjeska-national-park.jpg",
"Svaneti": "assets/europa/svaneti.jpg",
"Sveti Stefan": "assets/europa/sveti-stefan.jpg",
"Tallinn": "assets/europa/tallinn.jpg",
"Tara National Park": "assets/europa/tara-national-park.jpg",
"Tartu": "assets/europa/tartu.jpg",
"Tatev": "assets/europa/tatev.jpg",
"Tbilisi": "assets/europa/tbilisi.jpg",
"Tenerife": "assets/europa/tenerife.jpg",
"The Hague": "assets/europa/the-hague.jpg",
"Thessaloniki": "assets/europa/thessaloniki.jpg",
"Theth": "assets/europa/theth.jpg",
"Tirana": "assets/europa/tirana.jpg",
"Tokaj": "assets/europa/tokaj.jpg",
"Trakai": "assets/europa/trakai.jpg",
"Transfagarasan": "assets/europa/transfagarasan.jpg",
"Trebinje": "assets/europa/trebinje.jpg",
"Tromso": "assets/europa/tromso.jpg",
"Turkey": "assets/europa/turkey.jpg",
"Turku": "assets/europa/turku.jpg",
"Tuscany": "assets/europa/tuscany.jpg",
"United Kingdom": "assets/europa/united-kingdom.jpg",
"Utrecht": "assets/europa/utrecht.jpg",
"Vaduz": "assets/europa/vaduz.jpg",
"Valencia": "assets/europa/valencia.jpg",
"Valletta": "assets/europa/valletta.jpg",
"Vardzia": "assets/europa/vardzia.jpg",
"Vatican City": "assets/europa/vatican-city.jpg",
"Vatnajokull National Park": "assets/europa/vatnajokull-national-park.jpg",
"Veliko Tarnovo": "assets/europa/veliko-tarnovo.jpg",
"Venice": "assets/europa/venice.jpg",
"Vianden": "assets/europa/vianden.jpg",
"Vienna": "assets/europa/vienna.jpg",
"Vilnius": "assets/europa/vilnius.jpg",
"Vrnjacka Banja": "assets/europa/vrnjacka-banja.jpg",
"Wachau": "assets/europa/wachau.jpg",
"Warsaw": "assets/europa/warsaw.jpg",
"Westfjords": "assets/europa/westfjords.jpg",
"Wild Atlantic Way": "assets/europa/wild-atlantic-way.jpg",
"Wroclaw": "assets/europa/wroclaw.jpg",
"Yanar Dag": "assets/europa/yanar-dag.jpg",
"Yerevan": "assets/europa/yerevan.jpg",
"York": "assets/europa/york.jpg",
"Zadar": "assets/europa/zadar.jpg",
"Zagreb": "assets/europa/zagreb.jpg",
"Zakopane": "assets/europa/zakopane.jpg",
"Zermatt": "assets/europa/zermatt.jpg",
"Zurich": "assets/europa/zurich.jpg"
};
