const EUROPA_TAGS = {
  cidade:      { e: '🌆', l: 'Cidade' },
  historia:    { e: '🏛️', l: 'História & arte' },
  montanha:    { e: '🏔️', l: 'Montanha' },
  praia:       { e: '🏖️', l: 'Praia de banho' },
  costa:       { e: '🌊', l: 'Costa de contemplar' },
  natureza:    { e: '🌲', l: 'Natureza' },
  aurora:      { e: '🌌', l: 'Aurora' },
  termas:      { e: '♨️', l: 'Termas' },
  gastronomia: { e: '🍷', l: 'Gastronomia & vinho' },
  neve:        { e: '🎿', l: 'Neve & ski' },
  roadtrip:    { e: '🚗', l: 'Road trip' },
};

const EUROPA_REGIOES = [
  {
    id: 'nordicos',
    nome: 'Nórdicos & Ártico',
    emoji: '🌌',
    resumo: 'Aurora, fiorde, floresta e design. É a experiência mais difícil de repetir em qualquer outro canto da Europa — e a mais cara. Encaixa bem como o "bloco diferente" de um roteiro que já tem cidade e história.',
    paises: [
      {
        slug: 'islandia', nome: 'Islândia', bandeira: '🇮🇸', wv: 'Iceland',
        tags: ['natureza', 'termas', 'aurora', 'roadtrip'],
        resumo: 'Natureza extrema numa ilha que se dá a volta de carro. Vulcão, geleira, cachoeira e piscina termal no mesmo dia. Não tem cidade grande nem história monumental — é 100% paisagem.',
        quando: 'Jun–ago pra sol da meia-noite e estradas abertas · set–mar pra aurora',
        portas: [ { c: 'KEF', n: 'Keflavík', t: 'porta' }, { c: 'AEY', n: 'Akureyri (norte)', t: 'regional' } ],
        termas: 'Sim, e das melhores do mundo. Blue Lagoon e Sky Lagoon são as famosas (caras, precisam de reserva); Mývatn Nature Baths no norte é mais tranquila; Secret Lagoon em Flúðir é a mais rústica; e Reykjadalur é um rio quente de graça, depois de uma trilha de ~1h. Atenção: as erupções na península de Reykjanes já causaram fechamentos temporários na Blue Lagoon — confirme antes de contar com ela.',
        cidades: [
          { n: 'Reykjavík', wv: 'Reykjavik', tags: ['cidade', 'gastronomia'], d: 'Capital compacta, dá pra andar a pé. Base pra tudo, boa cena de restaurante e a Sky Lagoon logo ali.' },
          { n: 'Costa Sul', wv: 'South Iceland', tags: ['natureza', 'roadtrip'], d: 'A faixa mais fotografada do país: Seljalandsfoss, Skógafoss e a praia de areia preta de Reynisfjara.' },
          { n: 'Jökulsárlón', wv: 'Vatnajokull National Park', tags: ['natureza'], d: 'Lagoa glacial com icebergs à deriva e a Diamond Beach do outro lado da estrada.' },
          { n: 'Snæfellsnes', wv: 'Snaefellsnes', tags: ['natureza', 'roadtrip'], d: 'Península apelidada de "Islândia em miniatura" — vulcão, costa, cavalos e o Kirkjufell.' },
          { n: 'Mývatn', wv: 'Myvatn', tags: ['natureza', 'termas'], d: 'Zona vulcânica ativa no norte: crateras, fumarolas e as Nature Baths sem a multidão do sul.' },
          { n: 'Westfjords', wv: 'Westfjords', tags: ['natureza', 'roadtrip'], d: 'A região mais isolada e menos visitada. Dynjandi, papagaios-do-mar e estradas de terra.' },
        ],
      },
      {
        slug: 'noruega', nome: 'Noruega', bandeira: '🇳🇴', wv: 'Norway',
        tags: ['natureza', 'montanha', 'aurora', 'costa'],
        resumo: 'Fiorde é o produto principal, e não existe substituto. Some o Ártico (aurora, baleias, huskies) e você tem dois países dentro de um — o sul verde e o norte polar.',
        quando: 'Jun–set pros fiordes e trilhas · out–mar pra aurora em Tromsø',
        portas: [ { c: 'OSL', n: 'Oslo', t: 'porta' }, { c: 'BGO', n: 'Bergen', t: 'regional' }, { c: 'TOS', n: 'Tromsø', t: 'regional' }, { c: 'EVE', n: 'Harstad/Narvik (Lofoten)', t: 'regional' } ],
        termas: null,
        cidades: [
          { n: 'Oslo', wv: 'Oslo', tags: ['cidade', 'historia'], d: 'Museu Munch, navios viking, ópera que dá pra subir no telhado. Cidade de 2 dias, não de 5.' },
          { n: 'Bergen', wv: 'Bergen', tags: ['cidade', 'natureza'], d: 'Casario de madeira de Bryggen (UNESCO) e a porta de entrada natural dos fiordes.' },
          { n: 'Tromsø', wv: 'Tromso', tags: ['aurora', 'natureza'], d: 'Acima do Círculo Polar. Aurora, baleias no inverno, trenó de huskies e cultura sámi.' },
          { n: 'Lofoten', wv: 'Lofoten', tags: ['natureza', 'costa', 'roadtrip'], d: 'Picos saindo direto do mar e vilas de pescadores. Provavelmente a paisagem mais forte da Europa.' },
          { n: 'Geirangerfjord', wv: 'Geiranger', tags: ['natureza'], d: 'O fiorde-cartão-postal, com as cascatas das Sete Irmãs e a estrada Trollstigen ao lado.' },
          { n: 'Stavanger', wv: 'Stavanger', tags: ['natureza', 'montanha'], d: 'Base do Preikestolen (Pulpit Rock) e do Kjeragbolten. Trilha de meio dia, vista de tirar o fôlego.' },
          { n: 'Flåm', wv: 'Flam', tags: ['natureza', 'roadtrip'], d: 'Um dos trens panorâmicos mais bonitos do mundo, ligando montanha e fiorde em 20 km.' },
        ],
      },
      {
        slug: 'suecia', nome: 'Suécia', bandeira: '🇸🇪', wv: 'Sweden',
        tags: ['cidade', 'natureza', 'aurora'],
        resumo: 'A mistura mais equilibrada do norte: uma capital de primeira linha, arquipélagos e um extremo ártico com aurora. Mais barata que a Noruega, com natureza menos dramática.',
        quando: 'Jun–ago pro arquipélago e Gotland · dez–mar pra aurora em Abisko',
        portas: [ { c: 'ARN', n: 'Estocolmo Arlanda', t: 'porta' }, { c: 'GOT', n: 'Gotemburgo', t: 'regional' }, { c: 'KRN', n: 'Kiruna', t: 'regional' } ],
        termas: null,
        cidades: [
          { n: 'Estocolmo', wv: 'Stockholm', tags: ['cidade', 'historia'], d: 'Espalhada por 14 ilhas. Gamla Stan medieval, o navio Vasa inteiro dentro de um museu e um arquipélago de milhares de ilhas na porta.' },
          { n: 'Gotemburgo', wv: 'Gothenburg', tags: ['cidade', 'gastronomia', 'costa'], d: 'Cidade portuária mais descontraída, forte em frutos do mar e com arquipélago próprio.' },
          { n: 'Abisko', wv: 'Abisko', tags: ['aurora', 'natureza'], d: 'Considerado um dos melhores pontos do planeta pra ver aurora — o "buraco azul" deixa o céu limpo com mais frequência.' },
          { n: 'Kiruna & Jukkasjärvi', wv: 'Kiruna', tags: ['neve', 'aurora'], d: 'Ártico sueco, mina de ferro e o Icehotel, reconstruído em gelo todo inverno.' },
          { n: 'Gotland & Visby', wv: 'Gotland', tags: ['praia', 'costa', 'historia'], d: 'Ilha no Báltico com cidade murada medieval (UNESCO) e praias — destino de verão dos suecos.' },
          { n: 'Malmö', wv: 'Malmo', tags: ['cidade'], d: 'A 35 min de trem de Copenhague pela ponte de Øresund. Emenda óbvia com a Dinamarca.' },
        ],
      },
      {
        slug: 'finlandia', nome: 'Finlândia', bandeira: '🇫🇮', wv: 'Finland',
        tags: ['natureza', 'aurora', 'neve', 'cidade'],
        resumo: 'Floresta, lago e sauna. A Lapônia finlandesa é a versão mais "produto pronto" do Ártico — igloo de vidro, renas, Papai Noel — o que é ótimo se você quer inverno sem improviso.',
        quando: 'Dez–mar pra Lapônia e aurora · jun–ago pros lagos e sol da meia-noite',
        portas: [ { c: 'HEL', n: 'Helsinque', t: 'porta' }, { c: 'RVN', n: 'Rovaniemi', t: 'regional' }, { c: 'KTT', n: 'Kittilä (Levi)', t: 'regional' }, { c: 'IVL', n: 'Ivalo (Inari)', t: 'regional' } ],
        termas: 'Não no sentido de fonte termal. O que existe é a cultura de sauna, que é levada muito a sério — Löyly e Allas em Helsinque são as públicas mais bonitas. É outra experiência: calor seco e mergulho gelado, não piscina quente ao ar livre.',
        cidades: [
          { n: 'Helsinque', wv: 'Helsinki', tags: ['cidade', 'gastronomia'], d: 'Design, arquitetura e mercados. A Rock Church e a fortaleza-ilha de Suomenlinna valem o dia.' },
          { n: 'Rovaniemi', wv: 'Rovaniemi', tags: ['neve', 'aurora'], d: 'Capital oficial da Lapônia, em cima do Círculo Polar. Santa Claus Village e toda a infra de inverno.' },
          { n: 'Levi & Ylläs', wv: 'Levi', tags: ['neve', 'natureza'], d: 'As maiores estações de esqui do país, com temporada longa e muita motoneve.' },
          { n: 'Inari & Saariselkä', wv: 'Inari', tags: ['aurora', 'natureza'], d: 'Lapônia mais ao norte e menos turística, centro da cultura sámi. Céu excelente pra aurora.' },
          { n: 'Lakeland & Savonlinna', wv: 'Savonlinna', tags: ['natureza'], d: 'Milhares de lagos, cabanas de madeira e o castelo de Olavinlinna sobre a água.' },
          { n: 'Turku', wv: 'Turku', tags: ['historia', 'costa'], d: 'Antiga capital, com castelo medieval e o maior arquipélago do mundo em número de ilhas.' },
        ],
      },
      {
        slug: 'dinamarca', nome: 'Dinamarca', bandeira: '🇩🇰', wv: 'Denmark',
        tags: ['cidade', 'gastronomia', 'historia'],
        resumo: 'É o nórdico "de cidade": design, gastronomia e bicicleta, sem depender de natureza extrema. Copenhague sozinha justifica a parada, e o país é pequeno o suficiente pra caber em 4–5 dias.',
        quando: 'Mai–set (verão curto e agradável) · dez pros mercados de Natal',
        portas: [ { c: 'CPH', n: 'Copenhague', t: 'porta' }, { c: 'BLL', n: 'Billund', t: 'regional' } ],
        termas: null,
        cidades: [
          { n: 'Copenhague', wv: 'Copenhagen', tags: ['cidade', 'gastronomia'], d: 'Nyhavn, ciclovias por toda parte e o epicentro da nova cozinha nórdica. Uma das melhores capitais da Europa pra simplesmente andar.' },
          { n: 'Aarhus', wv: 'Aarhus', tags: ['cidade', 'historia'], d: 'Segunda cidade, universitária, com o museu ARoS e seu arco-íris panorâmico no telhado.' },
          { n: 'Odense', wv: 'Odense', tags: ['historia'], d: 'Cidade natal de Hans Christian Andersen, com museu novo dedicado a ele.' },
          { n: 'Norte da Zelândia', wv: 'North Zealand', tags: ['historia', 'natureza'], d: 'Bate-volta de Copenhague: castelo de Kronborg (o Hamlet) e Frederiksborg, mais o museu Louisiana.' },
          { n: 'Skagen', wv: 'Skagen', tags: ['costa', 'natureza'], d: 'Ponta norte do país, onde dois mares se encontram visivelmente. Luz que virou escola de pintura.' },
          { n: 'Møns Klint', wv: 'Mon', tags: ['natureza'], d: 'Falésias brancas de calcário de 100 m sobre o Báltico — a paisagem menos "dinamarquesa" da Dinamarca.' },
        ],
      },
    ],
  },
  {
    id: 'britanicas',
    nome: 'Ilhas Britânicas',
    emoji: '🏰',
    resumo: 'Duas experiências que se completam: cidade densa de museu e história de um lado, road trip de costa e montanha do outro. E é onde a barreira do idioma some.',
    paises: [
      {
        slug: 'reino-unido', nome: 'Reino Unido', bandeira: '🇬🇧', wv: 'United Kingdom',
        tags: ['cidade', 'historia', 'montanha', 'roadtrip'],
        resumo: 'Londres é um destino inteiro sozinha. Fora dela o país entrega coisa bem diferente: Highlands de road trip, lagos, cidades medievais e a única cidade termal natural das ilhas.',
        quando: 'Mai–set pro norte e Escócia · Londres o ano todo',
        portas: [ { c: 'LHR', n: 'Londres Heathrow', t: 'porta' }, { c: 'LGW', n: 'Londres Gatwick', t: 'porta' }, { c: 'EDI', n: 'Edimburgo', t: 'regional' }, { c: 'MAN', n: 'Manchester', t: 'regional' } ],
        termas: 'Só uma, mas é boa: Bath. É a única fonte termal natural do país — os romanos construíram um complexo em cima dela, que hoje é museu (não se banha), e o Thermae Bath Spa ao lado usa a mesma água, com piscina no rooftop olhando a cidade.',
        cidades: [
          { n: 'Londres', wv: 'London', tags: ['cidade', 'historia', 'gastronomia'], d: 'Museus de nível mundial e a maioria de graça (British Museum, Tate, National Gallery). Teatro, mercados e uma cena de restaurante que virou das melhores da Europa.' },
          { n: 'Edimburgo', wv: 'Edinburgh', tags: ['cidade', 'historia'], d: 'Castelo em cima de um vulcão extinto e uma Old Town de becos. Em agosto o Fringe toma a cidade inteira (e os preços).' },
          { n: 'Highlands & Isle of Skye', wv: 'Isle of Skye', tags: ['montanha', 'roadtrip', 'natureza'], d: 'A road trip clássica do país: Glencoe, lagos, castelos e as formações rochosas de Skye.' },
          { n: 'Lake District', wv: 'Lake District', tags: ['natureza', 'montanha'], d: 'Lagos, montanhas suaves e vilarejos de pedra. Caminhada acessível, sem alpinismo.' },
          { n: 'Bath', wv: 'Bath', tags: ['historia', 'termas'], d: 'Cidade georgiana inteira em pedra dourada, com termas romanas no centro. UNESCO duas vezes.' },
          { n: 'York', wv: 'York', tags: ['historia'], d: 'Muralhas romanas e medievais que dá pra percorrer a pé, catedral gótica enorme e ruelas como The Shambles.' },
          { n: 'Cornualha', wv: 'Cornwall', tags: ['praia', 'costa', 'roadtrip'], d: 'Costa de falésias, vilas de pescadores e as praias mais bonitas da Inglaterra.' },
          { n: 'Snowdonia (País de Gales)', wv: 'Snowdonia', tags: ['montanha', 'natureza'], d: 'Montanha de verdade, castelos de Eduardo I na costa e trens a vapor.' },
          { n: 'Costa do Giant\'s Causeway', wv: 'Causeway Coast', tags: ['natureza', 'roadtrip'], d: 'Na Irlanda do Norte: colunas de basalto hexagonais e uma estrada costeira excelente, saindo de Belfast.' },
        ],
      },
      {
        slug: 'irlanda', nome: 'Irlanda', bandeira: '🇮🇪', wv: 'Ireland',
        tags: ['roadtrip', 'costa', 'natureza'],
        resumo: 'País de carro alugado. A graça está na costa oeste — falésia, península, vila de pescador e pub — não nas cidades. Se você não pretende dirigir, rende bem menos.',
        quando: 'Mai–set (fora disso, dia curto e chuva constante)',
        portas: [ { c: 'DUB', n: 'Dublin', t: 'porta' }, { c: 'SNN', n: 'Shannon (oeste)', t: 'regional' }, { c: 'ORK', n: 'Cork', t: 'regional' } ],
        termas: null,
        cidades: [
          { n: 'Dublin', wv: 'Dublin', tags: ['cidade', 'historia'], d: 'Trinity College e o Book of Kells, Guinness Storehouse, e a maior densidade de pub da Europa.' },
          { n: 'Galway', wv: 'Galway', tags: ['cidade', 'gastronomia'], d: 'Cidade pequena, colorida e musical. A porta natural pro oeste e pra Connemara.' },
          { n: 'Cliffs of Moher', wv: 'Cliffs of Moher', tags: ['natureza'], d: 'Falésias de 200 m sobre o Atlântico, com o platô calcário do Burren logo atrás.' },
          { n: 'Ring of Kerry', wv: 'Ring of Kerry', tags: ['roadtrip', 'natureza'], d: 'Circuito de ~180 km com montanha, lago e mar. Faça no sentido anti-horário pra fugir dos ônibus.' },
          { n: 'Península de Dingle', wv: 'Dingle Peninsula', tags: ['costa', 'roadtrip'], d: 'Menor e mais bonita que o Ring of Kerry, com o Slea Head Drive e vilas de língua irlandesa.' },
          { n: 'Wild Atlantic Way', wv: 'Wild Atlantic Way', tags: ['roadtrip', 'costa'], d: 'A rota costeira de 2.500 km que amarra tudo, de Cork a Donegal. Escolha um trecho, não tente tudo.' },
        ],
      },
    ],
  },
  {
    id: 'ocidental',
    nome: 'Europa Ocidental & Alpes',
    emoji: '🏔️',
    resumo: 'O núcleo clássico: museus, capitais, castelos e a cordilheira alpina. É também onde estão as portas de entrada mais baratas do Brasil — o que faz dessa região quase sempre o começo ou o fim do roteiro.',
    paises: [
      {
        slug: 'paises-baixos', nome: 'Países Baixos', bandeira: '🇳🇱', wv: 'Netherlands',
        tags: ['cidade', 'historia'],
        resumo: 'Urbano e cultural, do começo ao fim. Canal, museu e bicicleta. País minúsculo e com trem bom — dá pra ver quatro cidades usando uma base só.',
        quando: 'Abr–mai pelas tulipas · jun–set pro clima',
        portas: [ { c: 'AMS', n: 'Amsterdã Schiphol', t: 'porta' } ],
        termas: null,
        cidades: [
          { n: 'Amsterdã', wv: 'Amsterdam', tags: ['cidade', 'historia'], d: 'Rijksmuseum, Van Gogh e Casa de Anne Frank (ingresso só online, semanas antes). Cinturão de canais UNESCO.' },
          { n: 'Roterdã', wv: 'Rotterdam', tags: ['cidade'], d: 'O oposto de Amsterdã: reconstruída do zero após a guerra, é o parque de arquitetura moderna do país.' },
          { n: 'Utrecht', wv: 'Utrecht', tags: ['cidade', 'historia'], d: 'Canais em dois níveis com cafés na altura da água. Mais tranquila e mais barata que a capital.' },
          { n: 'Haia & Scheveningen', wv: 'The Hague', tags: ['historia', 'costa'], d: 'Mauritshuis com a Moça com Brinco de Pérola, sede das cortes internacionais e praia grande ao lado.' },
          { n: 'Keukenhof', wv: 'Lisse', tags: ['natureza'], d: 'O maior jardim de bulbos do mundo. Abre só cerca de 8 semanas, entre março e maio — fora disso, não existe.' },
          { n: 'Giethoorn', wv: 'Giethoorn', tags: ['natureza'], d: 'Vila sem ruas de carro: circula-se de barco pelos canais. Vá cedo, porque enche.' },
        ],
      },
      {
        slug: 'belgica', nome: 'Bélgica', bandeira: '🇧🇪', wv: 'Belgium',
        tags: ['historia', 'gastronomia', 'cidade'],
        resumo: 'Cidade histórica pequena, cerveja e chocolate. Rende 3 dias, não 10 — e funciona muito bem emendada com Países Baixos ou norte da França de trem.',
        quando: 'Abr–out · dez pelos mercados de Natal',
        portas: [ { c: 'BRU', n: 'Bruxelas', t: 'porta' }, { c: 'CRL', n: 'Charleroi (low cost)', t: 'regional' } ],
        termas: 'Sim, e é literalmente a origem da palavra: a cidade de Spa, nas Ardenas, deu nome ao conceito. As Thermes de Spa ficam no alto do morro, ligadas ao centro por funicular, e usam água mineral local. É mais discreto que Budapeste ou Islândia, mas é real e histórico.',
        cidades: [
          { n: 'Bruxelas', wv: 'Brussels', tags: ['cidade', 'gastronomia'], d: 'Grand Place (uma das praças mais bonitas da Europa), art nouveau de Horta e museu do Magritte.' },
          { n: 'Bruges', wv: 'Bruges', tags: ['historia'], d: 'Centro medieval intacto com canais. Durma lá — de dia a cidade é tomada por excursões, de noite ela volta a ser sua.' },
          { n: 'Gante', wv: 'Ghent', tags: ['historia', 'cidade'], d: 'Tem o casario de Bruges, mas com vida universitária e menos gente. Retábulo de Van Eyck na catedral.' },
          { n: 'Antuérpia', wv: 'Antwerp', tags: ['cidade', 'historia'], d: 'Rubens, moda de vanguarda, diamantes e uma estação de trem que parece um palácio.' },
          { n: 'Spa & Ardenas', wv: 'Spa', tags: ['termas', 'natureza'], d: 'Floresta, colinas e a cidade termal que batizou a categoria. Também o circuito de Spa-Francorchamps.' },
        ],
      },
      {
        slug: 'luxemburgo', nome: 'Luxemburgo', bandeira: '🇱🇺', wv: 'Luxembourg',
        tags: ['historia', 'natureza'],
        resumo: 'Micro-país que quase ninguém programa e quase todo mundo gosta. Fortaleza dramática, floresta de trilha e vinho de Mosela. Transporte público gratuito no país inteiro.',
        quando: 'Mai–out',
        portas: [ { c: 'LUX', n: 'Luxemburgo', t: 'regional' } ],
        termas: 'Um só, mas de verdade: Mondorf-les-Bains, na fronteira com a França, é a única estância termal do país, com água quente natural.',
        cidades: [
          { n: 'Cidade de Luxemburgo', wv: 'Luxembourg City', tags: ['cidade', 'historia'], d: 'Construída sobre um desfiladeiro, com as casamatas do Bock escavadas na rocha. Centro histórico UNESCO.' },
          { n: 'Vianden', wv: 'Vianden', tags: ['historia'], d: 'Castelo medieval enorme sobre o rio, restaurado, com teleférico pra vista de cima.' },
          { n: 'Mullerthal', wv: 'Mullerthal', tags: ['natureza'], d: 'Apelidada de "Pequena Suíça Luxemburguesa": formações rochosas, cachoeiras e trilhas bem marcadas.' },
          { n: 'Vale do Mosela', wv: 'Moselle (Luxembourg)', tags: ['gastronomia'], d: 'Encostas de vinhedo em terraço, especialidade em brancos e crémant.' },
          { n: 'Mondorf-les-Bains', wv: 'Mondorf-les-Bains', tags: ['termas'], d: 'Domaine Thermal com piscinas de água termal natural, parque e cassino.' },
        ],
      },
      {
        slug: 'franca', nome: 'França', bandeira: '🇫🇷', wv: 'France',
        tags: ['historia', 'gastronomia', 'montanha', 'praia', 'costa', 'roadtrip'],
        resumo: 'Provavelmente o país mais completo da Europa: capital de museu, Mediterrâneo, Alpes, vinho de classe mundial e castelo. Justamente por isso, cuidado — dá pra fazer a França inteira e nunca sair da "mesma" tag.',
        quando: 'Mai–jun e set–out pro geral · jun–jul pra lavanda na Provence · dez–mar pros Alpes',
        portas: [ { c: 'CDG', n: 'Paris Charles de Gaulle', t: 'porta' }, { c: 'ORY', n: 'Paris Orly', t: 'regional' }, { c: 'NCE', n: 'Nice', t: 'regional' }, { c: 'LYS', n: 'Lyon', t: 'regional' }, { c: 'MRS', n: 'Marselha', t: 'regional' } ],
        termas: 'O termalismo francês é enorme, mas é mais "cura médica" do que banho de lazer — Vichy, Dax, Aix-les-Bains funcionam como estâncias de tratamento. Se você quer piscina termal com paisagem, os Pirineus entregam melhor: Cauterets e Bagnères-de-Luchon têm banhos termais de montanha. Não espere o nível de Budapeste ou da Islândia.',
        cidades: [
          { n: 'Paris', wv: 'Paris', tags: ['cidade', 'historia', 'gastronomia'], d: 'Louvre, Orsay, Orangerie. É a cidade em que "mais dias" sempre rende — mas reserve tudo com antecedência.' },
          { n: 'Nice & Côte d\'Azur', wv: 'Nice', tags: ['praia', 'cidade'], d: 'Mediterrâneo de água azul-turquesa, Promenade des Anglais e bate-volta pra Èze, Antibes e Mônaco.' },
          { n: 'Lyon', wv: 'Lyon', tags: ['gastronomia', 'historia'], d: 'Considerada a capital gastronômica do país. Bouchons tradicionais e a Vieux Lyon renascentista com seus traboules.' },
          { n: 'Bordeaux', wv: 'Bordeaux', tags: ['gastronomia', 'cidade'], d: 'Centro do século XVIII inteiro em pedra clara, mais Saint-Émilion e Médoc a menos de 1h.' },
          { n: 'Provence', wv: 'Provence', tags: ['roadtrip', 'gastronomia'], d: 'Avignon, Gordes, Roussillon e os campos de lavanda de Valensole — que florescem de meados de junho a meados de julho.' },
          { n: 'Chamonix & Alpes', wv: 'Chamonix', tags: ['montanha', 'neve'], d: 'Mont Blanc de perto, teleférico da Aiguille du Midi a 3.842 m. Genebra (GVA) é a porta prática, a 1h de carro.' },
          { n: 'Normandia', wv: 'Normandy', tags: ['historia', 'costa'], d: 'Praias do Desembarque, cemitérios militares e o Mont-Saint-Michel — que fica ao lado, já na Bretanha.' },
          { n: 'Vale do Loire', wv: 'Loire Valley', tags: ['historia', 'gastronomia'], d: 'Concentração absurda de castelos renascentistas: Chambord, Chenonceau, Amboise. Ótimo de bicicleta.' },
          { n: 'Alsácia', wv: 'Alsace', tags: ['historia', 'gastronomia'], d: 'Estrasburgo, Colmar e a Rota dos Vinhos com vilas enxaimel. Em dezembro, os mercados de Natal mais famosos da França.' },
          { n: 'Córsega', wv: 'Corsica', tags: ['praia', 'costa', 'montanha'], d: '"Montanha no mar": praias de nível caribenho e o GR20, uma das trilhas mais duras da Europa.' },
        ],
      },
      {
        slug: 'alemanha', nome: 'Alemanha', bandeira: '🇩🇪', wv: 'Germany',
        tags: ['cidade', 'historia', 'montanha', 'termas'],
        resumo: 'Versátil e barata pro que entrega. Berlim e Munique são cidades opostas dentro do mesmo país, tem Alpes no sul, castelo de conto de fadas, vale de vinho e uma das melhores tradições termais da Europa.',
        quando: 'Mai–set pro geral · fim de set pra Oktoberfest · dez pros mercados de Natal',
        portas: [ { c: 'FRA', n: 'Frankfurt', t: 'porta' }, { c: 'MUC', n: 'Munique', t: 'porta' }, { c: 'BER', n: 'Berlim', t: 'regional' }, { c: 'DUS', n: 'Düsseldorf', t: 'regional' } ],
        termas: 'Sim, e é levada a sério. Baden-Baden é a referência: o Friedrichsbad é um ritual romano-irlandês de 17 etapas (tradicionalmente sem roupa e sem celular) e a Caracalla Therme ao lado é a versão de maiô. Wiesbaden e Bad Ems completam — as três entraram na lista UNESCO das grandes cidades termais da Europa.',
        cidades: [
          { n: 'Berlim', wv: 'Berlin', tags: ['cidade', 'historia'], d: 'História do século XX a céu aberto: Muro, Portão de Brandemburgo, Ilha dos Museus. Vida noturna sem hora pra acabar.' },
          { n: 'Munique', wv: 'Munich', tags: ['cidade', 'gastronomia'], d: 'Cervejarias, Marienplatz e a melhor base pros Alpes bávaros. Oktoberfest lota a cidade e triplica hotel.' },
          { n: 'Baviera & Neuschwanstein', wv: 'Fussen', tags: ['historia', 'montanha', 'roadtrip'], d: 'O castelo que inspirou a Disney, mais a Rota Romântica com Rothenburg ob der Tauber.' },
          { n: 'Baden-Baden', wv: 'Baden-Baden', tags: ['termas'], d: 'A cidade termal clássica alemã, na borda da Floresta Negra. Cassino histórico e parque termal.' },
          { n: 'Floresta Negra', wv: 'Black Forest', tags: ['natureza', 'roadtrip'], d: 'Estradas sinuosas entre florestas densas, relógios cuco, lagos e a Schwarzwälder Kirschtorte de origem.' },
          { n: 'Vale do Reno & Mosela', wv: 'Rhine Valley', tags: ['gastronomia', 'roadtrip', 'historia'], d: 'Trecho UNESCO com castelo em cima de cada curva do rio e vinhedos de Riesling em encostas quase verticais.' },
          { n: 'Hamburgo', wv: 'Hamburg', tags: ['cidade'], d: 'Porto enorme, armazéns UNESCO da Speicherstadt e a Elbphilharmonie.' },
          { n: 'Dresden', wv: 'Dresden', tags: ['historia'], d: 'Barroco reconstruído tijolo a tijolo depois do bombardeio, com a Frauenkirche como símbolo.' },
          { n: 'Colônia', wv: 'Cologne', tags: ['historia'], d: 'A catedral gótica mais impressionante do país, colada na estação de trem.' },
        ],
      },
      {
        slug: 'austria', nome: 'Áustria', bandeira: '🇦🇹', wv: 'Austria',
        tags: ['historia', 'montanha', 'termas', 'neve'],
        resumo: 'Duas coisas muito distintas no mesmo país: a Viena imperial de palácio, ópera e café; e o Tirol alpino de esqui e terma. Combinação de cultura + montanha difícil de bater.',
        quando: 'Mai–set pros Alpes no verde · dez–mar pra neve e termas',
        portas: [ { c: 'VIE', n: 'Viena', t: 'porta' }, { c: 'SZG', n: 'Salzburgo', t: 'regional' }, { c: 'INN', n: 'Innsbruck', t: 'regional' } ],
        termas: 'Sim, e é uma das melhores da Europa central. Aqua Dome, em Längenfeld (Ötztal), tem piscinas suspensas em forma de taça com os Alpes em volta; Rogner Bad Blumau, na Estíria, foi projetada pelo Hundertwasser e parece um desenho; e Bad Gastein é a estância termal alpina histórica, encravada numa cachoeira.',
        cidades: [
          { n: 'Viena', wv: 'Vienna', tags: ['cidade', 'historia'], d: 'Schönbrunn, Hofburg, Klimt no Belvedere e a ópera. Cultura de café que é patrimônio imaterial UNESCO.' },
          { n: 'Salzburgo', wv: 'Salzburg', tags: ['historia', 'montanha'], d: 'Cidade de Mozart, fortaleza no alto e centro barroco UNESCO, com os Alpes de fundo.' },
          { n: 'Hallstatt', wv: 'Hallstatt', tags: ['natureza', 'historia'], d: 'A vila-cartão-postal entre lago e montanha. Absurdamente lotada no meio do dia — durma ou chegue cedo.' },
          { n: 'Innsbruck', wv: 'Innsbruck', tags: ['montanha', 'neve'], d: 'Cidade alpina de verdade: do centro você pega o funicular e em 20 min está a 2.000 m.' },
          { n: 'Ötztal & Aqua Dome', wv: 'Otztal', tags: ['termas', 'neve'], d: 'Vale de esqui com o complexo termal mais fotogênico dos Alpes austríacos.' },
          { n: 'Bad Gastein', wv: 'Bad Gastein', tags: ['termas', 'neve'], d: 'Estância belle époque construída sobre uma cachoeira, com águas termais radônicas e ski de alto nível.' },
          { n: 'Wachau', wv: 'Wachau', tags: ['gastronomia', 'natureza'], d: 'Trecho UNESCO do Danúbio entre Melk e Krems: mosteiro barroco, vinhedos e Grüner Veltliner.' },
        ],
      },
      {
        slug: 'suica', nome: 'Suíça', bandeira: '🇨🇭', wv: 'Switzerland',
        tags: ['montanha', 'natureza', 'termas'],
        resumo: 'A montanha em estado puro, com a melhor infraestrutura do mundo pra chegar até ela — trem panorâmico, teleférico e vilarejo sem carro. É cara de doer, então funciona melhor como bloco curto e intenso dentro de um roteiro maior.',
        quando: 'Jun–set pra trilha e trem panorâmico · dez–mar pra neve',
        portas: [ { c: 'ZRH', n: 'Zurique', t: 'porta' }, { c: 'GVA', n: 'Genebra', t: 'porta' }, { c: 'BSL', n: 'Basileia', t: 'regional' } ],
        termas: 'Sim, e com um diferencial: água termal a 1.400 m de altitude. Leukerbad é o maior centro termal alpino, com piscinas quentes ao ar livre cercadas de paredões; as Termas de Vals (7132) são uma obra de arquitetura do Peter Zumthor em quartzito; e Bad Ragaz é a versão sofisticada, ligada à garganta de Tamina.',
        cidades: [
          { n: 'Lucerna', wv: 'Lucerne', tags: ['cidade', 'montanha'], d: 'Ponte de madeira coberta, lago e o Pilatus/Rigi logo atrás. A melhor base pra quem tem poucos dias.' },
          { n: 'Interlaken & Jungfrau', wv: 'Interlaken', tags: ['montanha', 'natureza'], d: 'Entre dois lagos, com acesso a Grindelwald, Lauterbrunnen e ao Jungfraujoch, a estação de trem mais alta da Europa.' },
          { n: 'Zermatt', wv: 'Zermatt', tags: ['montanha', 'neve'], d: 'Vila sem carros aos pés do Matterhorn. Ski o ano inteiro no glaciar.' },
          { n: 'Lauterbrunnen', wv: 'Lauterbrunnen', tags: ['natureza', 'montanha'], d: 'Vale glacial com 72 cachoeiras caindo de paredões verticais. Base pra Mürren e Wengen.' },
          { n: 'Zurique', wv: 'Zurich', tags: ['cidade'], d: 'A maior cidade do país, à beira do lago. Porta de entrada mais prática — mas a Suíça não é sobre ela.' },
          { n: 'Genebra', wv: 'Geneva', tags: ['cidade'], d: 'Lago Léman, jato d\'água e sede da ONU/Cruz Vermelha. Também a porta mais rápida pra Chamonix.' },
          { n: 'Leukerbad', wv: 'Leukerbad', tags: ['termas', 'montanha'], d: 'Maior estância termal dos Alpes, com piscinas a 51°C na saída da fonte e vista pro vale.' },
          { n: 'Engadina & St. Moritz', wv: 'St. Moritz', tags: ['neve', 'montanha'], d: 'Luxo de inverno, lagos de altitude e o ponto de partida do Bernina Express.' },
          { n: 'Ticino & Lugano', wv: 'Lugano', tags: ['cidade', 'natureza'], d: 'A Suíça italiana: palmeira, lago e clima ameno. Parece outro país.' },
        ],
      },
      {
        slug: 'liechtenstein', nome: 'Liechtenstein', bandeira: '🇱🇮', wv: 'Liechtenstein',
        tags: ['montanha', 'historia'],
        resumo: 'Microestado alpino de 160 km² entre Suíça e Áustria. Não é destino de viagem — é uma parada de meio dia que se encaixa quando você já está em Zurique ou no Tirol. O que oferece: um principado ainda governado por uma família, montanha e um centro minúsculo.',
        quando: 'Mai–out pra caminhada · dez–mar pro esqui em Malbun',
        portas: [ { c: 'ZRH', n: 'via Zurique — ~1h20 de carro; sem aeroporto próprio', t: 'porta' } ],
        termas: null,
        cidades: [
          { n: 'Vaduz', wv: 'Vaduz', tags: ['cidade', 'historia'], d: 'Capital com uma rua principal. Castelo do príncipe no alto (só se vê por fora), museu de arte e o carimbo de passaporte pago no posto de turismo.' },
          { n: 'Malbun', wv: 'Malbun', tags: ['neve', 'montanha'], d: 'A única estação de esqui do país, pequena e familiar, a 1.600 m.' },
          { n: 'Balzers & Liechtenstein-Weg', wv: 'Balzers', tags: ['natureza', 'historia'], d: 'O castelo de Gutenberg no sul do país e a trilha de 75 km que atravessa as 11 comunas — dá pra fazer só um trecho como bate-volta.' },
        ],
      },
    ],
  },
  {
    id: 'mediterraneo-oeste',
    nome: 'Ibéria & Mediterrâneo Ocidental',
    emoji: '🌊',
    resumo: 'Sol, praia, história e comida — e, na prática, as portas de entrada mais baratas saindo do Brasil. Cuidado com a repetição: Portugal, Espanha e Itália entregam tags parecidas, então combine no máximo dois deles e complete com outra família.',
    paises: [
      {
        slug: 'portugal', nome: 'Portugal', bandeira: '🇵🇹', wv: 'Portugal',
        tags: ['cidade', 'gastronomia', 'praia', 'costa', 'natureza'],
        resumo: 'Sem barreira de idioma, porta de entrada barata e uma variedade grande pro tamanho: cidade histórica, vinho, praia de falésia e, nas ilhas, natureza vulcânica de verdade.',
        quando: 'Abr–jun e set–out no continente · jun–set pros Açores',
        portas: [ { c: 'LIS', n: 'Lisboa', t: 'porta' }, { c: 'OPO', n: 'Porto', t: 'porta' }, { c: 'FAO', n: 'Faro (Algarve)', t: 'regional' }, { c: 'FNC', n: 'Funchal (Madeira)', t: 'regional' }, { c: 'PDL', n: 'Ponta Delgada (Açores)', t: 'regional' } ],
        termas: 'Nos Açores, sim, e são ótimas: em Furnas (São Miguel) você tem o tanque de água ferruginosa laranja do Parque Terra Nostra e as poças escalonadas da Poça da Dona Beija, que abre até tarde da noite. No continente o termalismo existe (Chaves, São Pedro do Sul) mas é mais clínico que lazer.',
        cidades: [
          { n: 'Lisboa', wv: 'Lisbon', tags: ['cidade', 'historia', 'gastronomia'], d: 'Miradouros, azulejo, bondes e Belém. Base excelente porque tudo no sul do país fica perto.' },
          { n: 'Porto', wv: 'Porto', tags: ['cidade', 'gastronomia'], d: 'Ribeira sobre o Douro e as caves de vinho do Porto em Gaia, do outro lado da ponte.' },
          { n: 'Sintra', wv: 'Sintra', tags: ['historia', 'natureza'], d: 'Palácio da Pena, Quinta da Regaleira e serra com microclima. Bate-volta de Lisboa, mas exige o dia inteiro e ingresso comprado antes.' },
          { n: 'Algarve', wv: 'Algarve', tags: ['praia', 'costa', 'natureza'], d: 'Falésias douradas, grutas (Benagil) e as praias mais bonitas do continente. Lotado em agosto.' },
          { n: 'Vale do Douro', wv: 'Douro Valley', tags: ['gastronomia', 'natureza'], d: 'Vinhedos em terraço (UNESCO) descendo até o rio. Melhor de trem ou barco, na vindima de setembro.' },
          { n: 'Madeira', wv: 'Madeira', tags: ['natureza', 'montanha'], d: 'Trilhas de levada, o pico do Areeiro a 1.800 m e clima ameno o ano inteiro. Nada a ver com o continente.' },
          { n: 'Açores — São Miguel', wv: 'Sao Miguel', tags: ['natureza', 'termas'], d: 'Crateras com lagoas (Sete Cidades, Furnas), fumarolas, chá e piscinas termais. Baleias entre abril e setembro.' },
          { n: 'Évora & Alentejo', wv: 'Evora', tags: ['historia', 'gastronomia'], d: 'Templo romano, capela dos ossos e uma das melhores regiões de vinho e comida do país, sem multidão.' },
          { n: 'Nazaré', wv: 'Nazare', tags: ['costa'], d: 'As maiores ondas surfadas do mundo, de outubro a março. Fora da temporada, é uma vila de praia comum.' },
        ],
      },
      {
        slug: 'espanha', nome: 'Espanha', bandeira: '🇪🇸', wv: 'Spain',
        tags: ['cidade', 'historia', 'praia', 'gastronomia'],
        resumo: 'Cidade grande, arte, praia e a melhor relação comida/preço da Europa Ocidental. Diferença importante: o norte (San Sebastián, Bilbao, Galícia) é verde, fresco e gastronômico; o sul é mourisco e quente. São experiências distintas.',
        quando: 'Abr–jun e set–out · jul–ago só se for praia (o interior passa de 40°C)',
        portas: [ { c: 'MAD', n: 'Madri', t: 'porta' }, { c: 'BCN', n: 'Barcelona', t: 'porta' }, { c: 'AGP', n: 'Málaga', t: 'regional' }, { c: 'PMI', n: 'Palma de Mallorca', t: 'regional' }, { c: 'IBZ', n: 'Ibiza', t: 'regional' }, { c: 'MAH', n: 'Menorca', t: 'regional' }, { c: 'TFS', n: 'Tenerife Sul', t: 'regional' } ],
        termas: 'Sim, e é o segredo mais bem guardado: Ourense, na Galícia, é a capital termal do país. Tem fontes quentes na rua no centro (As Burgas) e uma sequência de poças termais públicas às margens do rio Miño — Outariz, Muíño da Veiga — várias delas gratuitas. Nada turístico, e é água termal de verdade.',
        cidades: [
          { n: 'Madri', wv: 'Madrid', tags: ['cidade', 'historia', 'gastronomia'], d: 'Prado, Reina Sofía (Guernica) e Thyssen num raio de 1 km. Vida de rua até tarde e o melhor hub de trem do país.' },
          { n: 'Barcelona', wv: 'Barcelona', tags: ['cidade', 'historia', 'praia'], d: 'Sagrada Família, Park Güell e o modernismo catalão, com praia no meio da cidade. Reserve o Gaudí com antecedência.' },
          { n: 'Sevilha', wv: 'Seville', tags: ['historia', 'cidade'], d: 'Real Alcázar, catedral gigante e flamenco de verdade em Triana. Evite julho e agosto.' },
          { n: 'Granada', wv: 'Granada', tags: ['historia', 'montanha'], d: 'Alhambra — ingresso esgota semanas antes — e a Sierra Nevada logo acima, com ski a 30 min da cidade.' },
          { n: 'Córdoba', wv: 'Cordoba', tags: ['historia'], d: 'A Mesquita-Catedral é única no mundo. Em maio, os pátios floridos viram festival.' },
          { n: 'San Sebastián', wv: 'San Sebastian', tags: ['gastronomia', 'praia', 'costa'], d: 'Uma das maiores concentrações de estrelas Michelin do planeta, e os pintxos da Parte Vieja. Praia da Concha no meio.' },
          { n: 'Bilbao', wv: 'Bilbao', tags: ['cidade', 'historia'], d: 'Guggenheim de Gehry e uma cidade industrial que se reinventou por completo.' },
          { n: 'Valência', wv: 'Valencia', tags: ['cidade', 'gastronomia', 'praia'], d: 'Cidade das Artes e Ciências, berço da paella e praia urbana. Fallas em março.' },
          { n: 'Mallorca', wv: 'Mallorca', tags: ['praia', 'montanha'], d: 'A maior das Baleares: calas e praia de um lado, a serra de Tramuntana (UNESCO) com estradas de ciclismo do outro.' },
          { n: 'Menorca', wv: 'Menorca', tags: ['praia', 'natureza'], d: 'A Balear tranquila — reserva da biosfera UNESCO, calas de areia branca, Ciutadella e o Camí de Cavalls contornando a ilha inteira a pé.' },
          { n: 'Ibiza & Formentera', wv: 'Ibiza', tags: ['praia', 'cidade'], d: 'Fama de balada, mas o norte da ilha é rural e calmo, e Dalt Vila é cidade murada UNESCO. Formentera fica a 30 min de balsa e tem a água mais clara das Baleares.' },
          { n: 'Tenerife', wv: 'Tenerife', tags: ['natureza', 'praia'], d: 'O Teide, ponto mais alto da Espanha, num parque nacional que parece Marte. Clima bom o ano inteiro.' },
          { n: 'Ourense', wv: 'Ourense', tags: ['termas', 'gastronomia'], d: 'Termas públicas na beira do rio, na Galícia. Combina com Santiago de Compostela e com o marisco da Rías Baixas.' },
          { n: 'Santiago de Compostela', wv: 'Santiago de Compostela', tags: ['historia', 'natureza'], d: 'Fim do Caminho. Centro medieval UNESCO e ponto de chegada de quem faz a peregrinação a pé.' },
        ],
      },
      {
        slug: 'andorra', nome: 'Andorra', bandeira: '🇦🇩', wv: 'Andorra',
        tags: ['montanha', 'neve', 'termas'],
        resumo: 'Principado nos Pirineus, entre França e Espanha. Sem aeroporto — entra-se de carro ou ônibus por Barcelona (~3h) ou Toulouse (~3h). O que oferece: o maior domínio esquiável dos Pirineus, um centro termal grande de verdade e compras sem os impostos da UE.',
        quando: 'Dez–mar pra neve · jun–set pra trilha',
        portas: [ { c: 'BCN', n: 'via Barcelona — ~3h de carro/ônibus', t: 'porta' }, { c: 'TLS', n: 'via Toulouse — ~3h', t: 'regional' } ],
        termas: 'Sim, e é o motivo real pra parar aqui: Caldea, em Escaldes-Engordany, é um dos maiores complexos termais lúdicos do sul da Europa, alimentado por fonte termal natural, com lagoa interna, piscinas ao ar livre com vista pras montanhas e uma torre de vidro que virou símbolo do país.',
        cidades: [
          { n: 'Andorra la Vella', wv: 'Andorra la Vella', tags: ['cidade'], d: 'Capital mais alta da Europa. A avenida principal é basicamente uma zona franca — eletrônico, perfume e álcool bem mais baratos.' },
          { n: 'Caldea', wv: 'Escaldes-Engordany', tags: ['termas'], d: 'Complexo termal com águas a ~70°C na fonte, distribuídas por dezenas de piscinas e banhos.' },
          { n: 'Grandvalira', wv: 'Grandvalira', tags: ['neve', 'montanha'], d: 'Maior área esquiável dos Pirineus, com mais de 200 km de pistas e temporada longa.' },
          { n: 'Ordino & Vall del Madriu', wv: 'Ordino', tags: ['natureza', 'montanha'], d: 'O lado rural do país. O vale do Madriu-Perafita-Claror é UNESCO e só se acessa a pé.' },
        ],
      },
      {
        slug: 'monaco', nome: 'Mônaco', bandeira: '🇲🇨', wv: 'Monaco',
        tags: ['cidade', 'costa'],
        resumo: 'Segundo menor país do mundo, 2 km² grudados na Riviera Francesa. Sem aeroporto: Nice (NCE) fica a 30 min de ônibus/trem ou 7 min de helicóptero. O que oferece: um bate-volta de meio dia com cassino histórico, porto de iates e um dos melhores museus oceanográficos do mundo.',
        quando: 'Abr–out · maio no GP de Fórmula 1 (cidade fechada e preços em outro patamar)',
        portas: [ { c: 'NCE', n: 'via Nice — ~30 min de trem; sem aeroporto próprio', t: 'porta' } ],
        termas: 'Não no sentido de fonte termal. Os Thermes Marins de Monte-Carlo são talassoterapia — água do mar aquecida, não água termal geotérmica. Bom spa, categoria diferente.',
        cidades: [
          { n: 'Monte Carlo', wv: 'Monaco', tags: ['cidade'], d: 'Cassino de 1863, Hôtel de Paris e as curvas do circuito de F1 que você percorre a pé pela rua normal.' },
          { n: 'Monaco-Ville (Le Rocher)', wv: 'Monaco', tags: ['historia'], d: 'A cidade velha sobre o rochedo: palácio dos Grimaldi, catedral e a troca da guarda às 11h55.' },
          { n: 'Museu Oceanográfico', wv: 'Monaco', tags: ['historia', 'costa'], d: 'Prédio monumental de 1910 dependurado na falésia, fundado pelo príncipe Alberto I. Vale mais que o cassino.' },
          { n: 'Port Hercule', wv: 'Monaco', tags: ['costa'], d: 'O porto de iates. Em setembro recebe o Monaco Yacht Show.' },
        ],
      },
      {
        slug: 'italia', nome: 'Itália', bandeira: '🇮🇹', wv: 'Italy',
        tags: ['historia', 'gastronomia', 'praia', 'montanha', 'termas'],
        resumo: 'Junto com a França, o país mais completo da Europa — e o mais fácil de fazer errado, porque as cidades de arte se parecem entre si depois da terceira. Alterne: uma cidade histórica, depois Dolomitas ou costa.',
        quando: 'Abr–jun e set–out · jul–ago só litoral e montanha (as cidades ficam insuportáveis)',
        portas: [ { c: 'FCO', n: 'Roma Fiumicino', t: 'porta' }, { c: 'MXP', n: 'Milão Malpensa', t: 'porta' }, { c: 'VCE', n: 'Veneza', t: 'regional' }, { c: 'NAP', n: 'Nápoles', t: 'regional' }, { c: 'CTA', n: 'Catânia (Sicília)', t: 'regional' } ],
        termas: 'Sim, e com opção pra todo bolso. Saturnia, na Toscana, tem as Cascate del Mulino: cascatas termais a 37°C ao ar livre, abertas 24h e de graça. Ischia é uma ilha vulcânica inteira dedicada a isso, com parques termais como Negombo e Poseidon. E nos Alpes, QC Terme Bormio e as Terme Merano juntam água quente com neve.',
        cidades: [
          { n: 'Roma', wv: 'Rome', tags: ['historia', 'cidade', 'gastronomia'], d: 'Coliseu, Fórum, Panteão e o Vaticano dentro dela. Camada sobre camada de 2.700 anos.' },
          { n: 'Florença', wv: 'Florence', tags: ['historia', 'gastronomia'], d: 'Uffizi, Davi de Michelangelo e o Duomo de Brunelleschi. Compacta — se faz a pé.' },
          { n: 'Veneza', wv: 'Venice', tags: ['historia', 'cidade'], d: 'Não tem paralelo em lugar nenhum. Durma na ilha: depois das 18h os cruzeiros vão embora e a cidade muda.' },
          { n: 'Dolomitas', wv: 'Dolomites', tags: ['montanha', 'natureza', 'neve'], d: 'Paredões de calcário rosado, Alpe di Siusi, Tre Cime. Cultura meio austríaca, e alguns dos melhores refúgios de montanha da Europa.' },
          { n: 'Costa Amalfitana', wv: 'Amalfi Coast', tags: ['praia', 'roadtrip'], d: 'Positano, Amalfi e Ravello dependurados na falésia. A estrada é linda e estreita — considere ônibus ou barco em vez de carro.' },
          { n: 'Toscana', wv: 'Tuscany', tags: ['gastronomia', 'roadtrip'], d: 'Val d\'Orcia, Chianti, Siena e San Gimignano. País de carro alugado e agriturismo.' },
          { n: 'Sicília', wv: 'Sicily', tags: ['historia', 'praia', 'natureza'], d: 'Templos gregos melhores que os da Grécia, o Etna ativo, Taormina e uma cozinha própria com influência árabe.' },
          { n: 'Sardenha', wv: 'Sardinia', tags: ['praia', 'costa', 'natureza'], d: 'As águas mais claras do Mediterrâneo, da Costa Smeralda às praias selvagens do sul.' },
          { n: 'Lagos do Norte', wv: 'Lake Como', tags: ['natureza', 'montanha'], d: 'Como, Garda e Maggiore: vilas com jardim, montanha atrás e ferry entre os povoados.' },
          { n: 'Cinque Terre', wv: 'Cinque Terre', tags: ['costa', 'natureza'], d: 'Cinco vilas coloridas ligadas por trilha e trem local sobre o mar. Vá fora de julho/agosto.' },
          { n: 'Bolonha', wv: 'Bologna', tags: ['gastronomia', 'historia'], d: 'A capital da comida italiana, com 40 km de arcadas UNESCO. Base pra Parma e Modena.' },
          { n: 'Nápoles & Pompeia', wv: 'Naples', tags: ['cidade', 'gastronomia', 'historia'], d: 'A pizza na origem, um centro histórico caótico e vivo, e Pompeia/Herculano a 30 min de trem.' },
          { n: 'Saturnia', wv: 'Saturnia', tags: ['termas'], d: 'Cascatas termais naturais na Maremma toscana. Gratuitas, abertas 24h — vá de madrugada ou bem cedo.' },
          { n: 'Ischia', wv: 'Ischia', tags: ['termas', 'praia'], d: 'Ilha vulcânica no golfo de Nápoles, com dezenas de fontes termais e parques termais à beira-mar.' },
        ],
      },
      {
        slug: 'san-marino', nome: 'San Marino', bandeira: '🇸🇲', wv: 'San Marino',
        tags: ['historia', 'montanha'],
        resumo: 'Enclave de 61 km² dentro da Itália, no alto do Monte Titano. Sem aeroporto: entra-se por Rimini (~30 min) ou Bolonha (~2h). O que oferece: uma cidadela medieval murada com três torres e vista até o Adriático — meio dia, encaixado num roteiro pela Emília-Romanha.',
        quando: 'Abr–out',
        portas: [ { c: 'RMI', n: 'via Rimini — ~30 min de ônibus; sem aeroporto próprio', t: 'regional' }, { c: 'BLQ', n: 'via Bolonha — ~2h', t: 'porta' } ],
        termas: null,
        cidades: [
          { n: 'Cidade de San Marino', wv: 'San Marino', tags: ['historia'], d: 'Centro histórico e Monte Titano são UNESCO. As três torres (Guaita, Cesta e Montale) são o símbolo do país e ficam ligadas por um caminho na crista.' },
          { n: 'Borgo Maggiore', wv: 'San Marino', tags: ['cidade'], d: 'Cidade abaixo da cidadela, ligada por teleférico. É onde ficam a feira e os preços normais.' },
        ],
      },
      {
        slug: 'vaticano', nome: 'Vaticano', bandeira: '🇻🇦', wv: 'Vatican City',
        tags: ['historia'],
        resumo: 'Menor país do mundo, 0,44 km² dentro de Roma. Não é uma parada logística — é uma manhã do seu roteiro romano. O que oferece: um dos maiores acervos de arte do planeta concentrado num espaço mínimo.',
        quando: 'O ano todo — entre bem cedo ou no fim da tarde',
        portas: [ { c: 'FCO', n: 'via Roma Fiumicino', t: 'porta' } ],
        termas: null,
        cidades: [
          { n: 'Basílica de São Pedro', wv: 'Vatican City', tags: ['historia'], d: 'Entrada gratuita, mas a fila é longa. Subir na cúpula é pago e vale — 551 degraus (ou elevador até metade).' },
          { n: 'Museus Vaticanos & Capela Sistina', wv: 'Vatican City', tags: ['historia'], d: 'Quilômetros de galeria terminando na Sistina. Na prática é obrigatório reservar horário online com antecedência.' },
          { n: 'Praça de São Pedro', wv: 'Vatican City', tags: ['historia'], d: 'A colunata de Bernini. Nas quartas-feiras costuma haver audiência papal, com ingresso gratuito solicitado antes.' },
        ],
      },
      {
        slug: 'malta', nome: 'Malta', bandeira: '🇲🇹', wv: 'Malta',
        tags: ['praia', 'historia', 'cidade'],
        resumo: 'Arquipélago no meio do Mediterrâneo com 7.000 anos de camadas: templos pré-históricos, cavaleiros, ingleses. Fala-se inglês, é barato pro padrão do Mediterrâneo, e cabe em 4–5 dias.',
        quando: 'Abr–jun e set–out · jul–ago é muito quente e cheio',
        portas: [ { c: 'MLA', n: 'Malta', t: 'regional' } ],
        termas: null,
        cidades: [
          { n: 'Valletta', wv: 'Valletta', tags: ['historia', 'cidade'], d: 'Capital fortificada dos Cavaleiros de São João, UNESCO inteira. A Co-Catedral guarda dois Caravaggios.' },
          { n: 'Mdina', wv: 'Mdina', tags: ['historia'], d: 'A "cidade silenciosa": antiga capital murada, quase sem carros, especialmente boa à noite.' },
          { n: 'Gozo', wv: 'Gozo', tags: ['natureza', 'praia'], d: 'Ilha vizinha, mais rural. Templos de Ġgantija — mais antigos que as pirâmides do Egito — e mergulho excelente.' },
          { n: 'Comino & Blue Lagoon', wv: 'Comino', tags: ['praia'], d: 'Ilhota praticamente desabitada com uma enseada de água turquesa. Vá no primeiro barco.' },
          { n: 'Sliema & St. Julian\'s', wv: 'Sliema', tags: ['cidade', 'praia'], d: 'Onde ficam a maioria dos hotéis, os restaurantes e a vida noturna, com balsa direta pra Valletta.' },
        ],
      },
    ],
  },
  {
    id: 'central-leste',
    nome: 'Europa Central & Báltico',
    emoji: '🏛️',
    resumo: 'Custo-benefício. As mesmas praças barrocas e centros medievais da Europa Ocidental, por metade do preço — e com a melhor cultura termal do continente concentrada aqui (Hungria acima de tudo).',
    paises: [
      {
        slug: 'republica-tcheca', nome: 'República Tcheca', bandeira: '🇨🇿', wv: 'Czech Republic',
        tags: ['historia', 'cidade', 'termas'],
        resumo: 'Praga é uma das cidades históricas mais completas da Europa e ainda sai em conta. Fora dela, o país é mais do mesmo em escala menor — o que muda a experiência é o oeste termal e o sul do vinho.',
        quando: 'Abr–jun e set–out · dez pelos mercados de Natal',
        portas: [ { c: 'PRG', n: 'Praga', t: 'porta' } ],
        termas: 'Sim, mas atenção ao formato: a tradição tcheca é de "cidade-spa" — Karlovy Vary e Mariánské Lázně têm colunatas onde se bebe a água mineral quente em canecas próprias, e o banho acontece dentro de hotéis de tratamento. Ambas entraram na lista UNESCO das grandes cidades termais da Europa. Se o que você quer é piscina termal ao ar livre, a Hungria e a Eslováquia entregam mais.',
        cidades: [
          { n: 'Praga', wv: 'Prague', tags: ['historia', 'cidade'], d: 'Castelo, Ponte Carlos, cidade velha e bairro judeu praticamente intactos — a cidade escapou dos bombardeios. Cerveja mais barata que água.' },
          { n: 'Český Krumlov', wv: 'Cesky Krumlov', tags: ['historia'], d: 'Vila medieval numa curva fechada do rio Vltava, com castelo e teatro barroco original. UNESCO.' },
          { n: 'Karlovy Vary', wv: 'Karlovy Vary', tags: ['termas', 'historia'], d: 'Estância termal do século XIX com colunatas, 13 fontes quentes e o licor Becherovka.' },
          { n: 'Kutná Hora', wv: 'Kutna Hora', tags: ['historia'], d: 'Antiga cidade da prata, com catedral gótica e o ossuário de Sedlec, decorado com ossos humanos.' },
          { n: 'Morávia do Sul', wv: 'South Moravia', tags: ['gastronomia', 'natureza'], d: 'A região de vinho do país: Mikulov, adegas em Valtice e o parque de Lednice, UNESCO.' },
        ],
      },
      {
        slug: 'hungria', nome: 'Hungria', bandeira: '🇭🇺', wv: 'Hungary',
        tags: ['termas', 'cidade', 'historia', 'gastronomia'],
        resumo: 'Se termas pesam na sua escolha, a Hungria não é uma opção — é o destino. O país inteiro fica sobre um dos maiores reservatórios de água termal do mundo, e Budapeste é a única capital europeia com dezenas de banhos termais em funcionamento.',
        quando: 'Abr–jun e set–out · o inverno é ótimo justamente por causa das termas',
        portas: [ { c: 'BUD', n: 'Budapeste', t: 'porta' } ],
        termas: 'A melhor da Europa, disparado. Széchenyi é o cartão-postal: piscinas amarelas neobarrocas ao ar livre, quentes mesmo com neve caindo. Gellért é art nouveau com azulejo e vitral. Rudas mantém a cúpula otomana do século XVI e tem um jacuzzi panorâmico no telhado com vista pro Danúbio. Fora da capital: Hévíz é o maior lago termal biologicamente ativo do mundo, onde se boia ao ar livre a 33°C mesmo em janeiro, e Egerszalók tem uma cascata calcária branca formada pela própria água.',
        cidades: [
          { n: 'Budapeste', wv: 'Budapest', tags: ['cidade', 'termas', 'historia'], d: 'Parlamento sobre o Danúbio, Buda medieval de um lado, Peste imperial do outro, ruin bars no bairro judeu e banhos termais espalhados pela cidade.' },
          { n: 'Hévíz', wv: 'Heviz', tags: ['termas', 'natureza'], d: 'Lago termal natural de 4,4 hectares, quente o ano inteiro, cercado de floresta. Experiência única na Europa.' },
          { n: 'Egerszalók', wv: 'Egerszalok', tags: ['termas'], d: 'A "colina de sal": terraços brancos formados pelo depósito da água termal, com complexo de piscinas ao lado.' },
          { n: 'Eger', wv: 'Eger', tags: ['gastronomia', 'historia'], d: 'Castelo, minarete otomano e o Vale das Belas Mulheres, com adegas escavadas na rocha servindo o Egri Bikavér.' },
          { n: 'Lago Balaton', wv: 'Lake Balaton', tags: ['natureza', 'gastronomia'], d: 'O maior lago da Europa Central, destino de verão dos húngaros, com vinhedos vulcânicos na margem norte.' },
          { n: 'Tokaj', wv: 'Tokaj', tags: ['gastronomia'], d: 'Região UNESCO do vinho doce Tokaji Aszú, chamado por Luís XIV de "vinho dos reis".' },
        ],
      },
      {
        slug: 'polonia', nome: 'Polônia', bandeira: '🇵🇱', wv: 'Poland',
        tags: ['historia', 'cidade', 'montanha'],
        resumo: 'A melhor relação história/preço da Europa. Centros medievais reconstruídos com precisão, memória pesada do século XX e — surpresa pra muita gente — termas geotérmicas de verdade no sul, ao pé dos Tatras.',
        quando: 'Mai–set · dez–fev pra neve e termas em Zakopane',
        portas: [ { c: 'WAW', n: 'Varsóvia Chopin', t: 'porta' }, { c: 'KRK', n: 'Cracóvia', t: 'regional' }, { c: 'GDN', n: 'Gdańsk', t: 'regional' } ],
        termas: 'Sim, e pouca gente sabe: a região de Zakopane, nos Tatras, tem água geotérmica abundante. Termy Chochołowskie e Termy Bukovina são complexos grandes de piscinas ao ar livre com vista direta pras montanhas nevadas — mesma ideia da Islândia, por uma fração do preço.',
        cidades: [
          { n: 'Cracóvia', wv: 'Krakow', tags: ['historia', 'cidade'], d: 'A maior praça medieval da Europa, o castelo de Wawel e o bairro judeu de Kazimierz. Auschwitz-Birkenau e a mina de sal de Wieliczka ficam a ~1h.' },
          { n: 'Varsóvia', wv: 'Warsaw', tags: ['historia', 'cidade'], d: 'Cidade velha reconstruída do zero após 1945 — tão fiel que virou UNESCO. Museu do Levante e Polin, sobre a história judaica polonesa.' },
          { n: 'Gdańsk', wv: 'Gdansk', tags: ['historia', 'costa'], d: 'Fachadas hanseáticas coloridas no Báltico, o museu da Segunda Guerra e as praias de Sopot ao lado.' },
          { n: 'Wrocław', wv: 'Wroclaw', tags: ['cidade', 'historia'], d: 'Cidade sobre ilhas, com mais de 100 pontes e centenas de estatuetas de anões escondidas pelas ruas.' },
          { n: 'Zakopane & Tatras', wv: 'Zakopane', tags: ['montanha', 'neve', 'termas'], d: 'A capital de inverno polonesa: arquitetura de madeira, trilhas nos Tatras e as termas geotérmicas mais bem servidas do país.' },
        ],
      },
      {
        slug: 'eslovaquia', nome: 'Eslováquia', bandeira: '🇸🇰', wv: 'Slovakia',
        tags: ['montanha', 'termas', 'historia'],
        resumo: 'Quase sempre ignorada, e por um bom motivo: Bratislava não segura uma viagem sozinha. O que vale é a montanha — os Altos Tatras são Alpes em versão compacta e barata — e uma rede termal densa.',
        quando: 'Jun–set pra trilha · dez–mar pra neve e termas',
        portas: [ { c: 'BTS', n: 'Bratislava', t: 'regional' }, { c: 'VIE', n: 'via Viena — ~1h de ônibus e muito melhor conectada', t: 'porta' } ],
        termas: 'Sim, é um dos países mais termais da Europa. Piešťany é a estância clássica, famosa pela lama sulfurosa; AquaCity Poprad e Bešeňová são complexos geotérmicos grandes, com piscinas ao ar livre olhando pros Tatras.',
        cidades: [
          { n: 'Bratislava', wv: 'Bratislava', tags: ['cidade', 'historia'], d: 'Centro pequeno e agradável, castelo no alto do Danúbio. Um dia basta — e fica a 1h de Viena.' },
          { n: 'Altos Tatras', wv: 'High Tatras', tags: ['montanha', 'neve'], d: 'A menor cordilheira alpina do mundo, com picos acima de 2.600 m, lagos glaciais e trilhas sinalizadas.' },
          { n: 'Piešťany', wv: 'Piestany', tags: ['termas'], d: 'Estância termal histórica numa ilha do rio Váh, conhecida pelas termas sulfurosas e banhos de lama.' },
          { n: 'Bešeňová & Poprad', wv: 'Poprad', tags: ['termas', 'montanha'], d: 'Parques termais geotérmicos ao pé dos Tatras — piscina quente ao ar livre com montanha nevada em volta.' },
          { n: 'Castelo de Spiš', wv: 'Spissky hrad', tags: ['historia'], d: 'Uma das maiores ruínas de castelo da Europa Central, UNESCO, dominando toda a planície.' },
          { n: 'Košice', wv: 'Kosice', tags: ['historia', 'cidade'], d: 'Segunda cidade do país, com a catedral gótica mais oriental da Europa e um centro histórico bem preservado.' },
        ],
      },
      {
        slug: 'eslovenia', nome: 'Eslovênia', bandeira: '🇸🇮', wv: 'Slovenia',
        tags: ['natureza', 'montanha', 'termas', 'praia'],
        resumo: 'O país mais eficiente da Europa em experiência por quilômetro: Alpes, caverna, rio turquesa, costa veneziana e termas — tudo a menos de 2h de carro um do outro. Ideal como bloco de natureza entre duas cidades grandes.',
        quando: 'Mai–set · dez–mar pra neve e termas',
        portas: [ { c: 'LJU', n: 'Liubliana', t: 'regional' }, { c: 'VCE', n: 'via Veneza — ~3h de carro', t: 'porta' }, { c: 'ZAG', n: 'via Zagreb — ~2h', t: 'regional' } ],
        termas: 'Sim, e é tradição nacional — o país tem mais de uma dezena de estâncias termais naturais. Terme Čatež é a maior, com "riviera" termal ao ar livre aberta o ano todo; Rogaška Slatina é a histórica, ligada à água mineral Donat Mg; e Terme Ptuj fica na cidade mais antiga do país.',
        cidades: [
          { n: 'Liubliana', wv: 'Ljubljana', tags: ['cidade'], d: 'Capital minúscula, sem carros no centro, com o rio cortando por baixo de pontes do Plečnik. Dá pra ver em um dia — e é agradável demais.' },
          { n: 'Lago Bled', wv: 'Bled', tags: ['natureza'], d: 'Ilha com igreja no meio do lago, castelo na falésia e Alpes de fundo. Alugue um barco a remo ou o pletna tradicional.' },
          { n: 'Lago Bohinj & Triglav', wv: 'Bohinj', tags: ['natureza', 'montanha'], d: 'Maior, mais selvagem e muito menos turístico que Bled. Porta do Parque Nacional Triglav.' },
          { n: 'Vale do Soča', wv: 'Soca Valley', tags: ['natureza', 'montanha'], d: 'Rio de um turquesa quase artificial, rafting e canyoning, mais a história da Frente Isonzo na Primeira Guerra.' },
          { n: 'Cavernas de Postojna & Škocjan', wv: 'Postojna', tags: ['natureza'], d: 'Postojna se percorre de trenzinho subterrâneo; Škocjan (UNESCO) tem um cânion dentro da montanha.' },
          { n: 'Piran', wv: 'Piran', tags: ['praia', 'historia'], d: 'Os 46 km de costa eslovena, com uma cidade veneziana intacta na ponta. Parece Itália.' },
          { n: 'Terme Čatež', wv: 'Catez ob Savi', tags: ['termas'], d: 'O maior complexo termal do país, com piscinas quentes ao ar livre também no inverno.' },
        ],
      },
      {
        slug: 'romenia', nome: 'Romênia', bandeira: '🇷🇴', wv: 'Romania',
        tags: ['historia', 'montanha', 'natureza', 'roadtrip', 'termas'],
        resumo: 'Um dos melhores road trips da Europa, e ainda pouco explorado. Castelo na Transilvânia, cidades saxãs medievais, estradas alpinas espetaculares e um delta que não se parece com nada mais no continente.',
        quando: 'Mai–set · a Transfăgărășan só abre por volta de jun–out',
        portas: [ { c: 'OTP', n: 'Bucareste Otopeni', t: 'porta' }, { c: 'CLJ', n: 'Cluj-Napoca', t: 'regional' }, { c: 'TSR', n: 'Timișoara', t: 'regional' } ],
        termas: 'Sim, com herança romana — "Herculane" vem daí. Băile Herculane é uma estância imperial parcialmente em ruínas, decadente e fotogênica, com banhos termais ainda em funcionamento; Băile Felix é a mais estruturada; e Therme București, perto do aeroporto, é um complexo gigante alimentado por poço geotérmico — ótimo pra emendar num dia de conexão.',
        cidades: [
          { n: 'Brașov', wv: 'Brasov', tags: ['historia', 'montanha'], d: 'Cidade saxã com praça enorme e montanha colada. Base pro castelo de Bran e pro Peleș, que é bem mais bonito.' },
          { n: 'Sibiu', wv: 'Sibiu', tags: ['historia', 'cidade'], d: 'Centro medieval com as "casas de olhos" nos telhados e uma cena cultural forte.' },
          { n: 'Sighișoara', wv: 'Sighisoara', tags: ['historia'], d: 'Uma das poucas cidadelas medievais da Europa ainda habitadas. UNESCO.' },
          { n: 'Transfăgărășan', wv: 'Transfagarasan', tags: ['roadtrip', 'montanha'], d: 'Estrada alpina de curvas fechadas até 2.000 m, com o lago Bâlea no topo. Fecha com a neve.' },
          { n: 'Bucareste', wv: 'Bucharest', tags: ['cidade', 'historia'], d: 'Contrastes duros: Palácio do Parlamento (o segundo maior prédio do mundo), bairro velho e vida noturna barata.' },
          { n: 'Maramureș', wv: 'Maramures', tags: ['natureza', 'historia'], d: 'Vida rural quase intocada, igrejas de madeira UNESCO e o "cemitério alegre" de Săpânța.' },
          { n: 'Delta do Danúbio', wv: 'Danube Delta', tags: ['natureza'], d: 'Reserva da biosfera onde o rio se desmancha em canais. Se percorre de barco; centenas de espécies de aves.' },
          { n: 'Băile Herculane', wv: 'Baile Herculane', tags: ['termas', 'historia'], d: 'Termas usadas desde os romanos, com arquitetura austro-húngara em ruína controlada. Visual único.' },
        ],
      },
      {
        slug: 'bulgaria', nome: 'Bulgária', bandeira: '🇧🇬', wv: 'Bulgaria',
        tags: ['montanha', 'historia', 'praia', 'termas'],
        resumo: 'Provavelmente o país mais barato da União Europeia. Entrega montanha com ski acessível, uma das cidades mais antigas do continente, mosteiros e praia no Mar Negro.',
        quando: 'Mai–set pro geral · dez–mar pra ski em Bansko',
        portas: [ { c: 'SOF', n: 'Sófia', t: 'porta' }, { c: 'VAR', n: 'Varna', t: 'regional' }, { c: 'BOJ', n: 'Burgas', t: 'regional' } ],
        termas: 'Sim — a Bulgária é um dos países com mais fontes termais da Europa, mais de 500. Devin e Velingrad são as estâncias mais conhecidas; Sapareva Banya tem o gêiser mais quente dos Bálcãs, a mais de 100°C. É termalismo local e barato, não resort de luxo.',
        cidades: [
          { n: 'Sófia', wv: 'Sofia', tags: ['cidade', 'historia'], d: 'Catedral Alexander Nevsky, ruínas romanas embaixo das ruas e a montanha Vitosha logo atrás — ski a 30 min do centro.' },
          { n: 'Plovdiv', wv: 'Plovdiv', tags: ['historia', 'cidade'], d: 'Uma das cidades continuamente habitadas mais antigas da Europa, com teatro romano em uso e o bairro artístico de Kapana.' },
          { n: 'Mosteiro de Rila', wv: 'Rila Monastery', tags: ['historia', 'montanha'], d: 'UNESCO. Arcadas listradas e afrescos vivíssimos no meio da montanha, a ~2h de Sófia.' },
          { n: 'Bansko', wv: 'Bansko', tags: ['neve', 'montanha'], d: 'A principal estação de esqui do país, nas montanhas Pirin — das mais baratas da Europa.' },
          { n: 'Veliko Tarnovo', wv: 'Veliko Tarnovo', tags: ['historia'], d: 'Antiga capital medieval, com a fortaleza de Tsarevets pendurada sobre uma curva do rio.' },
          { n: 'Nessebar & Varna', wv: 'Nesebar', tags: ['praia', 'historia'], d: 'Península UNESCO com igrejas bizantinas no Mar Negro, e Varna com as praias e o tesouro de ouro mais antigo do mundo.' },
        ],
      },
      {
        slug: 'moldavia', nome: 'Moldávia', bandeira: '🇲🇩', wv: 'Moldova',
        tags: ['gastronomia', 'historia'],
        resumo: 'Um dos países menos visitados da Europa. Não tem paisagem espetacular nem cidade monumental — o que tem é vinho, e nisso é excepcional: as maiores adegas subterrâneas do mundo ficam aqui.',
        quando: 'Mai–out · outubro no Festival Nacional do Vinho',
        portas: [ { c: 'RMO', n: 'Chișinău (código antigo: KIV)', t: 'regional' } ],
        termas: null,
        cidades: [
          { n: 'Chișinău', wv: 'Chisinau', tags: ['cidade'], d: 'Capital arborizada, arquitetura soviética e preços baixíssimos. Base pra tudo — o país é pequeno.' },
          { n: 'Cricova', wv: 'Cricova', tags: ['gastronomia'], d: 'Cidade subterrânea de vinho: mais de 100 km de galerias em antiga mina de calcário, percorridas de carrinho.' },
          { n: 'Mileștii Mici', wv: 'Milestii Mici', tags: ['gastronomia'], d: 'Detém o recorde do Guinness da maior coleção de vinhos do mundo, com cerca de 2 milhões de garrafas.' },
          { n: 'Orheiul Vechi', wv: 'Orheiul Vechi', tags: ['historia', 'natureza'], d: 'Mosteiro escavado numa falésia calcária sobre o rio Răut. A paisagem mais bonita do país.' },
        ],
      },
      {
        slug: 'estonia', nome: 'Estônia', bandeira: '🇪🇪', wv: 'Estonia',
        tags: ['historia', 'cidade', 'natureza'],
        resumo: 'Tallinn tem uma das cidades medievais mais bem preservadas da Europa — e o país é o mais digitalizado do continente. Bloco báltico rende bem: os três países cabem numa semana de ônibus/carro.',
        quando: 'Jun–ago (o verão báltico é curto) · dez pelo mercado de Natal',
        portas: [ { c: 'TLL', n: 'Tallinn', t: 'regional' } ],
        termas: 'Não há fontes termais. Pärnu e Haapsalu têm cultura de spa e lama medicinal do Báltico, e a sauna é tradição forte, incluindo a sauna esfumaçada de Võromaa, que é patrimônio imaterial UNESCO. É outra coisa, não termas quentes.',
        cidades: [
          { n: 'Tallinn', wv: 'Tallinn', tags: ['historia', 'cidade'], d: 'Cidade velha murada, UNESCO, com torres e telhados vermelhos intactos. Balsa de 2h pra Helsinque.' },
          { n: 'Tartu', wv: 'Tartu', tags: ['cidade', 'historia'], d: 'Cidade universitária desde 1632, com cena cultural e boêmia desproporcional ao tamanho.' },
          { n: 'Parque Nacional de Lahemaa', wv: 'Lahemaa National Park', tags: ['natureza'], d: 'Floresta, turfeiras com passarelas de madeira, mansões bálticas e vilas de pescadores.' },
          { n: 'Saaremaa', wv: 'Saaremaa', tags: ['natureza', 'costa'], d: 'Maior ilha do país, com moinhos, o castelo de Kuressaare e a cratera de meteorito de Kaali.' },
          { n: 'Pärnu', wv: 'Parnu', tags: ['costa'], d: 'A "capital de verão": praia de areia rasa, casario de madeira e tradição de spa desde o século XIX.' },
        ],
      },
      {
        slug: 'letonia', nome: 'Letônia', bandeira: '🇱🇻', wv: 'Latvia',
        tags: ['cidade', 'historia', 'natureza'],
        resumo: 'Riga é o motivo. Tem a maior concentração de arquitetura Art Nouveau da Europa, e é a maior e mais viva das três capitais bálticas.',
        quando: 'Jun–ago',
        portas: [ { c: 'RIX', n: 'Riga', t: 'regional' } ],
        termas: null,
        cidades: [
          { n: 'Riga', wv: 'Riga', tags: ['cidade', 'historia'], d: 'Centro histórico UNESCO e o bairro Art Nouveau da rua Alberta, com fachadas cheias de rostos e figuras. Mercado central dentro de antigos hangares de zepelim.' },
          { n: 'Sigulda & Parque Gauja', wv: 'Sigulda', tags: ['natureza', 'historia'], d: 'Vale do rio Gauja com castelos (Turaida), cavernas de arenito e teleférico sobre o vale.' },
          { n: 'Jūrmala', wv: 'Jurmala', tags: ['costa'], d: 'Praia de 30 km e casas de madeira do século XIX, a 25 min de trem de Riga.' },
          { n: 'Kuldīga', wv: 'Kuldiga', tags: ['natureza', 'historia'], d: 'Cidade de madeira UNESCO com a Ventas rumba, a cachoeira mais larga da Europa (mas com apenas 2 m de queda).' },
        ],
      },
      {
        slug: 'lituania', nome: 'Lituânia', bandeira: '🇱🇹', wv: 'Lithuania',
        tags: ['historia', 'natureza', 'cidade'],
        resumo: 'O mais barroco dos bálticos, e o que tem a paisagem mais distinta: as dunas gigantes do Istmo da Curônia. Vilnius é a menos turística das três capitais.',
        quando: 'Jun–ago',
        portas: [ { c: 'VNO', n: 'Vilnius', t: 'regional' }, { c: 'KUN', n: 'Kaunas', t: 'regional' } ],
        termas: 'Não termal quente. Druskininkai é a estância clássica do país, com águas minerais e lama — categoria spa báltico, não fonte termal.',
        cidades: [
          { n: 'Vilnius', wv: 'Vilnius', tags: ['historia', 'cidade'], d: 'Um dos maiores centros barrocos da Europa Oriental (UNESCO), com a república autoproclamada de artistas de Užupis dentro dele.' },
          { n: 'Trakai', wv: 'Trakai', tags: ['historia', 'natureza'], d: 'Castelo de tijolo vermelho numa ilha no lago, a 30 min de Vilnius. Bate-volta clássico.' },
          { n: 'Kaunas', wv: 'Kaunas', tags: ['cidade', 'historia'], d: 'Capital entre as guerras, com um acervo de arquitetura modernista dos anos 1920–30 reconhecido pela UNESCO.' },
          { n: 'Istmo da Curônia (Nida)', wv: 'Curonian Spit', tags: ['natureza', 'costa'], d: 'Faixa de areia de 98 km entre lagoa e mar, com dunas altíssimas e florestas de pinheiro. UNESCO.' },
          { n: 'Colina das Cruzes', wv: 'Hill of Crosses', tags: ['historia'], d: 'Centenas de milhares de cruzes acumuladas desde o século XIX, símbolo de resistência à ocupação soviética.' },
        ],
      },
    ],
  },
  {
    id: 'balcas',
    nome: 'Bálcãs & Mediterrâneo Oriental',
    emoji: '🏝️',
    resumo: 'Onde o Mediterrâneo ainda sai barato. Costa adriática, montanha selvagem, cidades otomanas e uma história recente muito diferente do resto do continente. É a região que mais mudou de patamar turístico na última década.',
    paises: [
      {
        slug: 'croacia', nome: 'Croácia', bandeira: '🇭🇷', wv: 'Croatia',
        tags: ['praia', 'historia', 'natureza'],
        resumo: 'A costa mais bonita do Adriático, com mais de mil ilhas e cidades romanas/venezianas em cima do mar. Já não é barata como era, mas ainda ganha da Itália no custo.',
        quando: 'Mai–jun e set (jul–ago é caro e lotado)',
        portas: [ { c: 'ZAG', n: 'Zagreb', t: 'regional' }, { c: 'SPU', n: 'Split', t: 'regional' }, { c: 'DBV', n: 'Dubrovnik', t: 'regional' }, { c: 'PUY', n: 'Pula (Ístria)', t: 'regional' } ],
        termas: null,
        cidades: [
          { n: 'Dubrovnik', wv: 'Dubrovnik', tags: ['historia', 'praia'], d: 'Cidade murada sobre o mar, UNESCO. A volta pelas muralhas é obrigatória — faça na primeira hora do dia.' },
          { n: 'Split', wv: 'Split', tags: ['historia', 'praia'], d: 'A cidade velha é literalmente o palácio de Diocleciano, com gente morando dentro há 1.700 anos.' },
          { n: 'Hvar & Vis', wv: 'Hvar', tags: ['praia'], d: 'Hvar é a ilha de praia e vida noturna; Vis, mais distante, é a rústica e tranquila, com a Caverna Azul ao lado.' },
          { n: 'Zadar', wv: 'Zadar', tags: ['cidade', 'praia'], d: 'Órgão do Mar tocado pelas ondas e o Cumprimento ao Sol. Base pros parques de Krka e Paklenica.' },
          { n: 'Plitvice', wv: 'Plitvice Lakes National Park', tags: ['natureza'], d: '16 lagos turquesa ligados por cascatas, percorridos em passarelas de madeira. UNESCO. Ingresso com horário marcado.' },
          { n: 'Ístria (Rovinj & Motovun)', wv: 'Istria', tags: ['gastronomia', 'praia'], d: 'A parte "italiana" da Croácia: trufa branca, azeite, vinho e vilas venezianas em colinas.' },
          { n: 'Zagreb', wv: 'Zagreb', tags: ['cidade'], d: 'Capital austro-húngara com cafés na rua e museus excêntricos. Costuma ser pulada — e não devia.' },
        ],
      },
      {
        slug: 'bosnia', nome: 'Bósnia e Herzegovina', bandeira: '🇧🇦', wv: 'Bosnia and Herzegovina',
        tags: ['historia', 'natureza', 'cidade'],
        resumo: 'A experiência mais distinta dos Bálcãs: é onde o Império Otomano e a Europa central se encontram fisicamente, numa mesma rua. História recente muito presente e preços entre os mais baixos do continente.',
        quando: 'Mai–out',
        portas: [ { c: 'SJJ', n: 'Sarajevo', t: 'regional' }, { c: 'DBV', n: 'via Dubrovnik — ~3h até Mostar', t: 'regional' } ],
        termas: 'Existe, em escala local: Ilidža, nos arredores de Sarajevo, e Fojnica têm fontes termais usadas desde a época romana e otomana. É balneário de bairro, não destino termal.',
        cidades: [
          { n: 'Sarajevo', wv: 'Sarajevo', tags: ['historia', 'cidade'], d: 'Baščaršija otomana, catedral, sinagoga e mesquita em quarteirões vizinhos. Museu do Túnel e as marcas do cerco dos anos 90.' },
          { n: 'Mostar', wv: 'Mostar', tags: ['historia'], d: 'Stari Most, a ponte otomana reconstruída após a guerra, UNESCO. Durma lá: de dia é excursão pura.' },
          { n: 'Blagaj', wv: 'Blagaj', tags: ['natureza', 'historia'], d: 'Uma teqia dervixe branca encostada num paredão, exatamente onde o rio Buna brota da rocha.' },
          { n: 'Kravice', wv: 'Kravice', tags: ['natureza'], d: 'Anfiteatro de cachoeiras onde dá pra nadar no verão, a ~40 min de Mostar.' },
          { n: 'Sutjeska & Una', wv: 'Sutjeska National Park', tags: ['natureza', 'montanha'], d: 'Sutjeska guarda Perućica, uma das últimas florestas primárias da Europa; o Una é rio de rafting e cascatas.' },
          { n: 'Trebinje', wv: 'Trebinje', tags: ['gastronomia', 'cidade'], d: 'Cidade pequena de vinho e platanos, a 30 min de Dubrovnik. Emenda perfeita e muito mais barata.' },
        ],
      },
      {
        slug: 'montenegro', nome: 'Montenegro', bandeira: '🇲🇪', wv: 'Montenegro',
        tags: ['costa', 'montanha', 'roadtrip'],
        resumo: 'Mar e montanha alta a 1h de distância um do outro, num país do tamanho de uma região. É o melhor road trip curto da Europa — em 5 dias você atravessa fiorde, cânion e praia.',
        quando: 'Mai–jun e set–out',
        portas: [ { c: 'TIV', n: 'Tivat (baía de Kotor)', t: 'regional' }, { c: 'TGD', n: 'Podgorica', t: 'regional' }, { c: 'DBV', n: 'via Dubrovnik — ~2h até Kotor', t: 'regional' } ],
        termas: null,
        cidades: [
          { n: 'Kotor', wv: 'Kotor', tags: ['historia', 'costa'], d: 'Cidade medieval murada no fundo de uma baía que parece fiorde. Suba os 1.350 degraus da muralha ao amanhecer.' },
          { n: 'Perast', wv: 'Perast', tags: ['historia', 'costa'], d: 'Vila barroca de pedra na baía, com a ilha artificial de Nossa Senhora das Rochas em frente.' },
          { n: 'Budva', wv: 'Budva', tags: ['praia'], d: 'A capital de praia e balada do país, com uma cidade velha murada no meio.' },
          { n: 'Sveti Stefan', wv: 'Sveti Stefan', tags: ['costa'], d: 'A ilhota-vila mais fotografada do Adriático, ligada por um istmo de areia. Acesso à ilha em si é restrito.' },
          { n: 'Durmitor & Cânion do Tara', wv: 'Durmitor National Park', tags: ['montanha', 'natureza'], d: 'Parque UNESCO com lagos glaciais e o segundo cânion mais profundo do mundo. Rafting no Tara.' },
          { n: 'Lovćen', wv: 'Lovcen National Park', tags: ['roadtrip', 'montanha'], d: 'A estrada de 25 curvas fechadas subindo de Kotor, com o mausoléu de Njegoš no alto. Uma das dirigidas mais bonitas da Europa.' },
          { n: 'Lago Skadar', wv: 'Lake Skadar', tags: ['natureza'], d: 'Maior lago dos Bálcãs, com nenúfares, aves e vinícolas na margem.' },
        ],
      },
      {
        slug: 'albania', nome: 'Albânia', bandeira: '🇦🇱', wv: 'Albania',
        tags: ['praia', 'montanha', 'historia', 'termas'],
        resumo: 'O melhor custo-benefício da Europa hoje. Praia de água transparente com preço de Bálcã, cidades otomanas UNESCO, Alpes selvagens e uma história de isolamento comunista que não se repete em lugar nenhum.',
        quando: 'Mai–jun e set pra costa · jun–set pra montanha',
        portas: [ { c: 'TIA', n: 'Tirana', t: 'regional' } ],
        termas: 'Sim, e é bem rústica: as termas de Bënjë, perto de Përmet, são piscinas naturais de água quente junto a uma ponte otomana e a um cânion. Não tem estrutura de resort — é banho ao ar livre no meio do nada, e justamente por isso vale.',
        cidades: [
          { n: 'Tirana', wv: 'Tirana', tags: ['cidade', 'historia'], d: 'Prédios pintados de cores fortes, os bunkers-museu Bunk\'Art e a pirâmide de Enver Hoxha reformada. Cafés e preços baixos.' },
          { n: 'Berat', wv: 'Berat', tags: ['historia'], d: 'A "cidade das mil janelas": casario otomano branco empilhado na encosta, com cidadela ainda habitada. UNESCO.' },
          { n: 'Gjirokastër', wv: 'Gjirokaster', tags: ['historia'], d: 'Cidade de pedra UNESCO, com casas-torre e uma fortaleza enorme sobre o vale.' },
          { n: 'Riviera Albanesa & Passo de Llogara', wv: 'Albanian Riviera', tags: ['roadtrip', 'costa'], d: 'A estrada que amarra o litoral sul: desce de 1.000 m no passo de Llogara direto pro mar, com mirantes o caminho todo. É o trecho de carro que vale por si só.' },
          { n: 'Dhërmi', wv: 'Dhermi', tags: ['praia'], d: 'A praia mais conhecida da riviera — seixo branco, água transparente e beach clubs. A vila velha fica encosta acima, bem mais calma. Gjipe, com cânion e praia isolada, fica ao lado.' },
          { n: 'Himarë', wv: 'Himare', tags: ['praia', 'cidade'], d: 'Base mais estruturada da riviera, com várias praias em volta (Livadhi, Potami, Jale) e um castelo na vila antiga, no alto. Boa pra ficar alguns dias em vez de só passar.' },
          { n: 'Sarandë', wv: 'Sarande', tags: ['praia', 'cidade'], d: 'A cidade grande do sul, com calçadão e vida noturna, e o ponto de partida pra tudo por ali. Balsa pra Corfu em ~30 min — emenda direta com a Grécia.' },
          { n: 'Ksamil & Butrint', wv: 'Ksamil', tags: ['praia', 'historia'], d: 'Ilhotas a poucos metros da praia e a água mais clara do país, de frente pra Corfu. Butrint, sítio greco-romano UNESCO, fica a 15 min; o Olho Azul (Syri i Kaltër) um pouco mais adiante.' },
          { n: 'Theth & Valbona', wv: 'Theth', tags: ['montanha', 'natureza'], d: 'Alpes Albaneses. A travessia a pé entre os dois vales é uma das melhores trilhas de um dia da Europa.' },
          { n: 'Lago Koman', wv: 'Koman', tags: ['natureza'], d: 'Travessia de ferry de 3h por um desfiladeiro alagado, comparada a fiordes. É transporte local, não passeio turístico.' },
          { n: 'Bënjë & Përmet', wv: 'Permet', tags: ['termas', 'natureza'], d: 'Piscinas termais naturais no cânion do Lengarica, ao lado de uma ponte otomana.' },
        ],
      },
      {
        slug: 'servia', nome: 'Sérvia', bandeira: '🇷🇸', wv: 'Serbia',
        tags: ['cidade', 'gastronomia', 'natureza'],
        resumo: 'Não é país de paisagem — é de cidade e de gente. Belgrado tem uma das vidas noturnas mais intensas da Europa e preços baixos. Bom como parada de 2–3 dias dentro de um circuito balcânico.',
        quando: 'Abr–out · julho no EXIT, em Novi Sad',
        portas: [ { c: 'BEG', n: 'Belgrado', t: 'porta' } ],
        termas: 'Sim, no formato "banja" (balneário local). Vrnjačka Banja é a mais famosa e movimentada; Niška Banja e Sokobanja completam. São estâncias tradicionais frequentadas por sérvios, com preço baixo e pouca infra turística internacional.',
        cidades: [
          { n: 'Belgrado', wv: 'Belgrade', tags: ['cidade', 'gastronomia'], d: 'Fortaleza de Kalemegdan no encontro do Sava com o Danúbio, bairro boêmio de Skadarlija e os splavovi — baladas em balsas no rio.' },
          { n: 'Novi Sad', wv: 'Novi Sad', tags: ['cidade', 'historia'], d: 'Fortaleza de Petrovaradin sobre o Danúbio, onde acontece o festival EXIT. Centro austro-húngaro tranquilo.' },
          { n: 'Parque Nacional Tara & Drvengrad', wv: 'Tara National Park', tags: ['natureza'], d: 'Floresta e desfiladeiro do Drina, mais a vila de madeira construída pelo Kusturica e o trem Šargan Eight.' },
          { n: 'Đavolja Varoš', wv: 'Djavolja Varos', tags: ['natureza'], d: '"Cidade do Diabo": 200 torres de erosão com pedras equilibradas no topo.' },
          { n: 'Vrnjačka Banja', wv: 'Vrnjacka Banja', tags: ['termas'], d: 'A estância termal mais tradicional do país, com fontes usadas desde a época romana.' },
        ],
      },
      {
        slug: 'kosovo', nome: 'Kosovo', bandeira: '🇽🇰', wv: 'Kosovo',
        tags: ['historia', 'montanha'],
        resumo: 'O país mais jovem da Europa e um dos menos visitados. Vale como complemento de um circuito balcânico, principalmente por Prizren e pelas montanhas do oeste. População muito jovem e preços baixíssimos.',
        quando: 'Mai–out',
        portas: [ { c: 'PRN', n: 'Pristina', t: 'regional' } ],
        termas: null,
        aviso: 'Atenção à ordem de entrada: a Sérvia não reconhece os carimbos do Kosovo e pode recusar a entrada de quem chegou ao Kosovo por um terceiro país e tenta entrar na Sérvia por lá. Entrar pela Sérvia e voltar pela Sérvia costuma ser o caminho seguro — confirme as regras vigentes antes de montar o trecho.',
        cidades: [
          { n: 'Prizren', wv: 'Prizren', tags: ['historia', 'cidade'], d: 'A cidade mais bonita do país: ponte otomana, mesquitas, fortaleza no alto e um rio cortando o centro.' },
          { n: 'Pristina', wv: 'Pristina', tags: ['cidade'], d: 'Capital jovem e caótica, com a Biblioteca Nacional (uma das construções mais estranhas da Europa) e cafés por toda parte.' },
          { n: 'Vale do Rugova & Peja', wv: 'Peja', tags: ['montanha', 'natureza'], d: 'Desfiladeiro nas Bjeshkët e Nemuna ("Montanhas Amaldiçoadas"), com trilhas, tirolesa e o Patriarcado de Peć.' },
          { n: 'Mosteiro de Visoki Dečani', wv: 'Decani', tags: ['historia'], d: 'Mosteiro sérvio-ortodoxo do século XIV, UNESCO, com afrescos excepcionais — visitação sujeita a controle de segurança.' },
        ],
      },
      {
        slug: 'macedonia-do-norte', nome: 'Macedônia do Norte', bandeira: '🇲🇰', wv: 'North Macedonia',
        tags: ['natureza', 'historia', 'montanha'],
        resumo: 'Pequena e barata, com um trunfo forte: o lago Ohrid, que é patrimônio natural e cultural da UNESCO ao mesmo tempo — coisa rara no mundo.',
        quando: 'Mai–set',
        portas: [ { c: 'SKP', n: 'Skopje', t: 'regional' }, { c: 'OHD', n: 'Ohrid', t: 'regional' } ],
        termas: null,
        cidades: [
          { n: 'Ohrid', wv: 'Ohrid', tags: ['natureza', 'historia'], d: 'Um dos lagos mais antigos do mundo, com igrejas bizantinas na falésia e teatro antigo. Praia de água doce no verão.' },
          { n: 'Skopje', wv: 'Skopje', tags: ['cidade', 'historia'], d: 'Bazar otomano de um lado do rio e, do outro, dezenas de estátuas monumentais do projeto "Skopje 2014" — polêmico e inesquecível.' },
          { n: 'Cânion Matka', wv: 'Matka Canyon', tags: ['natureza'], d: 'A 30 min de Skopje: caiaque, cavernas e mosteiros pendurados no paredão.' },
          { n: 'Mavrovo', wv: 'Mavrovo', tags: ['montanha', 'neve'], d: 'Maior parque nacional do país, com a igreja submersa do lago e a principal estação de esqui.' },
          { n: 'Bitola', wv: 'Bitola', tags: ['historia', 'cidade'], d: 'Cidade consular do fim do Império Otomano, com a rua Širok Sokak e as ruínas de Heraclea Lyncestis.' },
        ],
      },
      {
        slug: 'grecia', nome: 'Grécia', bandeira: '🇬🇷', wv: 'Greece',
        tags: ['praia', 'historia', 'gastronomia', 'termas'],
        resumo: 'Ilha e Antiguidade. Ponto importante de planejamento: as ilhas são muito diferentes entre si — Cíclades são brancas e secas, as Jônicas são verdes, Creta é quase um país. Não faça duas parecidas seguidas.',
        quando: 'Mai–jun e set–out · muitas ilhas fecham serviços no inverno',
        portas: [ { c: 'ATH', n: 'Atenas', t: 'porta' }, { c: 'SKG', n: 'Tessalônica', t: 'regional' }, { c: 'HER', n: 'Heraklion (Creta)', t: 'regional' }, { c: 'JTR', n: 'Santorini', t: 'regional' }, { c: 'RHO', n: 'Rodes', t: 'regional' } ],
        termas: 'Sim, e é antiga: Loutrá Edipsoú, na ilha de Evia, é uma das estâncias termais mais antigas em uso contínuo do mundo — há fontes quentes caindo direto no mar, de graça, na beira da estrada. Loutrá Pozar, no norte, tem piscinas naturais no meio de um desfiladeiro.',
        cidades: [
          { n: 'Atenas', wv: 'Athens', tags: ['historia', 'cidade'], d: 'Acrópole, Museu da Acrópole e Plaka. Duas noites bastam, e o rooftop com vista pro Partenon vale o preço.' },
          { n: 'Santorini', wv: 'Santorini', tags: ['praia', 'natureza'], d: 'A caldeira vulcânica com as vilas brancas na borda. Absurdamente cheia — durma em Oia ou Imerovigli e vá em maio ou outubro.' },
          { n: 'Creta', wv: 'Crete', tags: ['praia', 'costa', 'natureza', 'historia'], d: 'A ilha mais completa: palácio minoico de Knossos, garganta de Samaria, praias como Balos e Elafonissi, e cozinha própria.' },
          { n: 'Meteora', wv: 'Meteora', tags: ['natureza', 'historia'], d: 'Mosteiros do século XIV no topo de pilares de rocha. UNESCO, e a paisagem mais surreal do continente grego.' },
          { n: 'Rodes', wv: 'Rhodes', tags: ['historia', 'praia'], d: 'A maior cidade medieval habitada da Europa, murada pelos Cavaleiros de São João, com praia junto.' },
          { n: 'Corfu', wv: 'Corfu', tags: ['praia', 'costa', 'historia'], d: 'Jônica, verde e veneziana — arquitetura italiana, não cicládica. Boa emenda com a Albânia (ferry de 30 min pra Sarandë).' },
          { n: 'Naxos & Milos', wv: 'Naxos', tags: ['praia', 'gastronomia'], d: 'As Cíclades sem o preço de Santorini: Naxos tem praia grande e comida boa; Milos tem a paisagem lunar de Sarakiniko.' },
          { n: 'Peloponeso & Nafplio', wv: 'Nafplio', tags: ['historia', 'roadtrip'], d: 'Road trip com Micenas, Epidauro, Olímpia e Monemvasia, usando a cidade veneziana de Nafplio como base.' },
          { n: 'Tessalônica', wv: 'Thessaloniki', tags: ['gastronomia', 'cidade'], d: 'A capital gastronômica do país, com camadas romana, bizantina e otomana e vida noturna forte.' },
        ],
      },
    ],
  },
  {
    id: 'caucaso',
    nome: 'Transcontinentais & Cáucaso',
    emoji: '🕌',
    resumo: 'Tecnicamente na borda da Europa, e é justamente isso que os torna valiosos: entregam uma experiência que nenhum país da UE entrega. Vistos costumam ser fáceis pra brasileiros e o custo é baixo — mas confirme as regras vigentes antes de emitir.',
    paises: [
      {
        slug: 'turquia', nome: 'Turquia', bandeira: '🇹🇷', wv: 'Turkey',
        tags: ['historia', 'cidade', 'praia', 'termas', 'gastronomia'],
        resumo: 'O país mais diverso desta lista, e o mais estratégico: Istambul é um dos maiores hubs do mundo e permite stopover, o que na prática significa ganhar um destino inteiro dentro de um roteiro que já ia pra Europa.',
        quando: 'Abr–jun e set–out · Capadócia é bonita o ano todo, inclusive com neve',
        portas: [ { c: 'IST', n: 'Istambul', t: 'porta' }, { c: 'SAW', n: 'Istambul Sabiha Gökçen', t: 'regional' }, { c: 'AYT', n: 'Antalya', t: 'regional' }, { c: 'NAV', n: 'Nevşehir (Capadócia)', t: 'regional' }, { c: 'ASR', n: 'Kayseri (Capadócia)', t: 'regional' } ],
        termas: 'Sim, das mais impressionantes do mundo. Pamukkale são terraços brancos de travertino formados pela água termal escorrendo pela encosta, com as ruínas de Hierápolis em cima e a "Piscina de Cleópatra", onde se nada entre colunas romanas caídas. Bursa é a cidade termal otomana histórica, com banhos em funcionamento desde o século XIV no bairro de Çekirge. Fora isso, o hamam é cultura nacional.',
        cidades: [
          { n: 'Istambul', wv: 'Istanbul', tags: ['cidade', 'historia', 'gastronomia'], d: 'Santa Sofia, Mesquita Azul, Topkapı, Grande Bazar e o Bósforo separando dois continentes. Uma das cidades mais densas do mundo em coisa pra ver.' },
          { n: 'Capadócia', wv: 'Cappadocia', tags: ['natureza', 'historia'], d: 'Chaminés de fada, igrejas rupestres, cidades subterrâneas e os balões ao amanhecer. Reserve o balão com folga — voos são cancelados por vento.' },
          { n: 'Pamukkale & Hierápolis', wv: 'Pamukkale', tags: ['termas', 'historia'], d: 'O "castelo de algodão": piscinas naturais de travertino branco em degraus, com sítio greco-romano no topo.' },
          { n: 'Éfeso', wv: 'Ephesus', tags: ['historia'], d: 'Uma das cidades antigas mais bem preservadas do Mediterrâneo, com a Biblioteca de Celso e um teatro pra 25 mil pessoas.' },
          { n: 'Costa Turquesa (Fethiye & Ölüdeniz)', wv: 'Fethiye', tags: ['praia', 'natureza'], d: 'Lagoa azul, parapente do monte Babadağ, cruzeiros de goleta e a Lycian Way passando por perto.' },
          { n: 'Antalya', wv: 'Antalya', tags: ['praia', 'historia'], d: 'Cidade velha otomana sobre falésias, cachoeiras no meio urbano e a maior estrutura de resort do país.' },
          { n: 'Bursa', wv: 'Bursa', tags: ['termas', 'historia'], d: 'Primeira capital otomana, com banhos termais históricos e o Uludağ, principal estação de esqui da Turquia, logo acima.' },
          { n: 'Safranbolu', wv: 'Safranbolu', tags: ['historia'], d: 'Cidade otomana UNESCO com casario de madeira intacto — a melhor amostra de como eram essas cidades.' },
          { n: 'Monte Nemrut', wv: 'Mount Nemrut', tags: ['historia', 'montanha'], d: 'Cabeças colossais de pedra a 2.100 m, de um reino do século I a.C. Ver o nascer do sol lá é o ponto.' },
        ],
      },
      {
        slug: 'georgia', nome: 'Geórgia', bandeira: '🇬🇪', wv: 'Georgia (country)',
        tags: ['montanha', 'gastronomia', 'termas', 'historia'],
        resumo: 'O destino que mais surpreende quem vai. Cáucaso alto, vinho com 8.000 anos de método próprio, uma das melhores cozinhas do mundo e preços muito baixos. Brasileiros costumam ter entrada facilitada — confirme antes.',
        quando: 'Mai–jun e set–out · a alta montanha (Svaneti, Tusheti) só abre no verão',
        portas: [ { c: 'TBS', n: 'Tbilisi', t: 'regional' }, { c: 'KUT', n: 'Kutaisi (low cost)', t: 'regional' }, { c: 'BUS', n: 'Batumi', t: 'regional' } ],
        termas: 'Sim, e a capital nasceu por causa disso — "Tbilisi" vem de "tbili", quente. No bairro de Abanotubani, os banhos sulfurosos de cúpula de tijolo funcionam há séculos, com salas privativas alugadas por hora e massagem kisa. É uma das experiências termais mais autênticas da Europa. Borjomi, no interior, é a estância de água mineral famosa.',
        cidades: [
          { n: 'Tbilisi', wv: 'Tbilisi', tags: ['cidade', 'gastronomia', 'termas'], d: 'Cidade velha de varandas de madeira, banhos sulfurosos, fortaleza de Narikala e uma cena de restaurante e vinho muito boa.' },
          { n: 'Kazbegi (Stepantsminda)', wv: 'Stepantsminda', tags: ['montanha'], d: 'A igreja de Gergeti a 2.170 m com o monte Kazbek de 5.000 m atrás. Chega-se pela Estrada Militar Georgiana.' },
          { n: 'Kakheti & Signagi', wv: 'Sighnaghi', tags: ['gastronomia', 'historia'], d: 'Região de vinho onde nasceu o método qvevri, de ânforas enterradas — reconhecido pela UNESCO. Signagi é a vila murada com vista pro Cáucaso.' },
          { n: 'Svaneti (Mestia & Ushguli)', wv: 'Svaneti', tags: ['montanha', 'natureza'], d: 'Torres de pedra medievais em vales isolados; Ushguli é um dos povoados habitados mais altos da Europa.' },
          { n: 'Batumi', wv: 'Batumi', tags: ['costa', 'cidade'], d: 'Mar Negro com arquitetura excêntrica e cassinos. Subtropical, bem diferente do resto do país.' },
          { n: 'Vardzia', wv: 'Vardzia', tags: ['historia'], d: 'Cidade-mosteiro escavada numa falésia no século XII, com centenas de câmaras em vários níveis.' },
          { n: 'Borjomi', wv: 'Borjomi', tags: ['natureza', 'termas'], d: 'Parque nacional de floresta e a água mineral mais conhecida da ex-URSS, que se bebe direto na fonte.' },
        ],
      },
      {
        slug: 'armenia', nome: 'Armênia', bandeira: '🇦🇲', wv: 'Armenia',
        tags: ['historia', 'montanha', 'natureza'],
        resumo: 'Primeiro Estado a adotar o cristianismo, com mosteiros do século IV em desfiladeiros. Combina naturalmente com a Geórgia — são 5–6h de estrada entre as capitais.',
        quando: 'Mai–jun e set–out',
        portas: [ { c: 'EVN', n: 'Yerevan', t: 'regional' } ],
        termas: 'Em escala pequena: Jermuk é a estância termal e de água mineral do país, com fontes quentes e uma cascata. Não é destino termal internacional.',
        cidades: [
          { n: 'Yerevan', wv: 'Yerevan', tags: ['cidade', 'gastronomia'], d: 'Cidade rosada de tufo vulcânico, com a escadaria Cascade, Praça da República e o memorial do genocídio.' },
          { n: 'Garni & Geghard', wv: 'Geghard', tags: ['historia'], d: 'Um templo helenístico do século I ao lado de um mosteiro parcialmente escavado na rocha (UNESCO), num desfiladeiro de colunas de basalto.' },
          { n: 'Tatev', wv: 'Tatev', tags: ['historia', 'montanha'], d: 'Mosteiro do século IX na borda de um cânion, alcançado pelo teleférico "Asas de Tatev", um dos mais longos do mundo.' },
          { n: 'Lago Sevan', wv: 'Lake Sevan', tags: ['natureza'], d: 'Um dos maiores lagos de altitude do mundo, a 1.900 m, com o mosteiro de Sevanavank na península.' },
          { n: 'Dilijan', wv: 'Dilijan', tags: ['natureza', 'montanha'], d: 'Apelidada de "Suíça armênia": floresta densa, trilhas e mosteiros escondidos como Haghartsin.' },
          { n: 'Khor Virap', wv: 'Khor Virap', tags: ['historia'], d: 'Mosteiro na fronteira com a Turquia, com a vista mais clássica do monte Ararat.' },
        ],
      },
      {
        slug: 'azerbaijao', nome: 'Azerbaijão', bandeira: '🇦🇿', wv: 'Azerbaijan',
        tags: ['cidade', 'historia', 'natureza'],
        resumo: 'O mais "petrodólar" do Cáucaso: Baku mistura cidade murada medieval com arquitetura contemporânea de assinatura. Fora da capital, aparecem vulcões de lama e vilarejos de montanha. Requer visto — confirme o processo antes.',
        quando: 'Abr–jun e set–out',
        portas: [ { c: 'GYD', n: 'Baku', t: 'regional' } ],
        termas: 'Não no sentido usual. A curiosidade local é Naftalan, onde se tomam banhos de petróleo bruto por suposto efeito terapêutico. É outra categoria — e não substitui uma terma.',
        cidades: [
          { n: 'Baku', wv: 'Baku', tags: ['cidade', 'historia'], d: 'Icherisheher, a cidade murada UNESCO com a Torre da Donzela, contrastando com as Flame Towers e o Centro Heydar Aliyev da Zaha Hadid.' },
          { n: 'Gobustan', wv: 'Gobustan', tags: ['historia', 'natureza'], d: 'Petróglifos de até 40.000 anos (UNESCO) e, ao lado, um campo com centenas de vulcões de lama borbulhando.' },
          { n: 'Sheki', wv: 'Sheki', tags: ['historia'], d: 'Palácio dos Khans com vitrais de shebeke montados sem cola nem prego, e um caravançarai que virou hotel.' },
          { n: 'Gabala & Guba', wv: 'Gabala', tags: ['montanha', 'natureza'], d: 'Sopé do Grande Cáucaso: teleférico, cachoeiras e a vila de Khinalug, a 2.300 m, uma das mais altas e antigas da região.' },
          { n: 'Yanar Dag', wv: 'Yanar Dag', tags: ['natureza'], d: 'Encosta onde o gás natural que escapa do solo queima sem parar há séculos — origem do apelido "terra do fogo".' },
        ],
      },
    ],
  },
];

const EUROPA_FORA = {
  titulo: 'Hoje não entram no planejamento',
  texto: 'Rússia, Belarus e Ucrânia têm patrimônio cultural enorme — São Petersburgo e Kyiv estariam entre os destaques do continente em qualquer lista. Mas, no momento, não são destinos de viagem convencional: guerra ativa na Ucrânia, restrições de segurança e de acesso, e espaço aéreo fechado para a maioria das companhias ocidentais, o que também encarece e alonga rotas entre Europa e Ásia. Não faz sentido tratá-los como opção de roteiro enquanto esse quadro não mudar.',
  paises: [
    { bandeira: '🇺🇦', nome: 'Ucrânia' },
    { bandeira: '🇷🇺', nome: 'Rússia' },
    { bandeira: '🇧🇾', nome: 'Belarus' },
  ],
};
