window.POSES = {
  categorias: [
    {
      id: 'genericas',
      emoji: '✨',
      nome: 'Serve em qualquer lugar',
      resumo: 'Poses que não dependem do cenário — só de um apoio na altura do quadril, uma parede lisa ou um fundo com textura. São as que valem decorar, porque funcionam na primeira esquina tanto quanto num mirante.',
      poses: [
        { img: 'maos-atras-das-costas-olhar-por-cima-do-ombro.jpeg', nome: 'Mãos atrás das costas, olhar por cima do ombro' },
        { img: 'encostada-na-cerca-olhando-pro-lado.jpeg', nome: 'Encostada na cerca, olhando pro lado' },
        { img: 'perfil-torcido-maos-no-quadril.jpeg', nome: 'Perfil torcido com as mãos no quadril' },
        { img: 'perfil-com-as-maos-juntas-atras.jpeg', nome: 'Perfil com as mãos juntas atrás' },
        { img: 'de-frente-no-muro-branco-maos-ocupadas.jpeg', nome: 'De frente no muro branco, mãos ocupadas' },
        { img: 'de-costas-na-luz-dourada-mao-no-cabelo.jpeg', nome: 'De costas na luz dourada, mão no cabelo' },
        { img: 'perna-dobrada-com-a-mao-no-cabelo.jpeg', nome: 'Perna dobrada com a mão no cabelo' },
        { img: 'braco-acima-da-cabeca-mao-no-cos.jpeg', nome: 'Braço acima da cabeça, mão no cós' },
        { img: 'agachada-na-parede-com-a-mao-na-cabeca.jpeg', nome: 'Agachada na parede com a mão na cabeça' },
      ],
    },
    {
      id: 'praia',
      emoji: '🏖️',
      nome: 'Praia',
      resumo: 'Areia, mar e sol duro. A regra que atravessa quase todas: ou o sol está baixo, ou você precisa de algo que resolva o franzir de olho — óculos, boné, um objeto na frente do rosto, ou olhos fechados de propósito.',
      poses: [
        { img: 'vento-no-cabelo-contra-o-ceu.jpeg', nome: 'Vento no cabelo contra o céu' },
        { img: 'bracos-no-cabelo-olhar-por-cima-do-ombro.jpeg', nome: 'Braços no cabelo, olhar por cima do ombro' },
        { img: 'espreguicadeira-com-drink.jpeg', nome: 'Espreguiçadeira com drink' },
        { img: 'agachada-na-areia-olhando-pra-cima.jpeg', nome: 'Agachada na areia, olhando pra cima' },
        { img: 'de-costas-olhar-por-cima-do-ombro.jpeg', nome: 'De costas, olhar por cima do ombro' },
        { img: 'maos-no-rosto-de-cima-na-areia.jpeg', nome: 'Mãos no rosto, de cima na areia' },
        { img: 'de-costas-na-beira-queixo-pra-cima.jpeg', nome: 'De costas na beira, queixo pra cima' },
        { img: 'camisetao-e-bone-andando-na-agua.jpeg', nome: 'Camisetão e boné, andando na água' },
        { img: 'fotografando-o-por-do-sol.jpeg', nome: 'Fotografando o pôr do sol' },
        { img: 'sentada-de-lado-com-o-mar-atras.jpeg', nome: 'Sentada de lado com o mar atrás' },
        { img: 'deitada-de-brucos-na-canga.jpeg', nome: 'Deitada de bruços na canga' },
        { img: 'agua-de-coco-de-pernas-cruzadas.jpeg', nome: 'Água de coco de pernas cruzadas' },
        { img: 'cabelo-molhado-na-toalha.jpeg', nome: 'Cabelo molhado na toalha' },
        { img: 'andando-de-saia-com-a-mao-no-cabelo.jpeg', nome: 'Andando de saia com a mão no cabelo' },
        { img: 'encostada-na-cerca-pernas-cruzadas.jpeg', nome: 'Encostada na cerca, pernas cruzadas' },
        { img: 'arco-pra-tras-sentada-na-canga.jpeg', nome: 'Arco pra trás sentada na canga' },
        { img: 'bracos-abertos-no-corrimao.jpeg', nome: 'Braços abertos no corrimão' },
        { img: 'agachada-de-costas-com-flor-no-cabelo.jpeg', nome: 'Agachada de costas com flor no cabelo' },
        { img: 'vestido-longo-no-fim-do-por-do-sol.jpeg', nome: 'Vestido longo no fim do pôr do sol' },
        { img: 'maos-emoldurando-o-rosto-na-agua.jpeg', nome: 'Mãos emoldurando o rosto na água' },
        { img: 'mao-na-nuca-contra-o-sol.jpeg', nome: 'Mão na nuca contra o sol' },
        { img: 'reclinada-na-areia-na-hora-azul.jpeg', nome: 'Reclinada na areia na hora azul' },
        { img: 'bone-cobrindo-os-olhos-mao-no-rosto.jpeg', nome: 'Boné cobrindo os olhos, mão no rosto' },
        { img: 'mao-cobrindo-um-olho-rindo.jpeg', nome: 'Mão cobrindo um olho, rindo' },
        { img: 'reclinada-mexendo-nos-oculos.jpeg', nome: 'Reclinada mexendo nos óculos' },
        { img: 'de-brucos-mexendo-na-camera.jpeg', nome: 'De bruços mexendo na câmera' },
        { img: 'livro-na-canga-foto-do-colo.jpeg', nome: 'Livro na canga, foto do próprio colo' },
        { img: 'mao-sustentando-o-rosto-na-areia.jpeg', nome: 'Mão sustentando o rosto na areia' },
        { img: 'sentada-de-camisa-cabeca-inclinada.jpeg', nome: 'Sentada de camisa, cabeça inclinada' },
      ],
    },
    {
      id: 'natureza',
      emoji: '🏔️',
      nome: 'Natureza e mirante',
      resumo: 'Trilha, montanha, mirante. Aqui a paisagem é o assunto e você é escala — quase toda foto boa te coloca pequena no quadro. E como o corpo está coberto, o que sobra pra trabalhar é gesto: alongar, agachar, mexer na bota, cair na grama.',
      poses: [
        { img: 'estrela-na-grama-do-mirante.jpeg', nome: 'Estrela na grama do mirante' },
        { img: 'alongamento-na-beira-do-lago.jpeg', nome: 'Alongamento na beira do lago' },
        { img: 'ajustando-a-bota-com-careta.jpeg', nome: 'Ajustando a bota com careta' },
        { img: 'de-costas-mexendo-na-bota.jpeg', nome: 'De costas mexendo na bota' },
        { img: 'perna-esticada-acima-do-mar-de-nuvens.jpeg', nome: 'Perna esticada acima do mar de nuvens' },
        { img: 'agachada-segurando-o-capuz.jpeg', nome: 'Agachada segurando o capuz' },
        { img: 'rindo-na-grama-do-vinhedo.jpeg', nome: 'Rindo na grama do vinhedo' },
      ],
    },
    {
      id: 'neve',
      emoji: '❄️',
      nome: 'Neve',
      resumo: 'Corpo inteiro coberto por casaco grosso, então sobra rosto, gorro e mãos — e é aí que tudo acontece. A neve funciona como um rebatedor gigante: joga luz de baixo pra cima no rosto e apaga sombra. O risco é o oposto do da praia: branco em cima de branco vira uma mancha só, e é por isso que essas duas põem um fundo colorido e desfocado atrás.',
      dica: {
        titulo: 'Configuração do iPhone usada nestas duas',
        texto: 'Direto da câmera nativa, sem app nenhum:',
        itens: ['📸 Modo retrato', '💡 Filtro: Studio Light', '🔵 Abertura: f/2.8', '🔭 Zoom: 5x', '🔄 Telefone de cabeça pra baixo'],
        remate: 'O telefone invertido vale só pra estas duas fotos, não é regra pra tudo na neve: como a lente do iPhone fica numa ponta do aparelho, virar de cabeça pra baixo desce o ponto de vista sem precisar agachar. O zoom 5x é o que comprime o fundo e transforma as lanternas em bolinhas de luz.',
      },
      poses: [
        { img: 'cafe-nas-maos-olhar-serio.jpeg', nome: 'Café nas mãos, olhar sério' },
        { img: 'mao-na-orelha-do-gorro-sorrindo.jpeg', nome: 'Mão na orelha do gorro, sorrindo' },
      ],
    },
    {
      id: 'noite',
      emoji: '🌙',
      nome: 'Noite e luzes da cidade',
      resumo: 'O fundo é luz de cidade refletindo na água, e o corpo fica todo coberto — então tudo se resolve em ombro, mão e queixo. Todas essas foram feitas no mesmo ponto e no mesmo look, no começo da noite: é o horário em que o céu ainda tem cor e as luzes já acenderam.',
      dica: {
        titulo: 'App e configurações, segundo quem postou',
        texto: 'Quem publicou as referências (@alineralopez) diz que fez as fotos no comecinho da noite e que o segredo foi o app Dazz Cam, com esta configuração:',
        itens: ['📷 Câmera: GRD R', '🌡️ Temperatura: 5728', '🎨 Tom: 9', '☀️ Exposição: −5', '⚡ Flash: sempre ligado'],
        remate: 'O truque que ela dá junto: chegar mais perto da câmera pra ficar bem iluminada. Transcrevi do post como está — não testei os valores nem verifiquei o app.',
      },
      poses: [
        { img: 'maos-no-bolso-olhando-pro-lado.jpeg', nome: 'Mãos no bolso, olhando pro lado' },
        { img: 'de-frente-maos-nos-bolsos.jpeg', nome: 'De frente com as duas mãos nos bolsos' },
        { img: 'dois-bracos-no-cabelo.jpeg', nome: 'Dois braços no cabelo, cotovelos abertos' },
        { img: 'mao-no-oculos-cotovelo-alto.jpeg', nome: 'Mão no óculos, cotovelo alto' },
        { img: 'mao-na-tempora-de-lado.jpeg', nome: 'Mão na têmpora, de lado' },
        { img: 'capuz-e-oculos-escuros.jpeg', nome: 'Capuz e óculos escuros' },
      ],
    },
    {
      id: 'rooftop',
      emoji: '🌆',
      nome: 'Mirante, rooftop e vista',
      resumo: 'Tudo que se resolve apoiando o corpo num corrimão com uma vista atrás — bar no alto, sacada de quarto, mirante de estrada. O apoio é o que faz a pose: ele libera os ombros e dá o que fazer com as mãos. De dia o desafio é não virar silhueta contra o céu claro; de noite é o contrário — a cidade brilha e você desaparece, então a luz tem que vir da frente.',
      poses: [
        { img: 'dois-bracos-abertos-no-corrimao.jpeg', nome: 'Dois braços abertos no corrimão' },
        { img: 'perna-dobrada-apoiada-no-corrimao.jpeg', nome: 'Perna dobrada apoiada no corrimão' },
        { img: 'encostada-no-pilar-do-mirante.jpeg', nome: 'Encostada no pilar do mirante' },
        { img: 'maos-no-corrimao-cabeca-apoiada.jpeg', nome: 'Mãos no corrimão, cabeça apoiada' },
        { img: 'costas-nuas-contra-o-skyline.jpeg', nome: 'Costas nuas contra o skyline' },
        { img: 'apoiada-na-grade-com-a-cidade-embaixo.jpeg', nome: 'Apoiada na grade com a cidade embaixo' },
        { img: 'braco-estendido-na-mureta.jpeg', nome: 'Braço estendido na mureta' },
      ],
    },
    {
      id: 'casal',
      emoji: '💞',
      nome: 'Em casal',
      resumo: 'A pose de casal quebra quando os dois olham pra lente ao mesmo tempo — vira foto de documento em dupla. Todas essas resolvem isso do mesmo jeito: os dois se olham, ou se tocam, e a câmera é ignorada. Repare que em quase todas alguém está rindo de verdade, porque a pose dá um motivo pra rir.',
      poses: [
        { img: 'de-frente-de-maos-dadas-rindo.jpeg', nome: 'De frente, de mãos dadas, rindo' },
        { img: 'abraco-por-tras-maos-cruzadas.jpeg', nome: 'Abraço por trás, mãos cruzadas' },
        { img: 'abraco-de-lado-rindo.jpeg', nome: 'Abraço de lado, rindo' },
        { img: 'bracos-na-nuca-inclinada-pra-tras.jpeg', nome: 'Braços na nuca, inclinada pra trás' },
        { img: 'detalhe-das-maos-e-do-celular.jpeg', nome: 'Detalhe das mãos e do celular' },
      ],
    },
    {
      id: 'china',
      emoji: '🇨🇳',
      nome: 'China',
      resumo: 'Cenários de escala absurda — arquitetura enorme, montanha vertical, arranha-céu grudado no outro. A tentação é caber tudo no quadro e virar formiga. Todas essas fazem o contrário: escolhem UMA coisa como assunto e usam o corpo pra dar escala a ela, sem competir.',
      poses: [
        { img: 'sentado-na-escadaria-do-portal.jpeg', nome: 'Sentado na escadaria do portal' },
        { img: 'nuca-em-primeiro-plano-com-o-templo.jpeg', nome: 'Nuca em primeiro plano com o templo' },
        { img: 'apoiado-no-corrimao-do-mirante.jpeg', nome: 'Apoiado no corrimão do mirante' },
        { img: 'de-perfil-na-janela-do-cafe.jpeg', nome: 'De perfil na janela do café' },
        { img: 'em-pe-na-rua-dos-arranha-ceus.jpeg', nome: 'Em pé na rua dos arranha-céus' },
        { img: 'de-costas-diante-da-torre-na-chuva.jpeg', nome: 'De costas diante da torre, na chuva' },
      ],
    },
    {
      id: 'paris',
      emoji: '🇫🇷',
      nome: 'Paris',
      resumo: 'Aqui o cenário é o assunto, e ele é vertical: torre, colunas, colunata. Todas essas resolvem o mesmo problema — como aparecer sem tapar o monumento e sem virar formiga na frente dele. A resposta é sempre a mesma: câmera baixa e algo em primeiro plano pra dar profundidade.',
      poses: [
        { img: 'encostada-na-grade-com-a-torre-atras.jpeg', nome: 'Encostada na grade com a torre atrás' },
        { img: 'encostada-na-coluna-de-aco.jpeg', nome: 'Encostada na coluna de aço' },
        { img: 'andando-no-meio-da-colunata.jpeg', nome: 'Andando no meio da colunata' },
        { img: 'encostada-na-coluna-de-pedra.jpeg', nome: 'Encostada na coluna de pedra' },
        { img: 'sentada-na-balaustrada-pernas-cruzadas.jpeg', nome: 'Sentada na balaustrada, pernas cruzadas' },
        { img: 'na-escadaria-com-a-torre-ao-fundo.jpeg', nome: 'Na escadaria com a torre ao fundo' },
      ],
    },
  ],
};
