window.POSES = {
  tags: {
    'de-cima': { e: '🔽', l: 'câmera de cima' },
    'de-baixo': { e: '🔼', l: 'câmera de baixo' },
    'em-pe': { e: '🧍', l: 'em pé' },
    sentada: { e: '🧎', l: 'sentada' },
    agachada: { e: '🧘', l: 'agachada' },
    deitada: { e: '🧖', l: 'deitada' },
    'sem-rosto': { e: '🙈', l: 'sem mostrar o rosto' },
    braco: { e: '🤳', l: 'dá no braço estendido' },
    distancia: { e: '📍', l: 'precisa tripé ou alguém' },
    'sol-baixo': { e: '🌅', l: 'sol baixo / crepúsculo' },
    'sol-alto': { e: '☀️', l: 'sol alto' },
    objeto: { e: '🥤', l: 'com objeto na mão' },
    agua: { e: '🌊', l: 'na água' },
    noite: { e: '🌙', l: 'noite / pouca luz' },
  },

  categorias: [
    {
      id: 'genericas',
      emoji: '✨',
      nome: 'Serve em qualquer lugar',
      resumo: 'Poses que não dependem do cenário — só de um apoio na altura do quadril, uma parede lisa ou um fundo com textura. São as que valem decorar, porque funcionam na primeira esquina tanto quanto num mirante.',
      poses: [
        {
          img: 'maos-atras-das-costas-olhar-por-cima-do-ombro.jpeg',
          nome: 'Mãos atrás das costas, olhar por cima do ombro',
          corpo: 'De três-quartos de costas, peso numa perna. As duas mãos se juntam atrás do corpo na altura do quadril — isso puxa os ombros pra trás e endireita a postura sozinho, sem você pensar nisso. Gire a cabeça por cima do ombro com um meio sorriso.',
          quadro: 'Vertical, corpo inteiro, você levemente fora do centro. Câmera na altura do peito, com o fundo na altura do seu ombro.',
          luz: 'Fim de tarde com o sol baixo pelas costas, criando contorno de luz no cabelo.',
          onde: 'Qualquer fundo com textura — mato alto, parque, arbusto, parede de tijolo. O que importa é a textura atrás, não o lugar.',
          tags: ['em-pe', 'sol-baixo', 'distancia'],
        },
        {
          img: 'encostada-na-cerca-olhando-pro-lado.jpeg',
          nome: 'Encostada na cerca, olhando pro lado',
          corpo: 'De frente, encostada numa cerca com as mãos apoiadas atrás do corpo e uma perna cruzada na frente da outra. Ombros pra trás, cabeça virada pro lado e olhar fora da lente.',
          quadro: 'Vertical, corpo inteiro, você centrada. A cerca cria uma linha horizontal atrás na altura do quadril — é ela que organiza o quadro inteiro.',
          luz: 'Dia claro. Repare que a foto é em preto e branco: o P&B é o que resolve um fundo bagunçado (mato, fio, poste) que em cor competiria com você.',
          onde: 'Qualquer cerca, mureta, guarda-corpo ou parapeito na altura do quadril.',
          tags: ['em-pe', 'distancia'],
        },
        {
          img: 'perfil-torcido-maos-no-quadril.jpeg',
          nome: 'Perfil torcido com as mãos no quadril',
          corpo: 'De perfil com os pés quase juntos, tronco torcido e quadril projetado pra trás. As duas mãos descem abertas pelas laterais do quadril, com os dedos esticados. A cabeça gira por cima do ombro, olhar na lente.',
          quadro: 'Vertical, corpo inteiro, você centrada com muito espaço vazio em volta. Câmera na altura da cintura, pra roupa esticar até o chão.',
          luz: 'Luz frontal difusa e chapada, sem sombra atrás. É o oposto de todo o resto daqui: aqui o cenário é a ausência de cenário.',
          onde: 'Qualquer parede lisa e clara — corredor de hotel, parede de museu, fundo de loja, garagem.',
          tags: ['em-pe', 'distancia'],
        },
        {
          img: 'perfil-com-as-maos-juntas-atras.jpeg',
          nome: 'Perfil com as mãos juntas atrás',
          corpo: 'De perfil, quase de costas. As mãos se juntam atrás do corpo na altura do quadril, ombros baixos e coluna reta. A cabeça gira por cima do ombro e o olhar chega pela lateral do olho.',
          quadro: 'Vertical, três-quartos de corpo, você fora do centro com o vazio do fundo ocupando o outro lado.',
          luz: 'Luz lateral suave de janela, com o fundo em penumbra. É a foto do banco que mais depende da luz e menos da pose — a mesma posição em luz chapada não rende nada.',
          onde: 'Qualquer parede lisa com uma janela do lado. Quarto de hotel serve.',
          tags: ['em-pe', 'distancia'],
        },
        {
          img: 'de-frente-no-muro-branco-maos-ocupadas.jpeg',
          nome: 'De frente no muro branco, mãos ocupadas',
          corpo: 'De frente, pernas cruzadas nos tornozelos e peso numa perna. As duas mãos seguram alguma coisa — óculos numa, bolsa na outra. É o truque mais simples que existe pra mão não ficar sobrando. Sorriso aberto.',
          quadro: 'Vertical, corpo inteiro, você centrada. Câmera na altura do peito, com a linha do topo do muro cortando atrás de você.',
          luz: 'Dia nublado ou sombra aberta. O muro branco funciona como rebatedor: joga luz de volta no rosto por baixo e apaga olheira.',
          onde: 'Qualquer muro claro de rua.',
          tags: ['em-pe', 'objeto', 'distancia'],
        },
        {
          img: 'de-costas-na-luz-dourada-mao-no-cabelo.jpeg',
          nome: 'De costas na luz dourada, mão no cabelo',
          corpo: 'De costas pra câmera em passo de caminhada, tronco girado e cabeça por cima do ombro. Uma mão sobe até a nuca e entra no cabelo. Sorriso pequeno, olhar na lente.',
          quadro: 'Vertical, do quadril pra cima, você fora do centro pro fundo respirar.',
          luz: 'Sol baixo batendo de frente no seu rosto — o dourado no braço e no cabelo é o assunto da foto. Fique virada pro sol, não de costas pra ele.',
          onde: 'Qualquer rua, deck ou passarela que pegue sol baixo de frente no fim da tarde.',
          tags: ['em-pe', 'sol-baixo', 'distancia'],
        },
        {
          img: 'perna-dobrada-com-a-mao-no-cabelo.jpeg',
          nome: 'Perna dobrada com a mão no cabelo',
          corpo: 'Em pé numa perna, a outra dobrada pra frente com o joelho levantado. Uma mão entra no cabelo na altura da orelha e a outra desce e apoia no joelho levantado. Olhar direto na lente.',
          quadro: 'Vertical, corpo inteiro, você centrada com espaço em volta. Câmera na altura da cintura.',
          luz: 'Luz frontal difusa contra fundo claro. Em preto e branco, que é o que segura a foto sem nenhum cenário.',
          onde: 'Parede clara e lisa.',
          tags: ['em-pe', 'distancia'],
        },
        {
          img: 'braco-acima-da-cabeca-mao-no-cos.jpeg',
          nome: 'Braço acima da cabeça, mão no cós',
          corpo: 'Pernas afastadas com o peso dividido. Um braço sobe e dobra acima da cabeça, com a mão apoiada no topo dela; a outra mão puxa o cós da calça pro lado. Queixo levemente à frente.',
          quadro: 'Vertical, corpo inteiro, você centrada. Câmera na altura da cintura.',
          luz: 'Luz difusa e chapada, com sombra suave no chão. Sem cenário nenhum.',
          onde: 'Parede lisa e clara — cuidado com rodapé, tomada ou interruptor entrando no quadro.',
          tags: ['em-pe', 'distancia'],
        },
        {
          img: 'agachada-na-parede-com-a-mao-na-cabeca.jpeg',
          nome: 'Agachada na parede com a mão na cabeça',
          corpo: 'Agachada com os joelhos juntos e os pés no chão, um antebraço apoiado nos joelhos e a mão subindo pra sustentar a lateral da cabeça. A outra mão cai relaxada. Cabeça inclinada, olhar na lente.',
          quadro: 'Vertical, você centrada e ocupando quase todo o quadro. Quem fotografa agacha também, pra ficar na altura do seu rosto.',
          luz: 'Flash direto de noite contra parede clara. A sombra dura atrás de você faz parte do visual — não tente evitar.',
          onde: 'Qualquer parede lisa e clara: mármore de lobby, azulejo, parede de garagem.',
          tags: ['agachada', 'noite', 'distancia'],
        },
      ],
    },
    {
      id: 'praia',
      emoji: '🏖️',
      nome: 'Praia',
      resumo: 'Areia, mar e sol duro. A regra que atravessa quase todas: ou o sol está baixo, ou você precisa de algo que resolva o franzir de olho — óculos, boné, um objeto na frente do rosto, ou olhos fechados de propósito.',
      poses: [
        {
          img: 'vento-no-cabelo-contra-o-ceu.jpeg',
          nome: 'Vento no cabelo contra o céu',
          corpo: 'Em pé, tronco levemente torcido pra câmera. Uma mão sobe até a altura do rosto como se fosse segurar o cabelo que o vento leva — não segura de verdade, só fica no caminho. Queixo um pouco baixo, boca relaxada.',
          quadro: 'Vertical, do quadril pra cima. Câmera abaixo da linha do seu ombro, apontando pra cima: assim só sobra céu atrás — sem horizonte, sem gente na praia.',
          luz: 'Sol alto funciona porque o óculos espelhado resolve o olho franzido e o céu fica saturado. Fique de costas pro sol.',
          tags: ['de-baixo', 'em-pe', 'sol-alto', 'braco'],
        },
        {
          img: 'bracos-no-cabelo-olhar-por-cima-do-ombro.jpeg',
          nome: 'Braços no cabelo, olhar por cima do ombro',
          corpo: 'Três-quartos de costas pra câmera. Os dois braços sobem e as mãos prendem o cabelo no alto da cabeça — é isso que alonga o tronco e desenha o ombro. Gire só a cabeça até o olhar chegar na lente.',
          quadro: 'Vertical, meio corpo. Fique fora do centro pro mar ocupar o outro lado do quadro.',
          luz: 'Fim de tarde já sem sol direto: o céu nublado vira difusor gigante e a pele fica lisa, sem sombra dura.',
          tags: ['em-pe', 'sol-baixo', 'distancia'],
        },
        {
          img: 'espreguicadeira-com-drink.jpeg',
          nome: 'Espreguiçadeira com drink',
          corpo: 'Reclinada, uma perna estendida e a outra levemente dobrada pra quebrar a linha reta. Drink na mão perto do rosto, canudo na boca, sorriso aberto.',
          quadro: 'Vertical com o corpo em diagonal, cruzando o quadro. Deixe o guarda-sol entrar no topo — é ele que entrega o cenário sem precisar de mar.',
          luz: 'Sol alto, mas com a sombra do guarda-sol cortando o rosto. Contraste alto é o efeito, não o defeito.',
          tags: ['deitada', 'objeto', 'sol-alto', 'distancia'],
        },
        {
          img: 'agachada-na-areia-olhando-pra-cima.jpeg',
          nome: 'Agachada na areia, olhando pra cima',
          corpo: 'Sentada sobre os próprios pés, braços abraçando as canelas, ombros pra frente. O queixo sobe pra encontrar a câmera e o olhar vai direto na lente.',
          quadro: 'Vertical, câmera acima de você apontando pra baixo — a areia vira o fundo inteiro. Encoste numa rocha ou duna pra ter textura no topo do quadro.',
          luz: 'A rocha faz sombra no rosto e tira o sol de cima da cara. Sol de lado.',
          tags: ['de-cima', 'sentada', 'braco'],
        },
        {
          img: 'de-costas-olhar-por-cima-do-ombro.jpeg',
          nome: 'De costas, olhar por cima do ombro',
          corpo: 'Em pé de costas, peso numa perna só. Gire o tronco uns 45° e a cabeça até o queixo passar do ombro. Sorriso solto.',
          quadro: 'Vertical, três-quartos de corpo, você no centro. Vestido de costas nuas rende porque a foto vira sobre a linha das costas.',
          luz: 'Depois do sol sumir, com o céu ainda alaranjado. Sem flash: o rosto fica na luz ambiente e o fundo não estoura.',
          tags: ['em-pe', 'sol-baixo', 'distancia'],
        },
        {
          img: 'maos-no-rosto-de-cima-na-areia.jpeg',
          nome: 'Mãos no rosto, de cima na areia',
          corpo: 'Sentada com os joelhos dobrados e juntos, antebraços apoiados nos joelhos, as duas mãos subindo até as bochechas. Olhar reto na lente, boca fechada.',
          quadro: 'Vertical, câmera bem acima. As pernas entram em primeiro plano e criam profundidade; o resto do quadro é areia.',
          luz: 'Sol baixo lateral — a sombra do seu corpo entra no quadro e faz parte do desenho. Não tente escondê-la.',
          tags: ['de-cima', 'sentada', 'sol-baixo', 'braco'],
        },
        {
          img: 'de-costas-na-beira-queixo-pra-cima.jpeg',
          nome: 'De costas na beira, queixo pra cima',
          corpo: 'Em pé de costas na linha da espuma, coluna alongada. Torça o tronco de leve e vire a cabeça por cima do ombro com o queixo alto e os olhos quase fechados — como quem está pegando o último sol.',
          quadro: 'Horizontal, você no centro e pequena no quadro. Aqui o assunto é o céu com nuvens e o morro ao fundo; você é escala.',
          luz: 'Contraluz de sol baixo. A pele fica dourada e o mar reflete a luz atrás de você.',
          tags: ['em-pe', 'agua', 'sol-baixo', 'distancia'],
        },
        {
          img: 'camisetao-e-bone-andando-na-agua.jpeg',
          nome: 'Camisetão e boné, andando na água',
          corpo: 'Andando na beirada com a água no tornozelo, camisetão oversized, boné inclinado pra baixo escondendo o rosto. Olhar pro chão, braços soltos. Ande de verdade — não pare pra posar.',
          quadro: 'Vertical, você no terço de baixo e dois terços de mar transparente acima. É a pose pra quando você não quer aparecer.',
          luz: 'Sol alto — é ele que deixa a água legível e turquesa. Aqui o sol duro é aliado.',
          tags: ['em-pe', 'agua', 'sem-rosto', 'sol-alto', 'distancia'],
        },
        {
          img: 'fotografando-o-por-do-sol.jpeg',
          nome: 'Fotografando o pôr do sol',
          corpo: 'Sentada de lado na areia, joelhos dobrados, celular erguido fotografando o horizonte. Você aparece de perfil e ocupada — a pose é não estar posando.',
          quadro: 'Vertical, você no terço inferior e o céu ocupando a metade de cima.',
          luz: 'Dez a quinze minutos depois do sol sumir, quando as nuvens acendem de laranja. Antes disso o céu ainda está branco.',
          tags: ['sentada', 'sem-rosto', 'sol-baixo', 'objeto', 'distancia'],
        },
        {
          img: 'sentada-de-lado-com-o-mar-atras.jpeg',
          nome: 'Sentada de lado com o mar atrás',
          corpo: 'Sentada com as duas pernas dobradas pro mesmo lado, um braço abraçando o joelho e a mão descendo até o pé. Tronco torcido pra câmera, ombros pra trás.',
          quadro: 'Vertical, corpo inteiro, linha do horizonte na altura do seu ombro — nem cortando a cabeça, nem no chão.',
          luz: 'Crepúsculo de céu pastel, sem sol na cara e sem sombra dura.',
          tags: ['sentada', 'sol-baixo', 'distancia'],
        },
        {
          img: 'deitada-de-brucos-na-canga.jpeg',
          nome: 'Deitada de bruços na canga',
          corpo: 'De bruços, apoiada num antebraço, a mão aberta sustentando a lateral da cabeça e empurrando o rosto de leve. Ombros relaxados, olhar direto e sério.',
          quadro: 'Vertical fechado, rosto e ombros. Câmera na altura da areia apontando um pouco pra cima, pra entrar céu atrás.',
          luz: 'Sol alto vindo pelas costas, com a canga estampada dando cor no primeiro plano.',
          tags: ['deitada', 'sol-alto', 'braco'],
        },
        {
          img: 'agua-de-coco-de-pernas-cruzadas.jpeg',
          nome: 'Água de coco de pernas cruzadas',
          corpo: 'Sentada de pernas cruzadas na borda da piscina, coluna reta, as duas mãos segurando o coco na altura do peito, canudo na boca e olhar na lente.',
          quadro: 'Vertical de frente, corpo inteiro, com a piscina e o mar em faixas atrás.',
          luz: 'Sol alto de frente. O coco tampa parte do rosto e resolve de uma vez o "não sei o que fazer com as mãos".',
          tags: ['sentada', 'objeto', 'sol-alto', 'distancia'],
        },
        {
          img: 'cabelo-molhado-na-toalha.jpeg',
          nome: 'Cabelo molhado na toalha',
          corpo: 'De bruços apoiada nos dois antebraços, cabelo molhado solto caindo no rosto — deixe cair, não arrume. Olhar pro lado, fora da lente.',
          quadro: 'Quadrado ou vertical fechado, câmera na altura da toalha: céu limpo atrás e a toalha colorida embaixo.',
          luz: 'Sol alto, recém-saída do mar. O molhado é o que faz a foto — se o cabelo secar, a pose perde a graça.',
          tags: ['deitada', 'sol-alto', 'braco'],
        },
        {
          img: 'andando-de-saia-com-a-mao-no-cabelo.jpeg',
          nome: 'Andando de saia com a mão no cabelo',
          corpo: 'Em pé de perfil, um pé à frente do outro no meio do passo. O braço de trás sobe e a mão passa pelo cabelo com o cotovelo bem alto — é o cotovelo levantado que abre a linha do ombro. Queixo baixo, olhar pra baixo.',
          quadro: 'Vertical, corpo inteiro, câmera na altura do quadril pra alongar a perna. Você fora do centro e a pedra e o mar preenchendo o resto.',
          luz: 'Sol alto e forte. Fique com o vento de frente pro cabelo voar pra trás, e o sol de lado — de frente, a sombra do braço levantado cai na cara.',
          tags: ['em-pe', 'sol-alto', 'distancia'],
        },
        {
          img: 'encostada-na-cerca-pernas-cruzadas.jpeg',
          nome: 'Encostada na cerca, pernas cruzadas',
          corpo: 'Em pé com uma mão apoiada na cerca — é o apoio que deixa o resto do corpo solto — e as pernas cruzadas uma na frente da outra, peso na de trás. A outra mão sobe e toca a haste do óculos. Sorriso fechado.',
          quadro: 'Vertical, corpo inteiro. Câmera baixa, quase na altura do joelho, com o deck fugindo em diagonal: é a diagonal que alonga a perna.',
          luz: 'Sol alto de frente. Aqui o óculos é o que salva a foto — sem ele você franze o olho.',
          tags: ['em-pe', 'sol-alto', 'distancia'],
        },
        {
          img: 'arco-pra-tras-sentada-na-canga.jpeg',
          nome: 'Arco pra trás sentada na canga',
          corpo: 'Sentada com uma mão apoiada na areia atrás do quadril, tronco arqueado pra trás e as pernas dobradas pro mesmo lado. O braço livre dobra acima da cabeça com a mão relaxada. Queixo pra cima, boca entreaberta.',
          quadro: 'Vertical, corpo inteiro em diagonal. Câmera baixa, na altura da canga, com a linha do mar passando atrás do seu ombro.',
          luz: 'Sol alto — resolvido pelo óculos e pelo queixo levantado, que joga a sombra do nariz pra cima em vez de pra baixo.',
          tags: ['sentada', 'sol-alto', 'distancia'],
        },
        {
          img: 'bracos-abertos-no-corrimao.jpeg',
          nome: 'Braços abertos no corrimão',
          corpo: 'De costas pro mar, os dois braços abertos apoiados no corrimão — isso abre o peito e alonga o tronco. A camisa cai dos ombros de propósito. Gire a cabeça por cima do ombro pra câmera.',
          quadro: 'Vertical, três-quartos de corpo. Câmera na sua altura, com o corrimão cortando o quadro em diagonal e o sol atrás de você.',
          luz: 'Pôr do sol pelas costas, contraluz. O rosto fica na sombra e o fundo vira laranja — não use flash, ele mata o efeito.',
          tags: ['em-pe', 'sol-baixo', 'distancia'],
        },
        {
          img: 'agachada-de-costas-com-flor-no-cabelo.jpeg',
          nome: 'Agachada de costas com flor no cabelo',
          corpo: 'Agachada na areia com o vestido espalhado em volta, corpo de costas pra câmera. Gire o tronco e a cabeça por cima do ombro, olhar direto na lente. A flor vai na orelha do lado que fica visível.',
          quadro: 'Vertical, você no centro ocupando quase todo o quadro. Quem fotografa também agacha, pra ficar na sua altura, com a linha da água atrás do seu ombro.',
          luz: 'Crepúsculo já sem sol, quase monocromático de laranja. Luz baixa e difusa: aqui o desenho vem das costas nuas do vestido, não da luz.',
          tags: ['agachada', 'sol-baixo', 'distancia'],
        },
        {
          img: 'vestido-longo-no-fim-do-por-do-sol.jpeg',
          nome: 'Vestido longo no fim do pôr do sol',
          corpo: 'Em pé com o peso numa perna e o quadril projetado pro lado, uma mão na lateral do quadril e a outra segurando a bolsa junto ao corpo. Olhos fechados e queixo baixo — a pose é serena, sem sorriso.',
          quadro: 'Vertical, corpo inteiro, você no centro. Câmera baixa pro vestido cair até fora do quadro e alongar a silhueta.',
          luz: 'Quase noite, com o céu ainda em faixas de laranja e roxo. Nessa hora o céu está mais claro que você: precisa de uma fonte de luz apontada pra você, mesmo que seja a lanterna de outro celular.',
          tags: ['em-pe', 'sol-baixo', 'objeto', 'distancia'],
        },
        {
          img: 'maos-emoldurando-o-rosto-na-agua.jpeg',
          nome: 'Mãos emoldurando o rosto na água',
          corpo: 'Sentada na água rasa, os dois braços dobrados e as mãos abertas emoldurando o rosto, dedos apoiados nas bochechas e cotovelos pra dentro. Olhar direto na lente, boca fechada.',
          quadro: 'Vertical, do quadril pra cima. Câmera na altura do seu rosto, com a água ocupando o fundo inteiro — sem horizonte alto, sem praia aparecendo.',
          luz: 'Pôr do sol vermelho refletindo na água atrás: o reflexo faz o fundo brilhar. Uma luz fraca de frente resolve o rosto sem estragar o vermelho.',
          tags: ['sentada', 'agua', 'sol-baixo', 'distancia'],
        },
        {
          img: 'mao-na-nuca-contra-o-sol.jpeg',
          nome: 'Mão na nuca contra o sol',
          corpo: 'Em pé de perfil na água rasa. Uma mão sobe até a nuca e passa pelo cabelo com o cotovelo pra frente; o outro braço fica solto e um pouco pra trás, mão relaxada. Olhos fechados, queixo pra cima.',
          quadro: 'Vertical, três-quartos de corpo. Câmera na sua altura, com o sol dentro do quadro no canto — é o sol na moldura que dá o brilho de contorno no cabelo.',
          luz: 'Sol tocando o horizonte, contraluz total. Toque na tela pra medir a luz no seu rosto e deixe o fundo estourar de propósito.',
          tags: ['em-pe', 'agua', 'sol-baixo', 'distancia'],
        },
        {
          img: 'reclinada-na-areia-na-hora-azul.jpeg',
          nome: 'Reclinada na areia na hora azul',
          corpo: 'Reclinada de lado na areia, apoiada numa mão atrás do corpo, uma perna dobrada e a outra estendida por baixo do vestido. Tronco torcido pra câmera, ombros pra trás, olhar direto.',
          quadro: 'Vertical, corpo inteiro em diagonal, você no terço direito. Câmera baixa, quase na altura da areia.',
          luz: 'Hora azul, uns 20 minutos depois do sol sumir, quando o céu fica azul-marinho com uma faixa rosa. Aí você já precisa de luz própria — flash fraco ou lanterna de outro celular — senão vira silhueta.',
          tags: ['deitada', 'sol-baixo', 'distancia'],
        },
        {
          img: 'bone-cobrindo-os-olhos-mao-no-rosto.jpeg',
          nome: 'Boné cobrindo os olhos, mão no rosto',
          corpo: 'De bruços, apoiada nos antebraços, com o boné puxado pra frente cobrindo os olhos — sobra só o nariz e a boca. Uma mão aberta encosta na lateral do rosto, dedos relaxados. Cabeça de perfil.',
          quadro: 'Vertical fechado, rosto e ombros. Câmera baixa, quase na altura da canga, apontando um pouco pra cima pra entrar céu limpo atrás.',
          luz: 'Sol alto. O boné resolve o rosto inteiro: sem ele, você franze o olho e a sombra do nariz fica dura.',
          tags: ['deitada', 'sol-alto', 'braco'],
        },
        {
          img: 'mao-cobrindo-um-olho-rindo.jpeg',
          nome: 'Mão cobrindo um olho, rindo',
          corpo: 'Em pé de três-quartos, camisa branca escorregando de um ombro. Uma mão sobe espalmada e cobre um olho e parte da testa; o outro olho fica visível e o riso é aberto. A pose é a brincadeira, não a posição.',
          quadro: 'Vertical, meio corpo, você no centro com o mar quebrando atrás na altura do quadril.',
          luz: 'Fim de tarde de céu encoberto — luz difusa, nenhuma sombra dura. A mão no rosto aqui é estética, não necessidade.',
          tags: ['em-pe', 'sol-baixo', 'distancia'],
        },
        {
          img: 'reclinada-mexendo-nos-oculos.jpeg',
          nome: 'Reclinada mexendo nos óculos',
          corpo: 'Reclinada de lado na toalha, apoiada num antebraço, pernas esticadas e cruzadas. As duas mãos estão ocupadas com os óculos na toalha e o olhar vai pra elas, não pra lente. Boné escondendo os olhos.',
          quadro: 'Vertical, corpo inteiro em diagonal, você no terço de baixo. Câmera na altura da areia — a praia cheia atrás fica desfocada e vira só contexto.',
          luz: 'Sol alto e duro. Boné + olhar pra baixo é o que salva: você nunca encara o sol.',
          tags: ['deitada', 'objeto', 'sol-alto', 'distancia'],
        },
        {
          img: 'de-brucos-mexendo-na-camera.jpeg',
          nome: 'De bruços mexendo na câmera',
          corpo: 'De bruços na canga, de costas pra câmera, camiseta oversized e cabelo preso. As duas mãos seguram uma câmera compacta e você está olhando pra ela. Nenhum rosto aparece.',
          quadro: 'Vertical, de cima e de trás, com a areia ocupando a metade superior. Você entra na diagonal no terço de baixo.',
          luz: 'Fim de tarde, sol raso deitando sombra longa na areia. É a foto de "estava fazendo outra coisa" — funciona porque ninguém está posando.',
          tags: ['deitada', 'de-cima', 'sem-rosto', 'objeto', 'sol-baixo', 'distancia'],
        },
        {
          img: 'livro-na-canga-foto-do-colo.jpeg',
          nome: 'Livro na canga, foto do próprio colo',
          corpo: 'Você não aparece — só o próprio colo. Sentada, pernas à frente, uma mão apoiada na página aberta do livro. É a única do banco que você tira de si mesma sem aparecer.',
          quadro: 'Vertical, câmera apontada pra baixo, pro próprio colo. O livro no centro, a canga como fundo e as pernas entrando no terço de baixo.',
          luz: 'Sol alto filtrado por folhas — as sombras rendadas na perna são o assunto da foto. Sem essa sombra a imagem fica sem graça.',
          tags: ['sentada', 'de-cima', 'sem-rosto', 'objeto', 'sol-alto', 'braco'],
        },
        {
          img: 'mao-sustentando-o-rosto-na-areia.jpeg',
          nome: 'Mão sustentando o rosto na areia',
          corpo: 'Sentada na areia com as pernas dobradas pro lado, camisa branca aberta caindo dos dois ombros. Uma mão sobe espalmada e sustenta a lateral do rosto, empurrando de leve. Cabeça inclinada, olhar direto e sereno.',
          quadro: 'Vertical, três-quartos de corpo, você no centro. Câmera na sua altura sentada — quem fotografa se agacha.',
          luz: 'Fim de tarde dourado com o mar desfocado atrás. A luz vem de lado e desenha o osso do rosto.',
          tags: ['sentada', 'sol-baixo', 'distancia'],
        },
        {
          img: 'sentada-de-camisa-cabeca-inclinada.jpeg',
          nome: 'Sentada de camisa, cabeça inclinada',
          corpo: 'Sentada de lado na areia, joelhos dobrados e juntos, um antebraço apoiado neles. Camisa branca solta caindo de um ombro, óculos escuros. A cabeça tomba pro lado até quase tocar o ombro — é a inclinação que dá o clima relaxado.',
          quadro: 'Vertical, corpo inteiro, você no centro com a linha do mar na altura do ombro. Câmera baixa, na altura da areia, pra alongar a perna.',
          luz: 'Início de manhã ou fim de tarde de céu claro. O óculos resolve o olho e a camisa branca rebate luz no rosto.',
          tags: ['sentada', 'sol-alto', 'distancia'],
        },
      ],
    },
    {
      id: 'natureza',
      emoji: '🏔️',
      nome: 'Natureza e mirante',
      resumo: 'Trilha, montanha, mirante. Aqui a paisagem é o assunto e você é escala — quase toda foto boa te coloca pequena no quadro. E como o corpo está coberto, o que sobra pra trabalhar é gesto: alongar, agachar, mexer na bota, cair na grama.',
      poses: [
        {
          img: 'estrela-na-grama-do-mirante.jpeg',
          nome: 'Estrela na grama do mirante',
          corpo: 'Deitada de barriga pra cima na grama, braços e pernas abertos em X, cabeça virada de lado. Relaxa tudo — a pose é o abandono depois da subida, não uma posição bonita.',
          quadro: 'Vertical. Quem fotografa fica acima e atrás da sua cabeça, apontando pra baixo: você entra invertida no primeiro plano e o vale com o lago ocupa a faixa de cima.',
          luz: 'Meio-dia de céu limpo funciona justamente porque você está deitada, de óculos e com o rosto virado — nenhum sol batendo de frente na cara.',
          tags: ['de-cima', 'deitada', 'sol-alto', 'distancia'],
        },
        {
          img: 'alongamento-na-beira-do-lago.jpeg',
          nome: 'Alongamento na beira do lago',
          corpo: 'Em pé de perfil, peso nos dois pés. Os dois braços sobem estendidos até as mãos se encontrarem acima da cabeça, queixo pra cima e olhos fechados. É um alongamento de verdade — por isso não parece pose.',
          quadro: 'Vertical, corpo inteiro, você no centro e embaixo. A trilha de pedra em primeiro plano dá profundidade e o lago fica na faixa de cima.',
          luz: 'Manhã com sol lateral entre as árvores e a mata do outro lado ainda escura — o contraste é o que destaca a silhueta dos braços.',
          tags: ['em-pe', 'distancia'],
        },
        {
          img: 'ajustando-a-bota-com-careta.jpeg',
          nome: 'Ajustando a bota com careta',
          corpo: 'Em pé, uma perna dobrada pra frente e pra cima, a mão do mesmo lado segurando a bota como se fosse tirar uma pedrinha. Careta de esforço, boca aberta rindo. Capuz na cabeça e óculos escuros.',
          quadro: 'Vertical fechado, câmera um pouco abaixo da altura do seu quadril — a perna dobrada vem pro primeiro plano e o cascalho claro fecha o fundo.',
          luz: 'Fim de tarde, com o sol ainda batendo nos pinheiros atrás: você fica na sombra e o fundo dourado.',
          tags: ['em-pe', 'sol-baixo', 'distancia'],
        },
        {
          img: 'de-costas-mexendo-na-bota.jpeg',
          nome: 'De costas mexendo na bota',
          corpo: 'Sentada na grama de costas pra câmera, tronco torcido, uma perna estendida à frente e as duas mãos alcançando a bota. O cabelo cai pro lado e nenhum rosto aparece.',
          quadro: 'Vertical, você no canto de baixo e a trilha subindo em S pelo morro verde — é a trilha que faz a composição, não você.',
          luz: 'Sol alto de lado. Como você está de costas, o sol duro deixa de ser problema e vira contraste no verde.',
          tags: ['sentada', 'sem-rosto', 'sol-alto', 'distancia'],
        },
        {
          img: 'perna-esticada-acima-do-mar-de-nuvens.jpeg',
          nome: 'Perna esticada acima do mar de nuvens',
          corpo: 'Em pé numa perna só, a outra estendida pra frente na horizontal e travada. Braços cruzados na frente do peito e olhar pra baixo, sério. O contraste entre a pose absurda e a cara séria é a graça.',
          quadro: 'Vertical, você inteira no terço direito e o mar de nuvens preenchendo a faixa do meio. Câmera na sua altura ou um pouco abaixo, pra você ficar acima da linha das nuvens.',
          luz: 'Nascer do sol, luz rasante alaranjada batendo na grama do primeiro plano.',
          tags: ['em-pe', 'sol-baixo', 'distancia'],
        },
        {
          img: 'agachada-segurando-o-capuz.jpeg',
          nome: 'Agachada segurando o capuz',
          corpo: 'Agachada com os joelhos juntos, as duas mãos sobem e seguram a borda do capuz emoldurando o rosto. Boca fechada, olhar direto por trás do óculos.',
          quadro: 'Vertical, câmera acima apontando pra baixo — o cascalho claro vira o fundo inteiro e o preto da jaqueta recorta.',
          luz: 'Luz difusa de fim de dia, sem sol direto. Capuz escuro pede fundo claro: em pedra escura você desaparece.',
          tags: ['de-cima', 'agachada', 'distancia'],
        },
        {
          img: 'rindo-na-grama-do-vinhedo.jpeg',
          nome: 'Rindo na grama do vinhedo',
          corpo: 'Reclinada na grama apoiada num braço atrás, pernas dobradas pro lado. A outra mão sobe até a testa fazendo sombra pros olhos, cabeça pra trás, riso aberto. A pose é a reação ao sol na cara — não uma posição.',
          quadro: 'Vertical, câmera acima e à sua frente, apontando pra baixo. A fileira de plantas corre em diagonal atrás e a grama fecha o resto.',
          luz: 'Sol alto e duro. E é exatamente por isso que a mão na testa funciona: ela é a solução pra luz e o motivo do riso ao mesmo tempo.',
          onde: 'Vinhedo, pomar, qualquer fileira de plantação que crie uma linha diagonal atrás.',
          tags: ['deitada', 'de-cima', 'sol-alto', 'distancia'],
        },
      ],
    },
    {
      id: 'neve',
      emoji: '❄️',
      nome: 'Neve',
      resumo: 'Corpo inteiro coberto por casaco grosso, então sobra rosto, gorro e mãos — e é aí que tudo acontece. A neve funciona como um rebatedor gigante: joga luz de baixo pra cima no rosto e apaga sombra. O risco é o oposto do da praia: branco em cima de branco vira uma mancha só, e é por isso que essas duas põem um fundo colorido e desfocado atrás.',
      dica: {
        titulo: 'Configuração do iPhone usada nestas duas',
        texto: 'Direto da câmera nativa, sem app nenhum:',
        itens: [
          '📸 Modo retrato',
          '💡 Filtro: Studio Light',
          '🔵 Abertura: f/2.8',
          '🔭 Zoom: 5x',
          '🔄 Telefone de cabeça pra baixo',
        ],
        remate: 'O telefone invertido vale só pra estas duas fotos, não é regra pra tudo na neve: como a lente do iPhone fica numa ponta do aparelho, virar de cabeça pra baixo desce o ponto de vista sem precisar agachar. O zoom 5x é o que comprime o fundo e transforma as lanternas em bolinhas de luz.',
      },
      poses: [
        {
          img: 'cafe-nas-maos-olhar-serio.jpeg',
          nome: 'Café nas mãos, olhar sério',
          quadro: 'Vertical, do quadril pra cima, você centrada. Câmera na altura do peito. O fundo colorido e bem desfocado é metade da foto — sem ele, branco no branco não se separa.',
          luz: 'Sol de inverno com a neve rebatendo luz de baixo pra cima. É a luz mais generosa que existe pro rosto: não tem sombra dura em lugar nenhum.',
          onde: 'Feira, mercado ou rua decorada na neve — qualquer coisa colorida a alguns metros de distância pra virar borrão atrás.',
          tags: ['em-pe', 'objeto', 'distancia'],
        },
        {
          img: 'mao-na-orelha-do-gorro-sorrindo.jpeg',
          nome: 'Mão na orelha do gorro, sorrindo',
          quadro: 'Vertical, do quadril pra cima. Deixe espaço lateral pro braço levantado não encostar na borda. Mesmo enquadramento da anterior — muda só o braço e a expressão.',
          luz: 'Mesma luz da anterior; as duas saíram na mesma sequência. Repare que o braço levantado não faz sombra no rosto, porque a luz vem refletida do chão.',
          onde: 'Mesma ideia: fundo colorido e distante.',
          tags: ['em-pe', 'objeto', 'distancia'],
        },
      ],
    },
    {
      id: 'noite',
      emoji: '🌙',
      nome: 'Noite e luzes da cidade',
      resumo: 'O fundo é luz de cidade refletindo na água, e o corpo fica todo coberto — então tudo se resolve em ombro, mão e queixo. Todas essas foram feitas no mesmo ponto e no mesmo look, no começo da noite: é o horário em que o céu ainda tem cor e as luzes já acenderam.',
      dica: {
        titulo: 'App e configurações, segundo quem postou',
        texto: 'Quem publicou as referências (@alineralopez) diz que fez as fotos no comecinho da noite e que o segredo foi o app Dazz Cam, com esta configuração:',
        itens: [
          '📷 Câmera: GRD R',
          '🌡️ Temperatura: 5728',
          '🎨 Tom: 9',
          '☀️ Exposição: −5',
          '⚡ Flash: sempre ligado',
        ],
        remate: 'O truque que ela dá junto: chegar mais perto da câmera pra ficar bem iluminada. Transcrevi do post como está — não testei os valores nem verifiquei o app.',
      },
      poses: [
        {
          img: 'maos-no-bolso-olhando-pro-lado.jpeg',
          nome: 'Mãos no bolso, olhando pro lado',
          corpo: 'Em pé de frente, as duas mãos nos bolsos da calça e os ombros soltos. O olhar vai pro lado, fora da lente — é isso que tira o peso de "foto posada" de uma pose tão simples. Óculos na cabeça prendendo o cabelo.',
          quadro: 'Vertical, do quadril pra cima, você no centro. Câmera na altura do peito, com a linha da água e as luzes passando atrás do seu ombro.',
          luz: 'A mais cedo do conjunto: o céu ainda tem laranja no horizonte e as luzes da cidade já acenderam. É a janela mais fácil, porque ainda sobra luz ambiente no rosto.',
          tags: ['em-pe', 'noite', 'distancia'],
        },
        {
          img: 'de-frente-maos-nos-bolsos.jpeg',
          nome: 'De frente com as duas mãos nos bolsos',
          corpo: 'Mesma base da anterior, com duas mudanças: o olhar vem direto pra lente e o queixo desce um pouco. Ombros pra trás, cotovelos afastados do corpo pra não colar o braço no tronco.',
          quadro: 'Vertical, corpo dos joelhos pra cima. Câmera na altura do peito, você centrada com a colina escura de um lado e as luzes do outro.',
          luz: 'Céu já sem laranja. O rosto está mais claro que o fundo — é o flash suave fazendo o trabalho, não a luz do ambiente.',
          tags: ['em-pe', 'noite', 'distancia'],
        },
        {
          img: 'dois-bracos-no-cabelo.jpeg',
          nome: 'Dois braços no cabelo, cotovelos abertos',
          corpo: 'De frente, os dois braços sobem e as mãos entram no cabelo na altura das orelhas, com os cotovelos bem abertos pros lados. Isso cria um triângulo em volta do rosto e alarga a silhueta. Olhar na lente, sorriso mínimo.',
          quadro: 'Vertical, do quadril pra cima — precisa de espaço lateral pros cotovelos não encostarem na borda do quadro.',
          luz: 'Noite fechada com rastro de avião rosa no céu. Os braços levantados podem tapar luz do rosto: mantenha as mãos atrás da linha da orelha, não à frente.',
          tags: ['em-pe', 'noite', 'distancia'],
        },
        {
          img: 'mao-no-oculos-cotovelo-alto.jpeg',
          nome: 'Mão no óculos, cotovelo alto',
          corpo: 'Três-quartos pra câmera. Uma mão sobe e segura o óculos apoiado na cabeça, com o cotovelo bem alto e pra frente; a outra mão fica no bolso. O contraste entre um braço ativo e um parado é o que dá o desenho.',
          quadro: 'Vertical, do quadril pra cima, você fora do centro pro braço levantado ter espaço.',
          luz: 'Noite, com as luzes da cidade em faixa atrás. O braço levantado do lado da luz principal cria sombra na testa — levante o do lado escuro.',
          tags: ['em-pe', 'noite', 'distancia'],
        },
        {
          img: 'mao-na-tempora-de-lado.jpeg',
          nome: 'Mão na têmpora, de lado',
          corpo: 'Corpo de lado, tronco torcido pra câmera e a cabeça virada por cima do ombro. Uma mão sobe até a têmpora, tirando o cabelo do rosto com os dedos. Olhar direto, boca relaxada.',
          quadro: 'Vertical, corpo inteiro. Câmera na altura do peito, você no terço de baixo — o céu escuro ocupa a metade de cima e aguenta ficar vazio.',
          luz: 'A mais escura do conjunto: céu já noite fechada. Sem flash aqui você não existe; é a foto que mais depende de estar perto da câmera.',
          tags: ['em-pe', 'noite', 'distancia'],
        },
        {
          img: 'capuz-e-oculos-escuros.jpeg',
          nome: 'Capuz e óculos escuros',
          corpo: 'De frente, capuz na cabeça emoldurando o rosto e óculos escuros mesmo de noite. Uma mão desce em direção ao bolso, ombros retos, expressão séria. É a pose pra quando você não quer sorrir.',
          quadro: 'Vertical, corpo dos joelhos pra cima, você centrada. O capuz preto pede o céu ainda claro atrás, senão a cabeça desaparece no fundo.',
          luz: 'Céu lilás de fim de crepúsculo. Óculos escuro de noite só funciona porque o flash acende o rosto — na luz ambiente ia sumir tudo.',
          tags: ['em-pe', 'noite', 'distancia'],
        },
        {
          img: 'capuz-e-oculos-queixo-baixo.jpeg',
          nome: 'Capuz e óculos, queixo baixo',
          corpo: 'Variação da anterior, do mesmo momento: mesma base de capuz e óculos, mas o queixo desce e o corpo gira um pouco mais pro lado. Serve pra comparar o quanto uma mudança mínima de queixo muda a foto.',
          quadro: 'Vertical, um pouco mais fechado que a anterior, com mais céu sobrando acima da cabeça.',
          luz: 'Mesma luz da anterior — as duas saíram na mesma sequência.',
          tags: ['em-pe', 'noite', 'distancia'],
        },
      ],
    },
    {
      id: 'rooftop',
      emoji: '🌆',
      nome: 'Mirante, rooftop e vista',
      resumo: 'Tudo que se resolve apoiando o corpo num corrimão com uma vista atrás — bar no alto, sacada de quarto, mirante de estrada. O apoio é o que faz a pose: ele libera os ombros e dá o que fazer com as mãos. De dia o desafio é não virar silhueta contra o céu claro; de noite é o contrário — a cidade brilha e você desaparece, então a luz tem que vir da frente.',
      poses: [
        {
          img: 'dois-bracos-abertos-no-corrimao.jpeg',
          nome: 'Dois braços abertos no corrimão',
          corpo: 'De costas pro corrimão, os dois braços bem abertos apoiados nele, o que estica o peito e joga o quadril pra frente. Uma perna cruza na frente da outra com o pé apontado. Queixo levemente pra cima, sorriso fechado.',
          quadro: 'Vertical, corpo inteiro, você centrada. Câmera na altura do peito, com a água e os morros preenchendo atrás e o corrimão cortando o quadro na horizontal.',
          luz: 'Sol alto de dia limpo, com você de frente pra ele. Aqui não tem truque de luz: é sol na cara mesmo, resolvido só por não abrir muito o olho.',
          onde: 'Qualquer mirante ou parada de estrada com corrimão na altura do quadril.',
          tags: ['em-pe', 'sol-alto', 'distancia'],
        },
        {
          img: 'perna-dobrada-apoiada-no-corrimao.jpeg',
          nome: 'Perna dobrada apoiada no corrimão',
          corpo: 'Variação da anterior: mesmos braços abertos no corrimão, mas uma perna dobra pra trás e o pé se apoia numa barra mais baixa. Isso quebra a linha reta das pernas e joga o quadril pro lado.',
          quadro: 'Vertical, corpo inteiro. Câmera baixa, abaixo da linha do corrimão, pra perna dobrada aparecer inteira.',
          luz: 'Mesma luz da anterior — as duas saíram na mesma sequência, e a diferença é só a perna.',
          onde: 'Corrimão de mirante com mais de uma barra horizontal, pra ter onde apoiar o pé.',
          tags: ['em-pe', 'sol-alto', 'distancia'],
        },
        {
          img: 'encostada-no-pilar-do-mirante.jpeg',
          nome: 'Encostada no pilar do mirante',
          corpo: 'Encostada de lado num pilar de pedra, um braço estendido apoiado no corrimão e a outra mão descansando no quadril. Pernas cruzadas, peso na de trás. Olhar pro lado, queixo alto.',
          quadro: 'Vertical, corpo inteiro, você no terço esquerdo, com o pilar como âncora e o corrimão fugindo pro canto oposto.',
          luz: 'Sol alto lateral. O pilar de pedra clara rebate luz na sua direção e ameniza a sombra do rosto.',
          onde: 'Mirante com pilar, poste ou coluna junto ao corrimão.',
          tags: ['em-pe', 'sol-alto', 'distancia'],
        },
        {
          img: 'maos-no-corrimao-cabeca-apoiada.jpeg',
          nome: 'Mãos no corrimão, cabeça apoiada',
          corpo: 'Debruçada sobre o corrimão com os dois antebraços apoiados nele. Uma mão sobe e sustenta a lateral da cabeça, cotovelo apoiado. Uma perna dobrada atrás. Olhar direto na lente, cabeça inclinada.',
          quadro: 'Vertical, três-quartos de corpo, você no centro. Câmera na altura do corrimão, com a água ao fundo desfocada.',
          luz: 'Sol alto com vento. A cabeça apoiada na mão é o que impede a pose de virar "turista olhando a paisagem".',
          onde: 'Qualquer corrimão em que dê pra debruçar com os dois braços.',
          tags: ['em-pe', 'sol-alto', 'distancia'],
        },
        {
          img: 'costas-nuas-contra-o-skyline.jpeg',
          nome: 'Costas nuas contra o skyline',
          corpo: 'De costas pra câmera, os dois braços abertos apoiados no corrimão, ombros pra baixo e coluna alongada. Gire só a cabeça por cima do ombro, olhar direto na lente.',
          quadro: 'Vertical, do quadril pra cima, você no terço de baixo — o skyline precisa de espaço vertical pra caber inteiro. Câmera na sua altura ou um pouco acima.',
          luz: 'Fim de crepúsculo: o céu ainda azul e os prédios já acesos. É a única janela em que dá pra ter as duas coisas — meia hora depois o céu vira preto e você perde o azul.',
          onde: 'Sacada de quarto alto, rooftop, qualquer parapeito com o skyline de frente.',
          tags: ['em-pe', 'noite', 'distancia'],
        },
        {
          img: 'apoiada-na-grade-com-a-cidade-embaixo.jpeg',
          nome: 'Apoiada na grade com a cidade embaixo',
          corpo: 'De costas pra grade, os dois braços estendidos pra trás apoiados nela — isso abre o peito e joga o quadril pra frente. Uma perna cruza a outra. Tronco levemente torcido, queixo baixo, olhar pela lateral.',
          quadro: 'Vertical, do joelho pra cima, você centrada. Câmera na altura do peito. As luzes da cidade viram uma faixa de pontos atrás, na altura do seu quadril.',
          luz: 'Noite, com a luz vindo toda da frente (flash ou a luz do próprio bar). Sem isso, a cidade aparece e você não. Tecido acetinado rende muito nessa luz frontal.',
          onde: 'Qualquer grade de rooftop, mirante ou sacada alta.',
          tags: ['em-pe', 'noite', 'distancia'],
        },
        {
          img: 'braco-estendido-na-mureta.jpeg',
          nome: 'Braço estendido na mureta',
          corpo: 'De lado, encostada na mureta com o braço de trás totalmente estendido apoiado nela — o braço reto é o que cria a diagonal da foto. Peso na perna de trás, a da frente levemente dobrada. Olhar direto, boca fechada.',
          quadro: 'Vertical, do joelho pra cima, você no terço esquerdo e a mureta fugindo em diagonal pro canto oposto.',
          luz: 'Noite com luz frontal quente do próprio ambiente. Roupa clara ajuda muito: reflete a luz e te separa do fundo escuro.',
          onde: 'Mureta, parapeito de concreto ou qualquer beirada na altura da cintura.',
          tags: ['em-pe', 'noite', 'distancia'],
        },
      ],
    },
    {
      id: 'casal',
      emoji: '💞',
      nome: 'Em casal',
      resumo: 'A pose de casal quebra quando os dois olham pra lente ao mesmo tempo — vira foto de documento em dupla. Todas essas resolvem isso do mesmo jeito: os dois se olham, ou se tocam, e a câmera é ignorada. Repare que em quase todas alguém está rindo de verdade, porque a pose dá um motivo pra rir.',
      poses: [
        {
          img: 'de-frente-de-maos-dadas-rindo.jpeg',
          nome: 'De frente, de mãos dadas, rindo',
          corpo: 'Os dois de perfil, um de frente pro outro, bem próximos mas sem se abraçar. Só as mãos se dão, embaixo, entre os corpos. Os rostos quase se tocam e o riso é o assunto. Ninguém olha pra câmera.',
          quadro: 'Vertical, corpo inteiro, o casal no terço esquerdo e uma parede vazia ocupando o resto. É o vazio de um lado que faz a foto respirar.',
          luz: 'Luz difusa e clara de ambiente interno. Parede lisa e clara atrás, pra silhueta dos dois ficar legível.',
          onde: 'Qualquer parede clara e lisa, com espaço lateral sobrando.',
          tags: ['em-pe', 'distancia'],
        },
        {
          img: 'abraco-por-tras-maos-cruzadas.jpeg',
          nome: 'Abraço por trás, mãos cruzadas',
          corpo: 'Ele atrás, os dois braços passando por cima dos ombros dela e cruzando na frente do peito. As mãos dela sobem e se apoiam sobre as dele. Ele olha pra ela; ela olha pra cima e pro lado, rindo.',
          quadro: 'Vertical, do quadril pra cima, os dois no terço esquerdo.',
          luz: 'Luz clara e uniforme. O contraste entre a roupa escura dele e a clara dela é o que separa os dois corpos no quadro.',
          onde: 'Parede clara. Funciona igual em pé numa varanda ou num mirante.',
          tags: ['em-pe', 'distancia'],
        },
        {
          img: 'abraco-de-lado-rindo.jpeg',
          nome: 'Abraço de lado, rindo',
          corpo: 'Ele atrás e de lado, os braços em volta da cintura dela, puxando. Ela se inclina pra trás no abraço, cabeça jogada, rindo aberto e olhando pra cima. É movimento, não pose parada.',
          quadro: 'Vertical, três-quartos de corpo. Deixe espaço acima da cabeça dela, porque a inclinação come quadro.',
          luz: 'Luz de ambiente clara e frontal.',
          onde: 'Qualquer canto com parede lisa e espaço pra se mexer.',
          tags: ['em-pe', 'distancia'],
        },
        {
          img: 'bracos-na-nuca-inclinada-pra-tras.jpeg',
          nome: 'Braços na nuca, inclinada pra trás',
          corpo: 'Ela passa os dois braços em volta do pescoço dele e se joga pra trás, com o peso sustentado pelas mãos dele na lombar. Os dois rostos se aproximam, rindo. Exige confiança — e é o riso do desequilíbrio que faz a foto.',
          quadro: 'Vertical, três-quartos de corpo, o casal no centro-direita. Câmera na altura do peito.',
          luz: 'Luz frontal clara. Como há movimento, precisa de luz suficiente pra não sair tremido.',
          onde: 'Parede clara com espaço livre atrás dela pra inclinação.',
          tags: ['em-pe', 'distancia'],
        },
        {
          img: 'detalhe-das-maos-e-do-celular.jpeg',
          nome: 'Detalhe das mãos e do celular',
          corpo: 'Ninguém posa: uma mão segura o celular com a câmera frontal aberta mostrando os dois rostos, e embaixo as outras duas mãos se encontram, com os anéis à vista. A foto é a soma de dois planos.',
          quadro: 'Vertical, câmera apontada pra baixo, pro próprio colo. O celular no terço de cima, as mãos no de baixo, o chão como fundo.',
          luz: 'Luz de dia, sombra aberta. O celular vira uma segunda fonte de luz e ilumina as mãos.',
          onde: 'Qualquer lugar sentados. É a foto de anúncio de noivado, mas serve pra qualquer detalhe de mãos.',
          tags: ['sentada', 'sem-rosto', 'objeto', 'de-cima', 'braco'],
        },
      ],
    },
    {
      id: 'china',
      emoji: '🇨🇳',
      nome: 'China',
      resumo: 'Cenários de escala absurda — arquitetura enorme, montanha vertical, arranha-céu grudado no outro. A tentação é caber tudo no quadro e virar formiga. Todas essas fazem o contrário: escolhem UMA coisa como assunto e usam o corpo pra dar escala a ela, sem competir.',
      poses: [
        {
          img: 'sentado-na-escadaria-do-portal.jpeg',
          nome: 'Sentado na escadaria do portal',
          corpo: 'Sentado num degrau, no eixo da escada, joelhos dobrados e os braços cruzados apoiados neles. Ombros pra frente, sorriso fechado, olhar na lente. O corpo compacto é de propósito: quanto menos você ocupa, maior fica o cenário.',
          quadro: 'Vertical, você pequeno no terço de baixo e centrado no eixo da escadaria. A simetria é tudo — sair do eixo estraga. Câmera na altura do chão, apontando pra cima.',
          luz: 'Dia nublado. Perfeito aqui, porque o céu branco recorta o arco de pedra e não estoura.',
          onde: 'Escadaria monumental no eixo central. Esta é a subida do Portal do Céu, em Tianmen (Zhangjiajie).',
          tags: ['sentada', 'de-baixo', 'distancia'],
        },
        {
          img: 'nuca-em-primeiro-plano-com-o-templo.jpeg',
          nome: 'Nuca em primeiro plano com o templo',
          corpo: 'Você entra só como nuca e ombro, desfocado no canto de baixo, de costas e olhando pra cima. Não precisa expressão nenhuma — a única exigência é ficar perto da lente e imóvel.',
          quadro: 'Vertical. Foque no monumento, não em você: a cabeça desfocada em primeiro plano cria profundidade e faz o templo parecer maior. Você ocupa o canto inferior esquerdo.',
          luz: 'Sol alto de céu azul limpo, o que satura o azul e o dourado da construção.',
          onde: 'Qualquer monumento alto e detalhado. Este é o Salão de Oração pelas Boas Colheitas, no Templo do Céu, em Pequim — a placa 祈年殿 aparece no quadro.',
          tags: ['em-pe', 'sem-rosto', 'sol-alto', 'distancia'],
        },
        {
          img: 'apoiado-no-corrimao-do-mirante.jpeg',
          nome: 'Apoiado no corrimão do mirante',
          corpo: 'De perfil, uma mão apoiada no corrimão de madeira e o corpo levemente inclinado sobre ele. Olhar pra frente, pra paisagem — nunca pra lente. É a pose de quem foi ver a vista e não de quem foi ser fotografado.',
          quadro: 'Vertical, você no terço esquerdo e de perfil, com os pilares de pedra desfocados ocupando o resto. Um galho no topo do quadro fecha a moldura.',
          luz: 'Manhã de céu limpo, sol batendo de frente no rosto de perfil.',
          onde: 'Mirante com corrimão rústico. Estes são os pilares de arenito de Zhangjiajie.',
          tags: ['em-pe', 'sol-alto', 'distancia'],
        },
        {
          img: 'de-perfil-na-janela-do-cafe.jpeg',
          nome: 'De perfil na janela do café',
          corpo: 'Em pé de perfil junto ao vidro, quase em silhueta, uma mão na alça da bolsa e a outra segurando um copo. Olhar pra fora. Corpo relaxado, sem tensão nenhuma.',
          quadro: 'Vertical. Você escura no terço esquerdo, e a janela funciona como quadro: o telhado do templo e os prédios atrás são o assunto. As esquadrias dividem a cena em painéis.',
          luz: 'Contraluz total — você fica escura de propósito e a rua lá fora fica clara. Não tente iluminar o rosto: a silhueta é o efeito.',
          onde: 'Qualquer janelão de café ou restaurante com vista. Vale procurar café em andar alto — a vista de cima resolve a foto sozinha.',
          tags: ['em-pe', 'sem-rosto', 'objeto', 'distancia'],
        },
        {
          img: 'em-pe-na-rua-dos-arranha-ceus.jpeg',
          nome: 'Em pé na rua dos arranha-céus',
          corpo: 'Em pé no meio da via, braços soltos, câmera pendurada no ombro, olhar pra cima e pro lado — como se estivesse reparando nos prédios. Peso nos dois pés, nada de contrapposto: aqui a pose é neutra de propósito.',
          quadro: 'Vertical, você pequeno no terço de baixo e centrado. Câmera bem baixa, apontando pra cima, pras torres convergirem acima da sua cabeça.',
          luz: 'Dia de céu branco e cinza. Luz plana ajuda: ninguém fica em sombra dura entre os prédios.',
          onde: 'Rua estreita entre torres altas. Nesta, os letreiros Hotel Indigo e Ascott aparecem no quadro — não consegui confirmar a cidade.',
          tags: ['em-pe', 'de-baixo', 'distancia'],
        },
        {
          img: 'de-costas-diante-da-torre-na-chuva.jpeg',
          nome: 'De costas diante da torre, na chuva',
          corpo: 'De costas pra câmera, em pé diante do corrimão, uma mão no bolso, cabeça virada pra cima olhando a torre. Nada de rosto, nada de expressão — só a silhueta do casaco e a direção do olhar.',
          quadro: 'Vertical, você pequeno no terço de baixo e fora do centro, com a torre inteira subindo no eixo do quadro. Câmera na altura do peito.',
          luz: 'Noite de chuva e neblina — e é isso que faz a foto: o chão molhado reflete as luzes e a névoa apaga o fundo, deixando só a torre. Casaco de cor forte resolve o contraste.',
          onde: 'Orla com vista frontal pra um monumento iluminado. Esta é a Torre Pérola do Oriente, em Xangai, vista do outro lado do rio.',
          tags: ['em-pe', 'sem-rosto', 'noite', 'distancia'],
        },
      ],
    },
    {
      id: 'paris',
      emoji: '🇫🇷',
      nome: 'Paris',
      resumo: 'Aqui o cenário é o assunto, e ele é vertical: torre, colunas, colunata. Todas essas resolvem o mesmo problema — como aparecer sem tapar o monumento e sem virar formiga na frente dele. A resposta é sempre a mesma: câmera baixa e algo em primeiro plano pra dar profundidade.',
      poses: [
        {
          img: 'encostada-na-grade-com-a-torre-atras.jpeg',
          nome: 'Encostada na grade com a torre atrás',
          corpo: 'De costas pra grade, os dois braços abertos apoiados no corrimão e uma perna cruzada na frente da outra. A bolsa pende de uma mão. Olhar pro lado, fora da lente.',
          quadro: 'Vertical, corpo inteiro, você embaixo e centralizada com a torre subindo atrás do seu ombro. Câmera baixa apontando um pouco pra cima pra caber a torre inteira — fotografar de cima e cortar o topo é o erro clássico aqui.',
          luz: 'Sol de frente em dia de céu limpo. A torre atrás fica clara e desfocada; você precisa estar no sol também, senão vira silhueta.',
          onde: 'Ponte com vista frontal pra torre. Esta é a Pont de Bir-Hakeim, identificada pela grade verde e pelas colunas rebitadas.',
          tags: ['em-pe', 'sol-alto', 'distancia'],
        },
        {
          img: 'encostada-na-coluna-de-aco.jpeg',
          nome: 'Encostada na coluna de aço',
          corpo: 'Encostada de lado numa coluna, ombro apoiado, uma perna dobrada com o pé apoiado atrás. Uma mão sobe até a gola da jaqueta, perto do cabelo. Olhar pro lado, sério.',
          quadro: 'Vertical, você colada na coluna no terço direito e a torre inteira no terço esquerdo. Câmera baixa. A coluna escura em primeiro plano é o que cria profundidade e te separa do céu.',
          luz: 'Sol lateral de dia limpo. A coluna em contraluz recorta a sua silhueta.',
          onde: 'Mesma ponte, do lado de fora da colunata.',
          tags: ['em-pe', 'sol-alto', 'distancia'],
        },
        {
          img: 'andando-no-meio-da-colunata.jpeg',
          nome: 'Andando no meio da colunata',
          corpo: 'Andando pelo meio da via, um pé cruzando na frente do outro em passo largo. A jaqueta desce dos dois braços e a bolsa balança numa mão. Olhar pro lado, queixo alto.',
          quadro: 'Vertical, corpo inteiro, você centrada exatamente no eixo das colunas: a perspectiva fugindo pros dois lados é o assunto da foto. Sair do eixo estraga o efeito.',
          luz: 'Dia nublado ou de sol fraco. A passarela coberta faz a luz entrar de lado e uniforme, sem sombra dura.',
          onde: 'A passarela inferior da Pont de Bir-Hakeim, entre as colunas de aço. É ponto conhecidíssimo — vá cedo, porque enche.',
          tags: ['em-pe', 'distancia'],
        },
        {
          img: 'encostada-na-coluna-de-pedra.jpeg',
          nome: 'Encostada na coluna de pedra',
          corpo: 'De lado, ombro e mão apoiados na coluna, pernas cruzadas com o pé de trás apontado. Tronco levemente torcido pra câmera, olhar direto e sério.',
          quadro: 'Vertical, corpo inteiro, você entre duas colunas com a fileira delas fugindo atrás. Câmera na altura da cintura pra alongar a perna.',
          luz: 'Você na sombra da colunata e a pedra clara atrás pegando sol. Sombra aberta com fundo claro é a luz mais fácil que existe pra rosto — não tem sombra dura em lugar nenhum.',
          onde: 'Qualquer arcada ou colunata de pedra. Paris tem de sobra; a mesma pose funciona em Lisboa, Roma ou Bolonha.',
          tags: ['em-pe', 'sol-alto', 'distancia'],
        },
        {
          img: 'sentada-na-balaustrada-pernas-cruzadas.jpeg',
          nome: 'Sentada na balaustrada, pernas cruzadas',
          corpo: 'Sentada de lado na balaustrada, uma perna cruzada sobre a outra e os pés apontados pra baixo. Uma mão apoiada na pedra atrás do corpo, a outra descansando na perna. Tronco torcido pra câmera, olhar direto.',
          quadro: 'Vertical, corpo inteiro. Câmera na altura da balaustrada ou um pouco abaixo, com o pátio desfocado atrás — use o modo retrato pro fundo virar borrão e não competir.',
          luz: 'Você na sombra da arcada, o pátio atrás no sol. É esse contraste que te separa do fundo sem precisar de edição.',
          onde: 'Qualquer balaustrada de pedra na altura do quadril, de preferência com um pátio ou praça iluminada atrás.',
          tags: ['sentada', 'sol-alto', 'distancia'],
        },
        {
          img: 'na-escadaria-com-a-torre-ao-fundo.jpeg',
          nome: 'Na escadaria com a torre ao fundo',
          corpo: 'Em pé na escada, encostada na balaustrada, pernas cruzadas com o pé de trás apontado num degrau abaixo. Uma mão sobe até a nuca, a outra segura a bolsa. Sorriso aberto.',
          quadro: 'Vertical, corpo inteiro. Câmera alguns degraus abaixo de você, apontando pra cima: a diagonal do corrimão alonga a perna e a torre entra no canto de cima, sem competir com você.',
          luz: 'Sol alto de dia limpo, com você na sombra da escada e a torre no sol. O contraste separa você do fundo.',
          onde: 'Escadaria com balaustrada e vista pra torre. Não identifiquei qual é esta — dá pra ver que é uma rua alta residencial, mas não vou chutar o endereço.',
          tags: ['em-pe', 'sol-alto', 'distancia'],
        },
      ],
    },
  ],
};
